mtk_scheduler: fix incompatible pointer types build breaks
Errors:
drivers/misc/mediatek/sched/scheduler.c:281:4: error: incompatible pointer types passing 'void (void *, struct cpumask *, unsigned long, unsigned long, unsigned long *)' to parameter of type 'void (*)(void *, const struct cpumask *, unsigned long, unsigned long, unsigned long *)' [-Werror,-Wincompatible-pointer-types]

Change-Id: Ice0247ba9a84a4f99d81e21d8979129415737b98
CR-Id: ALPS05516247
Feature: [Module]Kernel Maintenance
Signed-off-by: Miles Chen <miles.chen@mediatek.com>