battery: remove the use of irq_to_desc
irq_to_desc is restrict exported by commit 64a1b95bb9fe3ec76e1a2cd803eff06389341ae4
("genirq: Restrict export of irq_to_desc()").

Remove the use of irq_to_desc().

Error:
ERROR: modpost: "irq_to_desc" [drivers/power/supply/mt6359p_battery.ko] undefined!

Change-Id: I47066abbed8df1fcdca01a2206f8621de1151e59
Signed-off-by: Miles Chen <miles.chen@mediatek.com>
Feature: [Module]Kernel Maintenance
CR-Id: ALPS05672993