locking_aee: fix pr_fmt macro redefined build breaks
Errors:
drivers/misc/mediatek/locking/locking_aee_main.c:6:9: error: 'pr_fmt' macro redefined [-Werror,-Wmacro-redefined]

(cherry-picked from commit 06bc8574ca7f735acaf01012f5f4a53f2dc0ca54)
Change-Id: I74beca59b5be061596e59c9667963144bee726c2
CR-Id: ALPS05511922
Feature: [Module]Kernel Maintenance
Signed-off-by: Miles Chen <miles.chen@mediatek.com>
(cherry picked from commit f918302676de5e036927a47e1044405dbe027b56)