pbm: fix nr_cap_states build breaks
Errors:
kernel-mainline/drivers/misc/mediatek/pbm/mtk_pbm.c:628:48: error: no member named 'nr_cap_states' in 'struct em_perf_domain'; did you mean 'nr_perf_states'?

Change-Id: Ie941a8a0a41519a0cd68f3e7aaabd614a1094ea3
CR-Id: ALPS05576687
Feature: [Module]Kernel Maintenance
Signed-off-by: Miles Chen <miles.chen@mediatek.com>