cpufreq,arm,arm64: export topology_set_freq_scale
EXPORT_SYMBOL_GPL(topology_set_freq_scale)
Errors:
ERROR: modpost: "topology_set_freq_scale" [drivers/cpufreq/mediatek-cpufreq-hw.ko] undefined!

Change-Id: I538788f3f30c4fbe97d17aaa48d0b3e4513d372a
CR-Id: ALPS05431666
Feature: [Module]Kernel Maintenance
Signed-off-by: Miles Chen <miles.chen@mediatek.com>
(cherry picked from commit 4e6bd83cb37488daa1bd6fef853c3932c314577c)