battery: fix __nocfi build breaks
Remove __nocfi

Error:
drivers/power/supply/mt6359p-gauge.c:3219:19: error: expected ';' after top level declarator
drivers/power/supply/mt6359p-gauge.c:3368:25: error: use of undeclared identifier 'mt6359_gauge_of_match'; did you mean 'mt6359_gauge_remove'?
drivers/power/supply/mt6359p-gauge.c:3371:11: error: use of undeclared identifier 'mt6359_gauge_probe'
drivers/power/supply/mt6359p-gauge.c:3374:13: error: use of undeclared identifier 'mt6359_gauge_suspend'
drivers/power/supply/mt6359p-gauge.c:3375:12: error: use of undeclared identifier 'mt6359_gauge_resume'; did you mean 'mt6359_gauge_remove'?
drivers/power/supply/mt6359p-gauge.c:3378:21: error: use of undeclared identifier 'mt6359_gauge_of_match'; did you mean 'mt6359_gauge_remove'?

Signed-off-by: Miles Chen <miles.chen@mediatek.com>
Change-Id: I6ab0867425896021feb9b1d0caee1218afd98d2f
CR-Id: ALPS05298037
Feature: [Module]Kernel Maintenance
Signed-off-by: Miles Chen <miles.chen@mediatek.com>