disp: fix allmodconfig build breaks
fix disp related allmodconfig build breaks

build command:
ARCH=arm64 make mrproper allmodconfig all

Errors:
drivers/gpu/drm/mediatek/mediatek_v2/mtk_drm_mmp.c:235:10: error: 'mtk_drm_drv.h' file not found with <angled> include; use "quotes" instead

Change-Id: I1b69ad9b3449d64c05d41fd60b4403d45cba05f7
Cc: Freya Li <freya.li@mediatek.com>
Signed-off-by: Miles Chen <miles.chen@mediatek.com>
Feature: Kernel SI Operation
CR-Id: ALPS05903624