lens: fix timespec build breaks
Errors:
drivers/misc/mediatek/lens/proprietary/main3/main3_lens.c:234:18: error: variable has incomplete type 'struct timespec'
drivers/misc/mediatek/lens/proprietary/sub2/sub2_lens.c:228:18: error: variable has incomplete type 'struct timespec'
drivers/misc/mediatek/lens/proprietary/main2/main2_lens.c:279:18: error: variable has incomplete type 'struct timespec'
drivers/misc/mediatek/lens/proprietary/sub/sub_lens.c:236:18: error: variable has incomplete type 'struct timespec'
drivers/misc/mediatek/lens/proprietary/main/main_lens.c:344:18: error: variable has incomplete type 'struct timespec'

Signed-off-by: Miles Chen <miles.chen@mediatek.com>
Change-Id: I442c6d8dc9c67072edf9db0b98e18e336376ceb2
CR-Id: ALPS05298037
Feature: [Module]Kernel Maintenance
Signed-off-by: Miles Chen <miles.chen@mediatek.com>