imgsensor: fix proc_create() build breaks
Error:
drivers/misc/mediatek/imgsensor/src/mt6873/../common/v1_1/imgsensor_proc.c:573:46: error: incompatible pointer types passing 'const struct file_operations *' to parameter of type 'const struct proc_ops *' [-Werror,-Wincompatible-pointer-types]
drivers/misc/mediatek/imgsensor/src/mt6873/../common/v1_1/imgsensor_proc.c:574:47: error: incompatible pointer types passing 'const struct file_operations *' to parameter of type 'const struct proc_ops *' [-Werror,-Wincompatible-pointer-types]
drivers/misc/mediatek/imgsensor/src/mt6873/../common/v1_1/imgsensor_proc.c:575:47: error: incompatible pointer types passing 'const struct file_operations *' to parameter of type 'const struct proc_ops *' [-Werror,-Wincompatible-pointer-types]
drivers/misc/mediatek/imgsensor/src/mt6873/../common/v1_1/imgsensor_proc.c:576:47: error: incompatible pointer types passing 'const struct file_operations *' to parameter of type 'const struct proc_ops *' [-Werror,-Wincompatible-pointer-types]
drivers/misc/mediatek/imgsensor/src/mt6873/../common/v1_1/imgsensor_proc.c:577:47: error: incompatible pointer types passing 'const struct file_operations *' to parameter of type 'const struct proc_ops *' [-Werror,-Wincompatible-pointer-types]
drivers/misc/mediatek/imgsensor/src/mt6873/../common/v1_1/imgsensor_proc.c:578:47: error: incompatible pointer types passing 'const struct file_operations *' to parameter of type 'const struct proc_ops *' [-Werror,-Wincompatible-pointer-types]
drivers/misc/mediatek/imgsensor/src/mt6873/../common/v1_1/imgsensor_proc.c:579:47: error: incompatible pointer types passing 'const struct file_operations *' to parameter of type 'const struct proc_ops *' [-Werror,-Wincompatible-pointer-types]
drivers/misc/mediatek/imgsensor/src/mt6873/../common/v1_1/imgsensor_proc.c:580:47: error: incompatible pointer types passing 'const struct file_operations *' to parameter of type 'const struct proc_ops *' [-Werror,-Wincompatible-pointer-types]
drivers/misc/mediatek/imgsensor/src/mt6873/../common/v1_1/imgsensor_proc.c:582:5: error: incompatible pointer types passing 'const struct file_operations *' to parameter of type 'const struct proc_ops *' [-Werror,-Wincompatible-pointer-types]
drivers/misc/mediatek/imgsensor/src/mt6873/../common/v1_1/imgsensor_proc.c:584:5: error: incompatible pointer types passing 'const struct file_operations *' to parameter of type 'const struct proc_ops *' [-Werror,-Wincompatible-pointer-types]
drivers/misc/mediatek/imgsensor/src/mt6873/../common/v1_1/imgsensor_proc.c:587:44: error: incompatible pointer types passing 'const struct file_operations *' to parameter of type 'const struct proc_ops *' [-Werror,-Wincompatible-pointer-types]

Signed-off-by: Miles Chen <miles.chen@mediatek.com>
Change-Id: I88929604582300853869cdf2d3ab228b7d332026
CR-Id: ALPS05298037
Feature: [Module]Kernel Maintenance
Signed-off-by: Miles Chen <miles.chen@mediatek.com>
Source_Git_Sha: 4e96838efdddaf4b82684dd65a6954d7b28577f5