remoteproc: qcom_common: Fix qcom_sysmon_get_reason() declaration
Saw the following compilation error when compiling for
sdxpinn.config,

ld.lld: error: duplicate symbol: qcom_sysmon_get_reason
>>> defined at qcom_common.h:111 (drivers/soc/qcom/../../remoteproc/qcom_common.h:111)
>>>            soc/qcom/pdr_interface.o:(qcom_sysmon_get_reason) in archive drivers/built-in.a
>>> defined at qcom_common.h:111 (drivers/remoteproc/qcom_common.h:111)
>>>            remoteproc/qcom_common.o:(.text+0x0) in archive drivers/built-in.a

Fix it.

Fixes: b52694ed407b ("remoteproc: Add snapshot of remoteproc drivers")
Change-Id: I0f7d75ce5ab01f725846e514676a37b50be2b83b
Signed-off-by: Subbaraman Narayanamurthy <quic_subbaram@quicinc.com>