mtprof: fix struct stack_trace build breaks
Errors:
drivers/misc/mediatek/mtprof/irq_monitor_test.c:178:7: error: incompatible pointer types passing 'const struct file_operations *' to parameter of type 'const struct proc_ops *' [-Werror,-Wincompatible-pointer-types]
drivers/misc/mediatek/mtprof/irq_monitor_main.c:72:21: error: field has incomplete type 'struct stack_trace'
drivers/misc/mediatek/mtprof/irq_monitor_main.c:86:21: error: field has incomplete type 'struct stack_trace'
drivers/misc/mediatek/mtprof/irq_monitor_main.c:98:7: error: incomplete definition of type 'struct stack_trace'
drivers/misc/mediatek/mtprof/irq_monitor_main.c:99:7: error: incomplete definition of type 'struct stack_trace'
drivers/misc/mediatek/mtprof/irq_monitor_main.c:100:7: error: incomplete definition of type 'struct stack_trace'
drivers/misc/mediatek/mtprof/irq_monitor_main.c:102:7: error: incomplete definition of type 'struct stack_trace'
drivers/misc/mediatek/mtprof/irq_monitor_main.c:103:2: error: implicit declaration of function 'save_stack_trace' [-Werror,-Wimplicit-function-declaration]
drivers/misc/mediatek/mtprof/irq_monitor_main.c:105:11: error: incomplete definition of type 'struct stack_trace'
drivers/misc/mediatek/mtprof/irq_monitor_main.c:106:11: error: incomplete definition of type 'struct stack_trace'
drivers/misc/mediatek/mtprof/irq_monitor_main.c:106:26: error: incomplete definition of type 'struct stack_trace'
drivers/misc/mediatek/mtprof/irq_monitor_main.c:107:8: error: incomplete definition of type 'struct stack_trace'
drivers/misc/mediatek/mtprof/irq_monitor_main.c:117:23: error: incomplete definition of type 'struct stack_trace'
drivers/misc/mediatek/mtprof/irq_monitor_main.c:119:18: error: incomplete definition of type 'struct stack_trace'
drivers/misc/mediatek/mtprof/irq_monitor_main.c:120:18: error: incomplete definition of type 'struct stack_trace'

Change-Id: I4c70248629bfe9900ebbeaa7c548b744d91e357d
CR-Id: ALPS05438846
Feature: [Module]Kernel Maintenance
Signed-off-by: Kuan-Ying Lee <Kuan-Ying.Lee@mediatek.com>