pinctrl: mediatek: fix allmodconfig build breaks
fix pinctrl related allmodconfig build breaks

build command:
ARCH=arm64 make mrproper allmodconfig all

Errors:
drivers/pinctrl/mediatek/pinctrl-mtk-common-v2_debug.c:14:10: error: '../../gpio/gpiolib.h' file not found with <angled> include; use "quotes" instead

Change-Id: I243d3d143f4f1006cc45363ca25bafb9d38e80ea
Cc: Light Hsieh <light.hsieh@mediatek.com>
Signed-off-by: Miles Chen <miles.chen@mediatek.com>
Feature: Kernel SI Operation
CR-Id: ALPS05903624