GZ: fix procfs, kfree, compat_ptr build breaks
Error:
drivers/misc/mediatek/geniezone/gz-trusty/trusty.c:89:16: error: expected string literal in 'asm'
drivers/misc/mediatek/geniezone/gz_main.c:819:12: error: implicit declaration of function 'compat_ptr' [-Werror,-Wimplicit-function-declaration]
drivers/misc/mediatek/geniezone/gz_main.c:918:12: error: implicit declaration of function 'compat_ptr' [-Werror,-Wimplicit-function-declaration]
drivers/misc/mediatek/geniezone/gz_main.c:1286:29: error: implicit declaration of function 'compat_ptr' [-Werror,-Wimplicit-function-declaration]
drivers/misc/mediatek/geniezone/gz-trusty/trusty-virtio.c:491:10: error: implicit declaration of function 'kzalloc' [-Werror,-Wimplicit-function-declaration]
drivers/misc/mediatek/geniezone/gz-trusty/trusty-virtio.c:552:2: error: implicit declaration of function 'kfree' [-Werror,-Wimplicit-function-declaration]
drivers/misc/mediatek/geniezone/gz-trusty/trusty-virtio.c:672:3: error: implicit declaration of function 'kfree' [-Werror,-Wimplicit-function-declaration]
drivers/misc/mediatek/geniezone/gz-trusty/trusty-virtio.c:777:10: error: implicit declaration of function 'kzalloc' [-Werror,-Wimplicit-function-declaration]
drivers/misc/mediatek/geniezone/gz-trusty/trusty-virtio.c:790:3: error: implicit declaration of function 'kfree' [-Werror,-Wimplicit-function-declaration]
drivers/misc/mediatek/geniezone/gz-trusty/trusty-virtio.c:821:9: error: implicit declaration of function 'kzalloc' [-Werror,-Wimplicit-function-declaration]
drivers/misc/mediatek/geniezone/gz-trusty/trusty-virtio.c:891:3: error: implicit declaration of function 'kfree' [-Werror,-Wimplicit-function-declaration]
drivers/misc/mediatek/geniezone/gz-trusty/trusty-virtio.c:897:3: error: implicit declaration of function 'kfree' [-Werror,-Wimplicit-function-declaration]
drivers/misc/mediatek/geniezone/gz-trusty/trusty-virtio.c:904:2: error: implicit declaration of function 'kfree' [-Werror,-Wimplicit-function-declaration]
drivers/misc/mediatek/geniezone/gz-trusty/trusty-virtio.c:939:3: error: implicit declaration of function 'kfree' [-Werror,-Wimplicit-function-declaration]
drivers/misc/mediatek/geniezone/gz-trusty/trusty-virtio.c:946:3: error: implicit declaration of function 'kfree' [-Werror,-Wimplicit-function-declaration]
drivers/misc/mediatek/geniezone/gz-trusty/trusty-virtio.c:950:2: error: implicit declaration of function 'kfree' [-Werror,-Wimplicit-function-declaration]
drivers/misc/mediatek/geniezone/gz-trusty/gz-log.c:435:53: error: incompatible pointer types passing 'const struct file_operations *' to parameter of type 'const struct proc_ops *' [-Werror,-Wincompatible-pointer-types]
drivers/misc/mediatek/geniezone/mtee-kree/tz_mmap.c:54:26: error: no member named 'mmap_sem' in 'struct mm_struct'
drivers/misc/mediatek/geniezone/mtee-kree/tz_mmap.c:65:23: error: too many arguments to function call, expected 7, have 8
drivers/misc/mediatek/geniezone/mtee-kree/tz_mmap.c:93:24: error: no member named 'mmap_sem' in 'struct mm_struct'

Signed-off-by: Miles Chen <miles.chen@mediatek.com>
Change-Id: Ibb9060b181615cc8a3175da1fda589d44d2722ed
CR-Id: ALPS05298037
Feature: [Module]Kernel Maintenance
Signed-off-by: Miles Chen <miles.chen@mediatek.com>