disp: fix drm_atomic_helper_legacy_gamma_set build breaks
Errors:
drivers/gpu/drm/mediatek/mediatek_v2/mtk_drm_crtc.c:4693:15: error: use of undeclared
identifier 'drm_atomic_helper_legacy_gamma_set'; did you mean 'drm_atomic_helper_check_modeset'?

Change-Id: I7203746e4a0fb11897444803ea1d316ca036ab9b
Signed-off-by: Miles Chen <miles.chen@mediatek.com>
Feature: [Module]Kernel Maintenance
CR-Id: ALPS05625693