apusys: mem_aosp: fix dma_buf_vmap build breaks
Errors:
drivers/misc/mediatek/apusys/midware/1.5/mdw_mem_aosp.c:120:25: error: too few arguments to function call, expected 2, have 1

Change-Id: I384d6f6e44599ecba9451528f12305045e80f5dc
Signed-off-by: Miles Chen <miles.chen@mediatek.com>
CR-Id: ALPS05568046
Feature: [Module]Kernel Maintenance