[ALPS04783226] scp: fix build breaks when CONFIG_KASAN=y
Fix build breaks when CONFIG_KASAN=y with CC=gcc

drivers/misc/mediatek/scp/mt6885/../v02/scp_excep.c:112:8: error:
cast from pointer to integer of different size
[-Werror=pointer-to-int-cast]
drivers/misc/mediatek/scp/mt6885/../v02/scp_excep.c:113:36: error:
cast from pointer to integer of different size
[-Werror=pointer-to-int-cast]
drivers/misc/mediatek/scp/mt6885/../v02/scp_excep.c:135:6: error:
cast from pointer to integer of different size
[-Werror=pointer-to-int-cast]
drivers/misc/mediatek/scp/mt6885/../v02/scp_excep.c:135:39: error:
cast from pointer to integer of different size
[-Werror=pointer-to-int-cast]
drivers/misc/mediatek/scp/mt6885/../v02/scp_excep.c:252:3: error:
‘scp_aed_title’ may be used uninitialized in this function
[-Werror=maybe-uninitialized]

MTK-Commit-Id: 9e4fca8dbd47cd93a766e8822a0f8b2749e725ac

Change-Id: Ibe9221473903388ad6506a1be726bbabfb12d205
CR-Id: ALPS04783226
Signed-off-by: Miles Chen <miles.chen@mediatek.com>
Feature: TinySys