lpm: fix pm_qos_update_request build breaks
Errors:
drivers/misc/mediatek/lpm/modules/debug/v1/lpm_dbg_cpuidle_state.c:94:5: error: no member named 'disabled' in 'struct cpuidle_state'
drivers/misc/mediatek/lpm/modules/debug/v1/lpm_dbg_cpuidle_state.c:98:3: error: no member named 'disabled' in 'struct cpuidle_state'
drivers/misc/mediatek/lpm/modules/debug/v1/lpm_dbg_cpuidle_status.c:328:4: error: no member named 'disabled' in 'struct cpuidle_state'
drivers/misc/mediatek/lpm/modules/debug/v1/lpm_dbg_cpuidle_status.c:331:17: error: no member named 'disabled' in 'struct cpuidle_state'
drivers/misc/mediatek/lpm/modules/debug/v1/mtk_cpupm_dbg.c:73:2: error: implicit declaration of function 'pm_qos_update_request' [-Werror,-Wimplicit-function-declaration]
drivers/misc/mediatek/lpm/modules/debug/v1/mtk_cpupm_dbg.c:78:2: error: implicit declaration of function 'pm_qos_update_request' [-Werror,-Wimplicit-function-declaration]
drivers/misc/mediatek/lpm/modules/debug/v1/mtk_cpupm_dbg.c:131:2: error: implicit declaration of function 'pm_qos_add_request' [-Werror,-Wimplicit-function-declaration]
drivers/misc/mediatek/lpm/modules/debug/v1/mtk_cpupm_dbg.c:132:3: error: use of undeclared identifier 'PM_QOS_CPU_DMA_LATENCY'
drivers/misc/mediatek/lpm/modules/debug/v1/mtk_cpupm_dbg.c:148:2: error: implicit declaration of function 'pm_qos_remove_request' [-Werror,-Wimplicit-function-declaration]

Change-Id: I2533c16fdeb55e208bda568a8447bc4d62ff566c
CR-Id: ALPS05476666
Feature: [Module]Kernel Maintenance
Signed-off-by: Miles Chen <miles.chen@mediatek.com>