clk: mediatek: mt6853: fix proc_create build breaks
Errors:
drivers/clk/mediatek/clkchk-mt6853.c:279:16: error: implicit declaration of function 'ioremap_nocache' [-Werror,-Wimplicit-function-declaration]
drivers/clk/mediatek/clkdbg.c:1137:21: error: use of undeclared identifier 'GPD_STATE_ACTIVE'; did you mean 'DL_STATE_ACTIVE'?
drivers/clk/mediatek/clkdbg.c:1184:21: error: use of undeclared identifier 'GPD_STATE_ACTIVE'; did you mean 'DL_STATE_ACTIVE'?
drivers/clk/mediatek/clkdbg.c:2096:44: error: incompatible pointer types passing 'const struct file_operations *' to parameter of type 'const struct proc_ops *' [-Werror,-Wincompatible-pointer-types]

Change-Id: I4aee760184982ceb14c7cebfbb80db7f4ccaed88
CR-Id: ALPS05493626
Feature: [Module]Kernel Maintenance
Signed-off-by: Miles Chen <miles.chen@mediatek.com>