disp: fix variable length arrays build breaks
Errors:
drivers/gpu/drm/mediatek/mediatek_v2/mtk_disp_ovl.c:459:11: error: variable length arrays are a C99 feature [-Werror,-Wvla-extension]
drivers/gpu/drm/mediatek/mediatek_v2/mtk_disp_rsz.c:376:11: error: variable length arrays are a C99 feature [-Werror,-Wvla-extension]
drivers/gpu/drm/mediatek/mediatek_v2/mtk_drm_crtc.c:5022:12: error: variable length arrays are a C99 feature [-Werror,-Wvla-extension]
drivers/gpu/drm/mediatek/mediatek_v2/mtk_layering_rule_base.c:470:11: error: variable length arrays are a C99 feature [-Werror,-Wvla-extension]
drivers/gpu/drm/mediatek/mediatek_v2/mtk_drm_lowpower.c:406:12: error: variable length arrays are a C99 feature [-Werror,-Wvla-extension]

Change-Id: I18775456853186c5b5378f05a36439f850a8430b
Signed-off-by: Miles Chen <miles.chen@mediatek.com>
Feature: [Module]Kernel Maintenance
CR-Id: ALPS05595303