apusys: fix timespec, dentry build breaks
Error:
drivers/misc/mediatek/apusys/midware/1.5/mdw_cmd.h:56:18: error: field has incomplete type 'struct timespec'
drivers/misc/mediatek/apusys/midware/1.5/mdw_cmd.h:104:18: error: field has incomplete type 'struct timespec'
drivers/misc/mediatek/apusys/midware/1.5/mdw_cmd.h:105:18: error: field has incomplete type 'struct timespec'
drivers/misc/mediatek/apusys/midware/1.5/mdw_cmd.h:106:18: error: field has incomplete type 'struct timespec'
drivers/misc/mediatek/apusys/midware/1.5/mdw_cmd.h:107:18: error: field has incomplete type 'struct timespec'
drivers/misc/mediatek/apusys/midware/1.5/mdw_cmd.h:108:18: error: field has incomplete type 'struct timespec'
drivers/misc/mediatek/apusys/midware/1.5/mdw_cmd.h:56:18: error: field has incomplete type 'struct timespec'
drivers/misc/mediatek/apusys/midware/1.5/mdw_cmd.h:104:18: error: field has incomplete type 'struct timespec'
drivers/misc/mediatek/apusys/midware/1.5/mdw_cmd.h:105:18: error: field has incomplete type 'struct timespec'
drivers/misc/mediatek/apusys/midware/1.5/mdw_cmd.h:106:18: error: field has incomplete type 'struct timespec'
drivers/misc/mediatek/apusys/midware/1.5/mdw_cmd.h:107:18: error: field has incomplete type 'struct timespec'
drivers/misc/mediatek/apusys/midware/1.5/mdw_cmd.h:108:18: error: field has incomplete type 'struct timespec'
drivers/misc/mediatek/apusys/midware/1.5/mdw_dbg.c:378:14: error: assigning to 'struct dentry *' from incompatible type 'void'
drivers/misc/mediatek/apusys/midware/1.5/mdw_dbg.c:383:16: error: assigning to 'struct dentry *' from incompatible type 'void'
drivers/misc/mediatek/apusys/midware/1.5/mdw_cmd.h:56:18: error: field has incomplete type 'struct timespec'
drivers/misc/mediatek/apusys/midware/1.5/mdw_cmd.h:104:18: error: field has incomplete type 'struct timespec'
drivers/misc/mediatek/apusys/midware/1.5/mdw_cmd.h:105:18: error: field has incomplete type 'struct timespec'

drivers/misc/mediatek/apusys/midware/1.5/mdw_cmd.h:107:18: error: field has incomplete type 'struct timespec'
drivers/misc/mediatek/apusys/midware/1.5/mdw_cmd.h:108:18: error: field has incomplete type 'struct timespec'
drivers/misc/mediatek/apusys/midware/1.5/mdw_cmd.h:56:18: error: field has incomplete type 'struct timespec'
drivers/misc/mediatek/apusys/midware/1.5/mdw_cmd.h:104:18: error: field has incomplete type 'struct timespec'
drivers/misc/mediatek/apusys/midware/1.5/mdw_cmd.h:105:18: error: field has incomplete type 'struct timespec'
drivers/misc/mediatek/apusys/midware/1.5/mdw_cmd.h:106:18: error: field has incomplete type 'struct timespec'
drivers/misc/mediatek/apusys/midware/1.5/mdw_cmd.h:107:18: error: field has incomplete type 'struct timespec'
drivers/misc/mediatek/apusys/midware/1.5/mdw_cmd.h:108:18: error: field has incomplete type 'struct timespec'
drivers/misc/mediatek/apusys/midware/1.5/mdw_cmn.c:18:14: error: incomplete definition of type 'struct timespec'
drivers/misc/mediatek/apusys/midware/1.5/mdw_cmn.c:18:29: error: incomplete definition of type 'struct timespec'
drivers/misc/mediatek/apusys/midware/1.5/mdw_cmn.c:19:10: error: incomplete definition of type 'struct timespec'
drivers/misc/mediatek/apusys/midware/1.5/mdw_cmn.c:19:26: error: incomplete definition of type 'struct timespec'
drivers/misc/mediatek/apusys/midware/1.5/mdw_cmn.c:20:16: error: incomplete definition of type 'struct timespec'
drivers/misc/mediatek/apusys/midware/1.5/mdw_cmn.c:20:32: error: incomplete definition of type 'struct timespec'
drivers/misc/mediatek/apusys/midware/1.5/mdw_cmd.c:357:2: error: implicit declaration of function 'getnstimeofday' [-Werror,-Wimplicit-function-declaration]
drivers/misc/mediatek/apusys/midware/1.5/mdw_cmd.c:538:2: error: implicit declaration of function 'getnstimeofday' [-Werror,-Wimplicit-function-declaration]
drivers/misc/mediatek/apusys/midware/1.5/mdw_cmd.h:56:18: error: field has incomplete type 'struct timespec'
drivers/misc/mediatek/apusys/midware/1.5/mdw_cmd.h:104:18: error: field has incomplete type 'struct timespec'
drivers/misc/mediatek/apusys/midware/1.5/mdw_cmd.h:105:18: error: field has incomplete type 'struct timespec'
drivers/misc/mediatek/apusys/midware/1.5/mdw_cmd.h:106:18: error: field has incomplete type 'struct timespec'
drivers/misc/mediatek/apusys/midware/1.5/mdw_cmd.h:107:18: error: field has incomplete type 'struct timespec'
drivers/misc/mediatek/apusys/midware/1.5/mdw_cmd.h:108:18: error: field has incomplete type 'struct timespec'
drivers/misc/mediatek/apusys/midware/1.5/mdw_cmd.h:56:18: error: field has incomplete type 'struct timespec'
drivers/misc/mediatek/apusys/midware/1.5/mdw_cmd.h:104:18: error: field has incomplete type 'struct timespec'
drivers/misc/mediatek/apusys/midware/1.5/mdw_cmd.h:105:18: error: field has incomplete type 'struct timespec'
drivers/misc/mediatek/apusys/midware/1.5/mdw_cmd.h:106:18: error: field has incomplete type 'struct timespec'
drivers/misc/mediatek/apusys/midware/1.5/mdw_cmd.h:107:18: error: field has incomplete type 'struct timespec'
drivers/misc/mediatek/apusys/midware/1.5/mdw_cmd.h:108:18: error: field has incomplete type 'struct timespec'
drivers/misc/mediatek/apusys/midware/1.5/mdw_sched.c:292:3: error: implicit declaration of function 'getnstimeofday' [-Werror,-Wimplicit-function-declaration]
drivers/misc/mediatek/apusys/midware/1.5/mdw_sched.c:414:3: error: implicit declaration of function 'getnstimeofday' [-Werror,-Wimplicit-function-declaration]
drivers/misc/mediatek/apusys/midware/1.5/mdw_sched.c:437:2: error: implicit declaration of function 'getnstimeofday' [-Werror,-Wimplicit-function-declaration]
drivers/misc/mediatek/apusys/midware/1.5/mdw_cmd.h:56:18: error: field has incomplete type 'struct timespec'
drivers/misc/mediatek/apusys/midware/1.5/mdw_cmd.h:104:18: error: field has incomplete type 'struct timespec'
drivers/misc/mediatek/apusys/midware/1.5/mdw_cmd.h:105:18: error: field has incomplete type 'struct timespec'
drivers/misc/mediatek/apusys/midware/1.5/mdw_cmd.h:106:18: error: field has incomplete type 'struct timespec'
drivers/misc/mediatek/apusys/midware/1.5/mdw_cmd.h:107:18: error: field has incomplete type 'struct timespec'
drivers/misc/mediatek/apusys/midware/1.5/mdw_cmd.h:108:18: error: field has incomplete type 'struct timespec'
drivers/misc/mediatek/apusys/midware/1.5/mdw_cmd.h:56:18: error: field has incomplete type 'struct timespec'
drivers/misc/mediatek/apusys/midware/1.5/mdw_cmd.h:104:18: error: field has incomplete type 'struct timespec'
drivers/misc/mediatek/apusys/midware/1.5/mdw_cmd.h:105:18: error: field has incomplete type 'struct timespec'
drivers/misc/mediatek/apusys/midware/1.5/mdw_cmd.h:106:18: error: field has incomplete type 'struct timespec'
drivers/misc/mediatek/apusys/midware/1.5/mdw_cmd.h:107:18: error: field has incomplete type 'struct timespec'
drivers/misc/mediatek/apusys/midware/1.5/mdw_cmd.h:108:18: error: field has incomplete type 'struct timespec'
drivers/misc/mediatek/apusys/midware/1.5/mdw_drv.c:481:21: error: implicit declaration of function 'compat_ptr' [-Werror,-Wimplicit-function-declaration]
drivers/misc/mediatek/apusys/midware/1.5/mdw_cmd.h:56:18: error: field has incomplete type 'struct timespec'
drivers/misc/mediatek/apusys/midware/1.5/mdw_cmd.h:104:18: error: field has incomplete type 'struct timespec'
drivers/misc/mediatek/apusys/midware/1.5/mdw_cmd.h:105:18: error: field has incomplete type 'struct timespec'
drivers/misc/mediatek/apusys/midware/1.5/mdw_cmd.h:106:18: error: field has incomplete type 'struct timespec'
drivers/misc/mediatek/apusys/midware/1.5/mdw_cmd.h:107:18: error: field has incomplete type 'struct timespec'
drivers/misc/mediatek/apusys/midware/1.5/mdw_cmd.h:108:18: error: field has incomplete type 'struct timespec'
drivers/misc/mediatek/apusys/midware/1.5/mdw_cmd.h:56:18: error: field has incomplete type 'struct timespec'
drivers/misc/mediatek/apusys/midware/1.5/mdw_cmd.h:104:18: error: field has incomplete type 'struct timespec'
drivers/misc/mediatek/apusys/midware/1.5/mdw_cmd.h:105:18: error: field has incomplete type 'struct timespec'
drivers/misc/mediatek/apusys/midware/1.5/mdw_cmd.h:106:18: error: field has incomplete type 'struct timespec'
drivers/misc/mediatek/apusys/midware/1.5/mdw_cmd.h:107:18: error: field has incomplete type 'struct timespec'
drivers/misc/mediatek/apusys/midware/1.5/mdw_cmd.h:108:18: error: field has incomplete type 'struct timespec'
drivers/misc/mediatek/apusys/midware/1.5/mdw_cmd.h:56:18: error: field has incomplete type 'struct timespec'
drivers/misc/mediatek/apusys/midware/1.5/mdw_cmd.h:104:18: error: field has incomplete type 'struct timespec'
drivers/misc/mediatek/apusys/midware/1.5/mdw_cmd.h:105:18: error: field has incomplete type 'struct timespec'
drivers/misc/mediatek/apusys/midware/1.5/mdw_cmd.h:106:18: error: field has incomplete type 'struct timespec'
drivers/misc/mediatek/apusys/midware/1.5/mdw_cmd.h:107:18: error: field has incomplete type 'struct timespec'
drivers/misc/mediatek/apusys/midware/1.5/mdw_cmd.h:108:18: error: field has incomplete type 'struct timespec'

Signed-off-by: Miles Chen <miles.chen@mediatek.com>
Change-Id: I0f30c1c4a31f9075ada38b39860fa9b0154f4e91
CR-Id: ALPS05298037
Feature: [Module]Kernel Maintenance
Signed-off-by: Miles Chen <miles.chen@mediatek.com>