clk: mediatek: fix assigning from incompatible type void build break
drivers/clk/mediatek/clk-fhctl-debug.c:331:18: error: assigning to 'struct dentry *' from incompatible type 'void'

Change-Id: I5e2f4cd70434b964121dc3aef56b17eb80c0bc7c
CR-Id: ALPS05439688
Feature: [Module]Kernel Maintenance
Signed-off-by: Miles Chen <miles.chen@mediatek.com>
(cherry picked from commit 2e245dd9278f5a0c4fe72d31f06e8cb1c4c12dc8)