performance: fix unused function build breaks
Errors:
drivers/misc/mediatek/performance/perf_ioctl/perf_ioctl.c:206:13: error: unused function 'eara_ioctl' [-Werror,-Wunused-function]

Change-Id: I73afbd1583cef994982edc56c412ee835ea99599
CR-Id: ALPS05511922
Feature: [Module]Kernel Maintenance
Signed-off-by: Miles Chen <miles.chen@mediatek.com>