ASoC: fix struct mt6359_priv build breaks
Error:
sound/soc/codecs/mt6359.c:34:6: error: incomplete definition of type 'struct mt6359_priv'
sound/soc/codecs/mt6359.c:42:19: error: incomplete definition of type 'struct mt6359_priv'
sound/soc/codecs/mt6359.c:43:19: error: incomplete definition of type 'struct mt6359_priv'
sound/soc/codecs/mt6359.c:44:19: error: incomplete definition of type 'struct mt6359_priv'
sound/soc/codecs/mt6359.c:47:19: error: incomplete definition of type 'struct mt6359_priv'
sound/soc/codecs/mt6359.c:48:19: error: incomplete definition of type 'struct mt6359_priv'
sound/soc/codecs/mt6359.c:49:25: error: incomplete definition of type 'struct mt6359_priv'
sound/soc/codecs/mt6359.c:60:19: error: incomplete definition of type 'struct mt6359_priv'
sound/soc/codecs/mt6359.c:61:25: error: incomplete definition of type 'struct mt6359_priv'
sound/soc/codecs/mt6359.c:63:25: error: incomplete definition of type 'struct mt6359_priv'
sound/soc/codecs/mt6359.c:69:19: error: incomplete definition of type 'struct mt6359_priv'
sound/soc/codecs/mt6359.c:70:19: error: incomplete definition of type 'struct mt6359_priv'
sound/soc/codecs/mt6359.c:71:25: error: incomplete definition of type 'struct mt6359_priv'
sound/soc/codecs/mt6359.c:74:19: error: incomplete definition of type 'struct mt6359_priv'
sound/soc/codecs/mt6359.c:75:19: error: incomplete definition of type 'struct mt6359_priv'
sound/soc/codecs/mt6359.c:76:25: error: incomplete definition of type 'struct mt6359_priv'
sound/soc/codecs/mt6359.c:88:19: error: incomplete definition of type 'struct mt6359_priv'
sound/soc/codecs/mt6359.c:89:25: error: incomplete definition of type 'struct mt6359_priv'
sound/soc/codecs/mt6359.c:92:19: error: incomplete definition of type 'struct mt6359_priv'

Change-Id: I845e20654a5cf28938f65cc42bba552529001c9a
CR-Id: ALPS05431666
Feature: [Module]Kernel Maintenance
Signed-off-by: Miles Chen <miles.chen@mediatek.com>
(cherry picked from commit c44fb5aa93cdbd5a1a46b8f1a2c2121558ca700e)