TOUCH: fix proc_create build breaks
Errors:
drivers/input/touchscreen/GTP1151/gt1x_generic.c:207:19: error: incompatible pointer types passing 'const struct file_operations *' to parameter of type 'const struct proc_ops *' [-Werror,-Wincompatible-pointer-types]

Change-Id: If19df1820509071c89f1908b1c776735166e7309
CR-Id: ALPS05489813
Feature: [Module]Kernel Maintenance
Signed-off-by: Miles Chen <miles.chen@mediatek.com>
(cherry picked from commit a08ea5a02acde859f9d12fe6ade65f2092165fb1)