[ALPS04783226] vpu: fix build breaks when CONFIG_KASAN=y
Fix the following build breaks when CONFIG_KASAN=y with CC=gcc

drivers/misc/mediatek/apusys/vpu/4.0/vpu_main.c:76:19: error:
format ‘%x’ expects argument of type ‘unsigned int’, but
argument 5 has type ‘uint64_t {aka long long unsigned int}’
[-Werror=format=]

MTK-Commit-Id: aa8cc59a026f322e6d4027d049c3f0b3af0e87d2

Change-Id: Ic6a72ab69b0219b66800a61962476547352fb1a9
CR-Id: ALPS04783226
Signed-off-by: Miles Chen <miles.chen@mediatek.com>
Feature:[Module] APUSYS