[ALPS04292830] mrdump: fix build error
[Detail]
There is the build errors while CONFIG_MTK_RAM_CONSOLE or
CONFIG_MTK_AEE_FEATURE is not set.

Build error:
1. static declaration of aee_rr_curr_exp_type follows non-static
   declaration
2. conflicting types for aee_sram_fiq_save_bin
3. attribute declaration must precede definition
4. redefinition of aee_sram_fiq_log

[Solution]
1. remove the condition so that header file was included.
2. add dummy function of aee_disable_api()
3. clean up repetitive codes.

MTK-Commit-Id: 4134449a007cf8001fb37f71282c51d9c7b89a97

Change-Id: I14ef0e5cd5e74cba4b038ae0c516f0271d8e044f
Signed-off-by: MY Chuang <my.chuang@mediatek.com>
CR-Id: ALPS04292830
Feature: Memory RAM Dump (MRDUMP)
(cherry-pick from 1f920450421c0d3a55ef6d751c067dee857eab87)