scp: fix proc_create() build breaks
Errors:
drivers/misc/mediatek/scp/rv33/scp_dvfs.c:1052:7: error: incompatible pointer types passing 'const struct file_operations *const' to parameter of type 'const struct proc_ops *' [-Werror,-Wincompatible-pointer-types]

Change-Id: Id349a7ac86a549a06a7b8e3896e9e30e43f12844
CR-Id: ALPS05442624
Feature: [Module]Kernel Maintenance
Signed-off-by: Miles Chen <miles.chen@mediatek.com>
(cherry picked from commit 79b0000693ede674b3b3048e8a1631818f77595b)