driver: aee_hang: fix unused variable build breaks
Errors:
drivers/spi/spi-mt65xx.c:697:6: error: variable 'mdata' is used uninitialized whenever 'if' condition is true [-Werror,-Wsometimes-uninitialized]

(cherry-picked from commit cc1b0fb978558d442abd421dd3df77895ef8edce)
Change-Id: Ibbbfd0fc939d7a8cfae855617d3cc6a5d05ea02a
CR-Id: ALPS05511922
Feature: [Module]Kernel Maintenance
Signed-off-by: Miles Chen <miles.chen@mediatek.com>
(cherry picked from commit fcfac6968058df3ea67c4c80a0540049714d3548)