ufs: fix pm_qos_update_request() build breaks
Errors:
drivers/scsi/ufs/ufs-mediatek.c:244:4: error: implicit declaration of function 'pm_qos_update_request' [-Werror,-Wimplicit-function-declaration]
drivers/scsi/ufs/ufs-mediatek.c:377:2: error: implicit declaration of function 'pm_qos_add_request' [-Werror,-Wimplicit-function-declaration]
drivers/scsi/ufs/ufs-mediatek.c:377:40: error: use of undeclared identifier 'PM_QOS_CPU_DMA_LATENCY'

Change-Id: I7a32e5fe35c7956c947ed417264076cd51c95f67
CR-Id: ALPS05408933
Feature: [Module]Kernel Maintenance
Signed-off-by: Kuan-Ying Lee <Kuan-Ying.Lee@mediatek.com>