cpufreq: fix topology_set_freq_scale undefined build breaks
Errors:
ERROR: modpost: "topology_set_freq_scale" [drivers/cpufreq/mediatek-cpufreq-hw.ko] undefined!

Change-Id: Ica84d6b5b0407aa21c14d8bb89b71d3e46c321a3
CR-Id: ALPS05431666
Feature: [Module]Kernel Maintenance
Signed-off-by: Miles Chen <miles.chen@mediatek.com>
(cherry picked from commit a542308399872c8ac22a83b3c1f35c886fe49981)