drivers: pinctrl: Export msm_qup_write and msm_qup_read functions
Commit 9c0e5c705430 ("drivers: pinctrl: Add support for read/write of QUP
registers") added msm_qup_write but didn't export it resulting in the
following error:

ERROR: "msm_qup_write" [drivers/i3c/master/i3c-master-msm-geni.ko]
undefined. So export msm_qup_write and msm_qup_read functions for
client drivers.

Change-Id: I5b1a307e3673b3f12b1bf0c665df4edf0d1769ed
Signed-off-by: Jordan Crouse <jcrouse@codeaurora.org>
Signed-off-by: Prateek Sood <prsood@codeaurora.org>