scp: fix tautological-overlap-compare build breaks
Errors:
drivers/misc/mediatek/scp/rv55/scp_dvfs.c:834:5: error: overlapping comparisons always evaluate to false [-Werror,-Wtautological-overlap-compare]

Change-Id: I085ed9943c8ad58effcdb36793beda78d91a163b
CR-Id: ALPS05511922
Feature: [Module]Kernel Maintenance
Signed-off-by: Miles Chen <miles.chen@mediatek.com>
(cherry picked from commit ce92042e53127e5e1a7dc487fd92f311c607dfdc)