drivers: qcom: Fix build issue when !CONFIG_MSM_QMP
Mark all empty ddr_stats_* functions in soc_sleep_stats.h
as static inline, so as to avoid link errors due to
multiple definitions when CONFIG_MSM_QMP is not defined.

  ld.lld: error: duplicate symbol:
  ddr_stats_freq_sync_send_msg
  >>> defined at soc_sleep_stats.h:34
  >>> (include/soc/qcom/soc_sleep_stats.h:34)
  >>>   soc/qcom/soc_sleep_stats.o:(ddr_stats_freq_sync_send_msg)
  >>>   in archive drivers/built-in.a
  >>> defined at soc_sleep_stats.h:34
  >>> (include/soc/qcom/soc_sleep_stats.h:34)
  >>>            soc/qcom/boot_stats.o:(.text+0x0) in
  >>>            archive drivers/built-in.a

Change-Id: I10b9698855d3cabcb4ddc87bec047906614246fe
Signed-off-by: Shiraz Hashim <quic_shashim@quicinc.com>