iommu/mediatek: fix iommu_priv build break
Solve the conflict between the upstream kernel.

Error:
drivers/iommu/mtk_iommu.c:403:59: error: no member named 'iommu_priv' in 'struct iommu_fwspec'
drivers/iommu/mtk_iommu.c:418:35: error: subscripted value is not an array, pointer, or vector
drivers/iommu/mtk_iommu.c:549:37: error: no member named 'iommu_fwspec' in 'struct device'
drivers/iommu/mtk_iommu.c:601:59: error: no member named 'iommu_priv' in 'struct iommu_fwspec'

Signed-off-by: Miles Chen <miles.chen@mediatek.com>
Change-Id: I1741b2437d9676fd52438086ff9f22670c538e31
CR-Id: ALPS05298037
Feature: [Module]Kernel Maintenance
Signed-off-by: Miles Chen <miles.chen@mediatek.com>
Source_Git_Sha: 7d0e86abbff96f09e66e98df4db05976b9cf9fbd