[ALPS06374686] GPU: fix ksys_close build breaks
1) Fix ksys_close build breaks since the API is replaced by close_fd.

Error:
drivers/gpu/mediatek/gpu_mali/mali_valhall/mali-r25p0/drivers/gpu/arm/midgard/mali_kbase_sync.h:165:2: error: implicit declaration of function ksys_close [-Werror,-Wimplicit-function-declaration]
drivers/gpu/mediatek/gpu_mali/mali_valhall/mali-r25p0/drivers/gpu/arm/midgard/mali_kbase_sync.h:165:2: error: implicit declaration of function ksys_close [-Werror,-Wimplicit-function-declaration]
drivers/gpu/mediatek/gpu_mali/mali_valhall/mali-r25p0/drivers/gpu/arm/midgard/mali_kbase_sync.h:165:2: error: implicit declaration of function ksys_close [-Werror,-Wimplicit-function-declaration]
drivers/gpu/mediatek/gpu_mali/mali_valhall/mali-r25p0/drivers/gpu/arm/midgard/ipa/mali_kbase_ipa.c:609:3: error: field designator get_static_power does not refer to any field in type struct devfreq_cooling_power; did you mean get_real_power?
drivers/gpu/mediatek/gpu_mali/mali_valhall/mali-r25p0/drivers/gpu/arm/midgard/ipa/mali_kbase_ipa.c:609:22: error: incompatible function pointer types initializing int (*)(struct devfreq *, u32 *, unsigned long, unsigned long) (aka int (*)(struct devfreq *, unsigned int *, unsigned long, unsigned long)) with an expression of type unsigned long (*)(struct devfreq *, unsigned long) [-Werror,-Wincompatible-function-pointer-types]
drivers/gpu/mediatek/gpu_mali/mali_valhall/mali-r25p0/drivers/gpu/arm/midgard/ipa/mali_kbase_ipa.c:610:3: error: field designator get_dynamic_power does not refer to any field in type struct devfreq_cooling_power
drivers/gpu/mediatek/gpu_mali/mali_valhall/mali-r25p0/drivers/gpu/arm/midgard/mali_kbase_sync.h:165:2: error: implicit declaration of function ksys_close [-Werror,-Wimplicit-function-declaration]
drivers/gpu/mediatek/gpu_mali/mali_valhall/mali-r25p0/drivers/gpu/arm/midgard/mali_kbase_sync.h:165:2: error: implicit declaration of function ksys_close [-Werror,-Wimplicit-function-declaration]

MTK-Commit-Id: 36b149c2387f9422b2e26915fa45c50bfd964869

Signed-off-by: Miles Chen <miles.chen@mediatek.com>
CR-Id: ALPS06374686
Feature: Kernel SI Operation
Change-Id: I46013b934d8a2c05c27a2395fbb0f824ec6a2cd1