kernel/stacktrace.c: export stack_trace_save_tsk
export stack_trace_save_tsk
ERROR: modpost: "stack_trace_save_tsk" [drivers/misc/mediatek/monitor_hang/monitor_hang.ko] undefined!
ERROR: modpost: "stack_trace_save_tsk" [drivers/misc/mediatek/aee/mrdump/mrdump.ko] undefined!
ERROR: modpost: "stack_trace_save_tsk" [drivers/misc/mediatek/aee/aed/aee_aed.ko] undefined!

Change-Id: I9a92825cf50668e1f1b1104646b4ff8b8bfc2f4b
CR-Id: ALPS05431666
Feature: [Module]Kernel Maintenance
Signed-off-by: Miles Chen <miles.chen@mediatek.com>
(cherry picked from commit ae3d5167052c4073c74f8a805a1947d72e81b003)