rtc: mt6397: fix no member named dev in struct mt6397_rtc build breaks
Errors:
drivers/rtc/rtc-mt6397.c:178:15: error: no member named 'dev' in 'struct mt6397_rtc'
drivers/rtc/rtc-mt6397.c:204:15: error: no member named 'dev' in 'struct mt6397_rtc'
drivers/rtc/rtc-mt6397.c:474:48: error: no member named 'dev' in 'struct mt6397_rtc'
drivers/rtc/rtc-mt6397.c:478:17: error: no member named 'dev' in 'struct mt6397_rtc'
drivers/rtc/rtc-mt6397.c:486:16: error: no member named 'dev' in 'struct mt6397_rtc'
drivers/rtc/rtc-mt6397.c:503:7: error: no member named 'dev' in 'struct mt6397_rtc'

Change-Id: I8ec1ecb1fbadc5f3dc0bb913082c227b39fd2e5e
CR-Id: ALPS05431666
Feature: [Module]Kernel Maintenance
Signed-off-by: Miles Chen <miles.chen@mediatek.com>