mmstat: fix implicit conversion from enumeration build breaks
Errors:
drivers/misc/mediatek/mmstat/trace_mmstat.c:162:51: error: implicit conversion from enumeration type 'enum node_stat_item' to different enumeration type 'enum zone_stat_item' [-Werror,-Wenum-conversion]

Change-Id: I4b6aa9c281cf97149dae4de6806d8afa6eee67e5
CR-Id: ALPS05511922
Feature: [Module]Kernel Maintenance
Signed-off-by: Miles Chen <miles.chen@mediatek.com>