mtprof: remove the use of irq_to_desc
irq_to_desc is restrict exported by commit 64a1b95bb9fe3ec76e1a2cd803eff06389341ae4
("genirq: Restrict export of irq_to_desc()").

Error:
ERROR: modpost: "irq_to_desc" [drivers/misc/mediatek/mtprof/irq_monitor.ko] undefined!

Change-Id: I439d10bebe0c168a775ffded6be682f70d1a0f58
Signed-off-by: Miles Chen <miles.chen@mediatek.com>
Feature: [Module]Kernel Maintenance
CR-Id: ALPS05672993