[ALPS07767442] ACK: Fix build error
error: implicit declaration of function ufshcd_vops_setup_xfer_req

Removed by ACK patch "3586ade72bf40b04171c91897e6df22b91e25bb3"

MTK-Commit-Id: d67ace81acd114037aea35a973eb8f6b672cd835

Change-Id: Ia8fa7f167a75664b396353a1e36b7e7fc5cc5292
CR-Id: ALPS07767442
Feature: Kernel SI Operation
Signed-off-by: Bo Ye <bo.ye@mediatek.com>