mnoc: fix unused function build breaks
Errors:
drivers/misc/mediatek/apusys/mnoc/1.5/common/mnoc_qos.c:132:12: error: unused function 'add_qos_request' [-Werror,-Wunused-function]
drivers/misc/mediatek/apusys/mnoc/1.5/common/mnoc_qos.c:138:13: error: unused function 'update_qos_request' [-Werror,-Wunused-function]
drivers/misc/mediatek/apusys/mnoc/1.5/common/mnoc_qos.c:144:12: error: unused function 'destroy_qos_request' [-Werror,-Wunused-function]

Change-Id: If2a994cdaa2e8f84582f9911c0f63ba2112a68cb
CR-Id: ALPS05511922
Feature: [Module]Kernel Maintenance
Signed-off-by: Miles Chen <miles.chen@mediatek.com>
(cherry picked from commit 9f0154a9226849423245d29326e15ae335035f9a)