[ALPS04783226] cpudvfs: fix build breaks when CONFIG_KASAN=y
Fix the following build breaks when CONFIG_KASAN=y with CC=gcc

drivers/misc/mediatek/mcupm/mt6885/mcupm_driver.h:54:36: error:
‘mcupm_reserve_mblock’ defined but not used
[-Werror=unused-variable]

MTK-Commit-Id: fe74d227ba4cc5b3fe0845d8a8e6d9518735d78a

Change-Id: Id8843384aebbe6d3adedc40ace25e3e8aab060f8
CR-Id: ALPS04783226
Signed-off-by: Miles Chen <miles.chen@mediatek.com>
Feature: DVFS (Dynamic Voltage and Frequency Scaling)