FDVT: fix timeval build breaks
Error:
drivers/misc/mediatek/cameraisp/fdvt/5.1/camera_fdvt.c:2684:17: error: variable has incomplete type 'struct timeval'

Feature: [Module]Kernel Maintenance
Change-Id: Ic19c745aac98fc02770d180a51678b60f97045ed
CR-Id: ALPS05559435
Signed-off-by: Miles Chen <miles.chen@mediatek.com>