VOW: fix warn_unused_result build breaks
Errors:
drivers/misc/mediatek/vow/ver02/vow.c:2984:3: error: ignoring return value of function declared with 'warn_unused_result' attribute [-Werror,-Wunused-result]
drivers/misc/mediatek/vow/ver02/vow.c:2994:3: error: ignoring return value of function declared with 'warn_unused_result' attribute [-Werror,-Wunused-result]
drivers/misc/mediatek/vow/ver02/vow.c:3003:4: error: ignoring return value of function declared with 'warn_unused_result' attribute [-Werror,-Wunused-result]
drivers/misc/mediatek/vow/ver02/vow.c:3012:4: error: ignoring return value of function declared with 'warn_unused_result' attribute [-Werror,-Wunused-result]
drivers/misc/mediatek/vow/ver02/vow.c:3016:3: error: ignoring return value of function declared with 'warn_unused_result' attribute [-Werror,-Wunused-result]

Change-Id: I4fe3a609a3a97e1224a1b4472cb302dd74a55769
CR-Id: ALPS05584628
Feature: [Module]Kernel Maintenance
Signed-off-by: Miles Chen <miles.chen@mediatek.com>