iommu/mediatek: fix unused variable build breaks
Errors:
drivers/iommu/mtk_iommu.c:577:27: error: unused variable 'dom' [-Werror,-Wunused-variable]

(cherry-picked from commit 478dc739423d02956624446fcdea619eeb0dc8ae)
Change-Id: Ic41085d77f73c542ee8f6fd0cd01fdf85efda6a2
CR-Id: ALPS05511922
Feature: [Module]Kernel Maintenance
Signed-off-by: Miles Chen <miles.chen@mediatek.com>