cpufreq: mediatek-hw: fix undefined CPUFREQ_STICKY build breaks
Errors:
drivers/cpufreq/mediatek-cpufreq-hw.c:207:12: error: use of undeclared identifier 'CPUFREQ_STICKY'

Change-Id: I0297c66f174ae23b8f4d44a0e3c125776a8ed096
Signed-off-by: Miles Chen <miles.chen@mediatek.com>
Feature: [Module]Kernel Maintenance
CR-Id: ALPS05625693