VOW: fix get_fs build breaks
https://lwn.net/Articles/832121/

Errors:
drivers/misc/mediatek/vow/ver02/vow.c:1837:15: error: implicit declaration of function 'get_fs' [-Werror,-Wimplicit-function-declaration]
drivers/misc/mediatek/vow/ver02/vow.c:1837:13: error: assigning to 'mm_segment_t' from incompatible type 'int'
drivers/misc/mediatek/vow/ver02/vow.c:1838:6: error: implicit declaration of function 'set_fs' [-Werror,-Wimplicit-function-declaration]
drivers/misc/mediatek/vow/ver02/vow.c:1838:13: error: use of undeclared identifier 'KERNEL_DS'; did you mean 'KERNFS_NS'?
drivers/misc/mediatek/vow/ver02/vow.c:1895:15: error: implicit declaration of function 'get_fs' [-Werror,-Wimplicit-function-declaration]
drivers/misc/mediatek/vow/ver02/vow.c:1895:13: error: assigning to 'mm_segment_t' from incompatible type 'int'
drivers/misc/mediatek/vow/ver02/vow.c:1896:6: error: implicit declaration of function 'set_fs' [-Werror,-Wimplicit-function-declaration]
drivers/misc/mediatek/vow/ver02/vow.c:1896:13: error: use of undeclared identifier 'KERNEL_DS'; did you mean 'KERNFS_NS'?
drivers/misc/mediatek/vow/ver02/vow.c:1916:14: error: implicit declaration of function 'get_fs' [-Werror,-Wimplicit-function-declaration]
drivers/misc/mediatek/vow/ver02/vow.c:1916:12: error: assigning to 'mm_segment_t' from incompatible type 'int'
drivers/misc/mediatek/vow/ver02/vow.c:1917:5: error: implicit declaration of function 'set_fs' [-Werror,-Wimplicit-function-declaration]
drivers/misc/mediatek/vow/ver02/vow.c:1917:12: error: use of undeclared identifier 'KERNEL_DS'; did you mean 'KERNFS_NS'?
drivers/misc/mediatek/vow/ver02/vow.c:1959:15: error: implicit declaration of function 'get_fs' [-Werror,-Wimplicit-function-declaration]
drivers/misc/mediatek/vow/ver02/vow.c:1959:13: error: assigning to 'mm_segment_t' from incompatible type 'int'
drivers/misc/mediatek/vow/ver02/vow.c:1960:6: error: implicit declaration of function 'set_fs' [-Werror,-Wimplicit-function-declaration]
drivers/misc/mediatek/vow/ver02/vow.c:1960:13: error: use of undeclared identifier 'KERNEL_DS'; did you mean 'KERNFS_NS'?
drivers/misc/mediatek/vow/ver02/vow.c:2016:15: error: implicit declaration of function 'get_fs' [-Werror,-Wimplicit-function-declaration]
drivers/misc/mediatek/vow/ver02/vow.c:2016:13: error: assigning to 'mm_segment_t' from incompatible type 'int'
drivers/misc/mediatek/vow/ver02/vow.c:2017:6: error: implicit declaration of function 'set_fs' [-Werror,-Wimplicit-function-declaration]

Change-Id: Ic03e81b89f5776bb4ce29c6c567cce772272588f
Signed-off-by: Miles Chen <miles.chen@mediatek.com>
CR-Id: ALPS05568046
Feature: [Module]Kernel Maintenance