ASoC: fix no membler named cpu_dai build breaks
Errors:
sound/soc/mediatek/mt6853/mt6853-afe-pcm.c:54:23: error: no member named 'cpu_dai' in 'struct snd_soc_pcm_runtime'
sound/soc/mediatek/mt6853/mt6853-afe-pcm.c:94:23: error: no member named 'cpu_dai' in 'struct snd_soc_pcm_runtime'
sound/soc/mediatek/mt6853/mt6853-afe-pcm.c:116:16: error: no member named 'cpu_dai' in 'struct snd_soc_pcm_runtime'
sound/soc/mediatek/mt6853/mt6853-afe-pcm.c:212:16: error: no member named 'cpu_dai' in 'struct snd_soc_pcm_runtime'
sound/soc/mediatek/mt6853/mt6853-afe-pcm.c:3066:10: error: use of undeclared identifier 'mtk_afe_pcm_ops'
sound/soc/mediatek/mt6853/mt6853-afe-pcm.c:3068:14: error: use of undeclared identifier 'mtk_afe_pcm_free'; did you mean 'mtk_afe_pcm_new'?
sound/soc/mediatek/mt6853/mt6853-mt6359p.c:134:37: error: no member named 'cpu_dai' in 'struct snd_soc_pcm_runtime'

Change-Id: I0eb9d7ecf23cefb6dd34ce46ab498f3dcfca8c28
CR-Id: ALPS05489813
Feature: [Module]Kernel Maintenance
Signed-off-by: Miles Chen <miles.chen@mediatek.com>