sound: mt6939p: fix conflict type build breaks
Error:
sound/soc/codecs/mt6359.c:212:6: error: conflicting types for 'mt6359_set_mtkaif_protocol'

Change-Id: I272adc7e64fd8ce62ee8bc4637d093b16cb5e250
Signed-off-by: Miles Chen <miles.chen@mediatek.com>
CR-Id: ALPS05568046
Feature: [Module]Kernel Maintenance