blocktag: fix expected expression build breaks
Errors:
drivers/misc/mediatek/memblock/mtk-memblock.c:49:39: error: expected expression
drivers/misc/mediatek/memblock/mtk-memblock.c:95:31: error: expected expression

Change-Id: Ib68d5c6eaf6e7073d22b2d5d30c97f56bac3bd83
CR-Id: ALPS05431666
Feature: [Module]Kernel Maintenance
Signed-off-by: Miles Chen <miles.chen@mediatek.com>