interconnect: mediatek: mmqos: fix build error for GKI project
1. Change config type of INTERCONNECT_MTK_MMQOS_COMMON from bool
   to tristate
2. Fix wrong parameter of MODULE_DEVICE_TABLE
3. Remove of_phandle_iterator_args because it is not exported and
   it is not necessary
4. Export mtk_mmqos_probe() and mtk_mmqos_remove()

Error message:
drivers/interconnect/mediatek/mmqos-mt6779.c:373:25: error: use of
   undeclared identifier 'mtk_mt6779_mmqos_of_ids'
MODULE_DEVICE_TABLE(of, mtk_mt6779_mmqos_of_ids);

drivers/interconnect/mediatek/mmqos-mtk.o: In function `mtk_mmqos_probe':
   drivers/interconnect/mediatek/mmqos-mtk.c:384: undefined reference to
`register_mmdvfs_notifier'

ERROR: "of_phandle_iterator_args"
   [drivers/interconnect/mediatek/mmqos-mtk.ko] undefined!
ERROR: "mtk_mmqos_remove"
   [drivers/interconnect/mediatek/mmqos-mt6779.ko] undefined!
ERROR: "mtk_mmqos_probe"
   [drivers/interconnect/mediatek/mmqos-mt6779.ko] undefined!

Change-Id: Id374aa1db1572e256dbaef917e3f53f43906e643
Feature: [Module]MM pipeline/MM DVFS
CR-Id: ALPS04754217
Signed-off-by: Anthony Huang <anthony.huang@mediatek.com>