memory: mtk-smi: fix mixing declarations and code build breaks
Errors:
drivers/memory/mtk-smi.c:214:6: error: ISO C90 forbids mixing declarations and code [-Werror,-Wdeclaration-after-statement]

(cherry-picked from commit 9a200fbaa16b725a480c72d8697f4807eedf31e2)
Change-Id: Ic5088c869fc471488687fbf084d5af6f7488d1dc
CR-Id: ALPS05511922
Feature: [Module]Kernel Maintenance
Signed-off-by: Miles Chen <miles.chen@mediatek.com>