rpmsg: fix MTK_CCD_ALLOC_ADDITIONAL_BUF not defined build breaks
Errors:
drivers/rpmsg/mtk_ccd_rpmsg_ipi.c:61:5: error: 'MTK_CCD_ALLOC_ADDITIONAL_BUF' is not defined, evaluates to 0 [-Werror,-Wundef]

(cherry-picked from commit e06e26ccf8217840a02872d5e03f4769350cb578)
Change-Id: I2f4fd8e6c1ae6ab380ae878161f48b1318fb382c
CR-Id: ALPS05511922
Feature: [Module]Kernel Maintenance
Signed-off-by: Miles Chen <miles.chen@mediatek.com>