scsi: ufs: resolve linkage errors when SCSI_UFSHCD is built as a module
In case CONFIG_SCSI_UFSHCD is defined as a module, we should export
ufshcd_hold() and ufshcd_release() in order to avoid the following
errors:
ERROR: "ufshcd_hold" [drivers/scsi/ufs/ufs-qcom.ko] undefined!
ERROR: "ufshcd_release" [drivers/scsi/ufs/ufs-qcom.ko] undefined!

Change-Id: I728172605deadd118a3a05af9bc7beeacd61cf55
Signed-off-by: Yaniv Gardi <ygardi@codeaurora.org>