leakage_table: fix proc_create build breaks
Errors:
drivers/misc/mediatek/leakage_table/mtk_static_power.c:476:36: error: incompatible pointer types passing 'const struct file_operations *const' to parameter of type 'const struct proc_ops *' [-Werror,-Wincompatible-pointer-types]

Change-Id: I9c68a248b3ae8260b3d10cfa1cb2a994e5e58d4c
CR-Id: ALPS05502217
Feature: [Module]Kernel Maintenance
Signed-off-by: Miles Chen <miles.chen@mediatek.com>
(cherry picked from commit 33f2a789e014012209de33d5c0c528f3eb6a5c6e)