clk: mediatek: fix tautological-overlap-compare build breaks
Errors:
drivers/clk/mediatek/clk-fhctl-debug.c:115:28: error: overlapping comparisons always evaluate to false [-Werror,-Wtautological-overlap-compare]

Change-Id: I495a9330a94f19edd6965004bb01000bd79c17b9
CR-Id: ALPS05511922
Feature: [Module]Kernel Maintenance
Signed-off-by: Miles Chen <miles.chen@mediatek.com>
(cherry picked from commit e07e7f6ab08d3718ba117e46e84e6691176a7630)