[ALPS04783226] apusys: fix build breaks when CONFIG_KASAN=y
Fix build breaks when CONFIG_KASAN=y with CC=gcc

drivers/misc/mediatek/apusys/midware/1.0/scheduler.c:421:23:
error: format ‘%x’ expects argument of type ‘unsigned int’,
but argument 6 has typ
e ‘uint64_t {aka long long unsigned int}’ [-Werror=format=]
drivers/misc/mediatek/apusys/midware/1.0/scheduler.c:511:20:
error: format ‘%x’ expects argument of type ‘unsigned int’,
but argument 6 has typ
e ‘uint64_t {aka long long unsigned int}’ [-Werror=format=]

MTK-Commit-Id: 1e50bb52ff213c46ad92fb9af6d05155fd8a0b5a

Change-Id: I032a07ccae4d3a1728f8f79976c975c027cefa18
CR-Id: ALPS04783226
Signed-off-by: Miles Chen <miles.chen@mediatek.com>
Feature:[Module] APUSYS