aee: fix runnable_load_avg not exists build breaks
Errors:
drivers/misc/mediatek/aee/mrdump/mrdump_helper.c:1228:12: error: no member named 'runnable_load_avg' in 'struct sched_avg'; did you mean 'runnable_avg'?
drivers/misc/mediatek/aee/mrdump/mrdump_helper.c:1290:69: error: no member named 'runnable_weight' in 'struct cfs_rq'
drivers/misc/mediatek/aee/mrdump/mrdump_helper.c:1295:16: error: no member named 'runnable_load_avg' in 'struct sched_avg'; did you mean 'runnable_avg'?
drivers/misc/mediatek/aee/mrdump/mrdump_helper.c:1305:20: error: no member named 'runnable_sum' in 'struct cfs_rq::(anonymous at /mfs/mtkslt0480/mtk04267/CAS_REAL/alps-dev-r0.bsp-common-kernel-5.4--2021_02_25_21_00-6873/merged/kernel-mainline/arch/arm64/include/uapi/../../../../kernel/sched/sched.h:552:2)'; did you mean 'runnable_avg'?
drivers/misc/mediatek/aee/mrdump/mrdump_helper.c:1475:4: error: no member named 'nr_load_updates' in 'struct rq'; did you mean 'calc_load_update'?
drivers/misc/mediatek/aee/mrdump/mrdump_helper.c:1475:4: error: no member named 'nr_load_updates' in 'struct rq'; did you mean 'calc_load_update'?
drivers/misc/mediatek/aee/mrdump/mrdump_helper.c:1475:4: error: no member named 'nr_load_updates' in 'struct rq'; did you mean 'calc_load_update'?

Feature: [Module]Kernel Maintenance
Change-Id: Icf0819607e29c254f69f26c5e60e896f3bda2aed
CR-Id: ALPS05588815
Signed-off-by: Miles Chen <miles.chen@mediatek.com>