[ALPS04783226] apusys: fix build break when CONFIG_KASAN=y
Fix a build break by removing the unused statement

drivers/misc/mediatek/apusys/power/2.0/apusys_power_ctl.c:126:49:
error: statement with no effect [-Werror=unused-value]

MTK-Commit-Id: 3db34b3d7319d3b8c08ddf2c3a0ef02dfa82eb9d

Change-Id: I30f46318d0d6a6108b9300205fc6804a4cd1967c
Signed-off-by: Miles Chen <miles.chen@mediatek.com>
Feature: [Module] APUSYS
CR-Id: ALPS04783226