clk: mediatek: mux: drop unused clock ops build breaks
Errors:
drivers/clk/mediatek/clk-mt8192.c:837:2: error: too many arguments provided to function-like macro invocation
drivers/clk/mediatek/clk-mt8192.c:837:2: error: use of undeclared identifier 'GATE_CLR_SET_UPD_FLAGS'
drivers/clk/mediatek/clk-mt8192.c:841:2: error: too many arguments provided to function-like macro invocation
drivers/clk/mediatek/clk-mt8192.c:841:2: error: use of undeclared identifier 'GATE_CLR_SET_UPD_FLAGS'
drivers/clk/mediatek/clk-mt8192.c:845:2: error: too many arguments provided to function-like macro invocation
drivers/clk/mediatek/clk-mt8192.c:845:2: error: use of undeclared identifier 'GATE_CLR_SET_UPD_FLAGS'
drivers/clk/mediatek/clk-mt8192.c:854:2: error: too many arguments provided to function-like macro invocation
drivers/clk/mediatek/clk-mt8192.c:854:2: error: use of undeclared identifier 'GATE_CLR_SET_UPD_FLAGS'
drivers/clk/mediatek/clk-mt8192.c:1352:40: error: invalid application of 'sizeof' to an incomplete type 'const struct mtk_mux []'

Change-Id: I4098604f4e3955c0cad5e008d1dee5617ac1d0b5
Signed-off-by: Miles Chen <miles.chen@mediatek.com>
Feature: [Module]Kernel Maintenance
CR-Id: ALPS05625693