aee: fix pr_ppid build breaks
Errors:
drivers/misc/mediatek/aee/mrdump/mrdump_mini.c:365:12: error: no member named 'pr_ppid' in 'struct elf_prstatus'
drivers/misc/mediatek/aee/mrdump/mrdump_mini.c:366:12: error: no member named 'pr_sigpend' in 'struct elf_prstatus'

Change-Id: I18bf2f41eae9836db65ee3acdb54c3248404b911
Signed-off-by: Miles Chen <miles.chen@mediatek.com>
Feature: [Module]Kernel Maintenance
CR-Id: ALPS05625693