pidmap: fix proc_create() build breaks
Errors:
drivers/misc/mediatek/pidmap/pidmap.c:324:3: error: incompatible pointer types passing 'const struct file_operations *' to parameter of type 'const struct proc_ops *' [-Werror,-Wincompatible-pointer-types]

Change-Id: Ic9bf389f9373f1d796850d6494f20e8c447e2b04
CR-Id: ALPS05387457
Feature: [Module]Kernel Maintenance
Signed-off-by: Miles Chen <miles.chen@mediatek.com>