[ALPS05653694] scsi: ufs-mediatek: fix compl_xfer_req build breaks
Fix build breaks after the revert of "FROMLIST: ufs: introduce
a callback to get info of command completion"

Errors:
drivers/scsi/ufs/ufs-mediatek.c:1104:3: error: field designator
compl_xfer_req does not refer to any field in type
const struct ufs_hba_variant_ops

MTK-Commit-Id: 5fe1eb810e9b1f4a9911c8c918dfafb2ce7dfa38

Change-Id: Iba3543a9b5edcd80984604476c7f2e506addba0d
Signed-off-by: Miles Chen <miles.chen@mediatek.com>
Feature: [Module]Kernel Maintenance
CR-Id: ALPS05653694