flashlight: fix v4l2_async_notifier_add_subdev build breaks
Errors:
drivers/misc/mediatek/flashlight/mtk-composite.c:146:19: error: expected expression

Change-Id: If54a55ee674230e5ce234873bf816c3d598a0ceb
Signed-off-by: Miles Chen <miles.chen@mediatek.com>
Feature: [Module]Kernel Maintenance
CR-Id: ALPS05625693