gpu: fix no member named max_freq in devfreq build breaks
Error:
/mfs/mtkslt0480/mtk04267/CAS_REAL/alps-dev-r0_bsp-common-kernel-5_4--2020_09_09_02_00/merged/kernel-5.4/drivers/gpu/mediatek/gpu_mali/mali_valhall/mali-r25p0/drivers/gpu/arm/midgard/backend/gpu/mali_kbase_devfreq.c:67:11: error: no member named 'max_freq' in 'struct devfreq'
/mfs/mtkslt0480/mtk04267/CAS_REAL/alps-dev-r0_bsp-common-kernel-5_4--2020_09_09_02_00/merged/kernel-5.4/drivers/gpu/mediatek/gpu_mali/mali_valhall/mali-r25p0/drivers/gpu/arm/midgard/backend/gpu/mali_kbase_devfreq.c:70:15: error: no member named 'max_freq' in 'struct devfreq'
/mfs/mtkslt0480/mtk04267/CAS_REAL/alps-dev-r0_bsp-common-kernel-5_4--2020_09_09_02_00/merged/kernel-5.4/drivers/gpu/mediatek/gpu_mali/mali_valhall/mali-r25p0/drivers/gpu/arm/midgard/backend/gpu/mali_kbase_devfreq.c:90:7: error: use of undeclared identifier 'DEVFREQ_GOV_INTERVAL'
/mfs/mtkslt0480/mtk04267/CAS_REAL/alps-dev-r0_bsp-common-kernel-5_4--2020_09_09_02_00/merged/kernel-5.4/drivers/gpu/mediatek/gpu_mali/mali_valhall/mali-r25p0/drivers/gpu/arm/midgard/backend/gpu/mali_kbase_devfreq.c:91:3: error: implicit declaration of function 'devfreq_interval_update' [-Werror,-Wimplicit-function-declaration]

Feature: [Module]Kernel Maintenance
Change-Id: I21c13d2f996cc3ca43e43d1e69223a229cd34836
CR-Id: ALPS05298037
Signed-off-by: Miles Chen <miles.chen@mediatek.com>