binder: fix redefinition build breaks
Errors:
drivers/android/binder.c:164:6: error: redefinition of 'binder_stat_types'
drivers/android/binder.c:165:2: error: redefinition of enumerator 'BINDER_STAT_PROC'
drivers/android/binder.c:166:2: error: redefinition of enumerator 'BINDER_STAT_THREAD'
drivers/android/binder.c:167:2: error: redefinition of enumerator 'BINDER_STAT_NODE'
drivers/android/binder.c:168:2: error: redefinition of enumerator 'BINDER_STAT_REF'
drivers/android/binder.c:169:2: error: redefinition of enumerator 'BINDER_STAT_DEATH'
drivers/android/binder.c:170:2: error: redefinition of enumerator 'BINDER_STAT_TRANSACTION'
drivers/android/binder.c:171:2: error: redefinition of enumerator 'BINDER_STAT_TRANSACTION_COMPLETE'
drivers/android/binder.c:172:2: error: redefinition of enumerator 'BINDER_STAT_COUNT'
drivers/android/binder.c:175:8: error: redefinition of 'binder_stats'
drivers/android/binder.c:224:8: error: redefinition of 'binder_work'
drivers/android/binder.c:228:3: error: redefinition of enumerator 'BINDER_WORK_TRANSACTION'
drivers/android/binder.c:229:3: error: redefinition of enumerator 'BINDER_WORK_TRANSACTION_COMPLETE'
drivers/android/binder.c:230:3: error: redefinition of enumerator 'BINDER_WORK_RETURN_ERROR'
drivers/android/binder.c:231:3: error: redefinition of enumerator 'BINDER_WORK_NODE'
drivers/android/binder.c:232:3: error: redefinition of enumerator 'BINDER_WORK_DEAD_BINDER'
drivers/android/binder.c:233:3: error: redefinition of enumerator 'BINDER_WORK_DEAD_BINDER_AND_CLEAR'
drivers/android/binder.c:234:3: error: redefinition of enumerator 'BINDER_WORK_CLEAR_DEATH_NOTIFICATION'
drivers/android/binder.c:238:8: error: redefinition of 'binder_error'

Change-Id: I96672c593a1b08c1d6d36141243aa31ae3dd5813
CR-Id: ALPS05431666
Feature: [Module]Kernel Maintenance
Signed-off-by: Miles Chen <miles.chen@mediatek.com>