rtc: mt6397: fix rtc_register_device build breaks
Errors:
drivers/rtc/rtc-mt6397.c:484:8: error: implicit declaration of function 'rtc_nvmem_register' [-Werror,-Wimplicit-function-declaration]

Change-Id: Ifaf79b02b58d7b8377d6884df541f186d2d2950a
Signed-off-by: Miles Chen <miles.chen@mediatek.com>
CR-Id: ALPS05568046
Feature: [Module]Kernel Maintenance