rpmsg: fix allmodconfig build breaks
fix rpmsg related allmodconfig build errors

build command:
ARCH=arm64 make mrproper allmodconfig all

Errors:
drivers/rpmsg/mtk_ccd_rpmsg.c:29:2: error: implicit declaration of function 'kfree' [-Werror,-Wimplicit-function-declaration]
drivers/rpmsg/mtk_ccd_rpmsg.c:54:9: error: implicit declaration of function 'kzalloc' [-Werror,-Wimplicit-function-declaration]
drivers/rpmsg/mtk_ccd_rpmsg.c:183:2: error: implicit declaration of function 'kfree' [-Werror,-Wimplicit-function-declaration]
drivers/rpmsg/mtk_ccd_rpmsg.c:282:9: error: implicit declaration of function 'kzalloc' [-Werror,-Wimplicit-function-declaration]
drivers/rpmsg/mtk_ccd_rpmsg.c:324:3: error: implicit declaration of function 'kfree' [-Werror,-Wimplicit-function-declaration]
drivers/rpmsg/mtk_ccd_rpmsg.c:331:2: error: implicit declaration of function 'kfree' [-Werror,-Wimplicit-function-declaration]
drivers/rpmsg/mtk_ccd_rpmsg.c:422:15: error: implicit declaration of function 'kzalloc' [-Werror,-Wimplicit-function-declaration]
drivers/rpmsg/mtk_ccd_rpmsg.c:454:2: error: implicit declaration of function 'kfree' [-Werror,-Wimplicit-function-declaration]
drivers/rpmsg/mtk_ccd_rpmsg_ipi.c:167:3: error: implicit declaration of function 'kfree' [-Werror,-Wimplicit-function-declaration]
drivers/rpmsg/mtk_ccd_rpmsg_ipi.c:282:3: error: implicit declaration of function 'kfree' [-Werror,-Wimplicit-function-declaration]

Change-Id: Iea048041c712a90e5b0fdcf80cd7e81cc0c0db5a
Cc: Ryan Yu <ryan.yu@mediatek.com>
Signed-off-by: Miles Chen <miles.chen@mediatek.com>
Feature: Kernel SI Operation
CR-Id: ALPS05903624