usb: typec: fix typec_capability build breaks
Error:
drivers/misc/mediatek/typec/tcpc/tcpci_dual_role.c:162:19: error: no member named 'dr_set' in 'struct typec_capability'
drivers/misc/mediatek/typec/tcpc/tcpci_dual_role.c:163:19: error: no member named 'pr_set' in 'struct typec_capability'
drivers/misc/mediatek/typec/tcpc/tcpci_dual_role.c:164:19: error: no member named 'vconn_set' in 'struct typec_capability'
drivers/misc/mediatek/typec/tcpc/tcpci_dual_role.c:165:19: error: no member named 'try_role' in 'struct typec_capability'
drivers/misc/mediatek/typec/tcpc/tcpci_dual_role.c:166:19: error: no member named 'port_type_set' in 'struct typec_capability'

Signed-off-by: Miles Chen <miles.chen@mediatek.com>
Change-Id: I3a684f88e91a2cdf076e2e480b44409b5eec2aa2
CR-Id: ALPS05298037
Feature: [Module]Kernel Maintenance
Signed-off-by: Miles Chen <miles.chen@mediatek.com>
Source_Git_Sha: 8fa79e8bae2ffaf0ddf4078bc07c13c3594de4e7