usb: mtu3: fix usb_role_switch build breaks
Error:
drivers/usb/mtu3/mtu3_dr.c:336:11: error: use of undeclared identifier 'dev'
drivers/usb/mtu3/mtu3_dr.c:341:12: error: use of undeclared identifier 'dev'
drivers/usb/mtu3/mtu3_dr.c:444:21: error: incompatible pointer types passing 'struct device *' to parameter of type 'struct usb_role_switch *' [-Werror,-Wincompatible-pointer-types]

Signed-off-by: Miles Chen <miles.chen@mediatek.com>
Change-Id: I1be882357da66efa740fc9c24f400b33329fbdc7
CR-Id: ALPS05298037
Feature: [Module]Kernel Maintenance
Signed-off-by: Miles Chen <miles.chen@mediatek.com>