regulator: mt6360: fix regulator_linear_range build breaks
Errors:
drivers/regulator/mt6360-regulator.c:404:60: error: array has incomplete element type 'const struct regulator_linear_range'
drivers/regulator/mt6360-regulator.c:553:19: error: invalid application of 'sizeof' to an incomplete type 'const struct mt6360_regulator_desc []'

Change-Id: I63d2e8af0be012ff96ac285fdb6c62f2d7db52d8
CR-Id: ALPS05483491
Feature: [Module]Kernel Maintenance
Signed-off-by: Miles Chen <miles.chen@mediatek.com>
(cherry picked from commit ef5fac6d72108880697e41180c69afd57f2cea37)