log_store: fix get_fs build breaks
Errors:
drivers/misc/mediatek/log_store/log_store.c:111:7: error: implicit declaration of function 'get_fs' [-Werror,-Wimplicit-function-declaration]

Change-Id: Id805a3f8f7d646b2eacf2924cf48291b77a99aa8
Signed-off-by: Miles Chen <miles.chen@mediatek.com>
CR-Id: ALPS05568046
Feature: [Module]Kernel Maintenance