clk: mediatek: FHCTL: fix allmodconfig build breaks
fix FHCTL related allmodconfig build breaks

build command:
ARCH=arm64 make mrproper allmodconfig all

Errors:
drivers/clk/mediatek/clk-fhctl-sspm.c:8:10: fatal error: 'sspm_ipi.h' file not found

Change-Id: I151afae0872d9f0717c02577b7fe04749dd92e79
Cc: MugaChi <muga.chi@mediatek.com>
Signed-off-by: Miles Chen <miles.chen@mediatek.com>
Feature: Kernel SI Operation
CR-Id: ALPS05903624