cpufreq: mediatek-hw: fix pm_qos build breaks
Error:
drivers/cpufreq/mediatek-cpufreq-hw.c:151:2: error: implicit declaration of function 'pm_qos_add_request' [-Werror,-Wimplicit-function-declaration]
drivers/cpufreq/mediatek-cpufreq-hw.c:151:34: error: use of undeclared identifier 'PM_QOS_CPU_DMA_LATENCY'
drivers/cpufreq/mediatek-cpufreq-hw.c:169:2: error: implicit declaration of function 'pm_qos_remove_request' [-Werror,-Wimplicit-function-declaration]

Feature: [Module]Kernel Maintenance
Change-Id: I8c310decf060fa07372b1dd1e89a7c038df4bcf1
CR-Id: ALPS05363693
Signed-off-by: Miles Chen <miles.chen@mediatek.com>
(cherry picked from commit b43c0fc2ad29ca46ae6e35381f987f02fa3f3d5d)