[ALPS04250113] m4u: fix uninitialized build error
Fix uninitialized build error by initialize the variable:

../drivers/misc/mediatek/m4u/mt6771/m4u_hw.c:1644:24: note:
cnt.main_tlb_miss_cnt was declared here struct M4U_PERF_COUNT cnt;
^
In file included from ../include/linux/printk.h:467:0,
   from ../include/linux/kernel.h:14,
   from ../include/asm-generic/bug.h:16,
   from ../arch/arm/include/asm/bug.h:60,
   from ../include/linux/bug.h:5,
   from ../include/linux/mmdebug.h:5,
   from ../include/linux/gfp.h:5,
   from ../include/linux/slab.h:15,
   from ../drivers/misc/mediatek/m4u/mt6771/m4u_hw.c:14:
   ../include/linux/dynamic_debug.h:127:3: error: cnt.transaction_cnt
   may be used uninitialized in this function
   [-Werror=maybe-uninitialized]
   __dynamic_pr_debug(&descriptor, pr_fmt(fmt),
		   ^

MTK-Commit-Id: 7b4cfd19357dfcbf3bbac25c9313b5581bead9e2

Change-Id: Idd39af9aa838c9944ecf5db09f8e564087ffecb0
Signed-off-by: Miles Chen <miles.chen@mediatek.com>
CR-Id: ALPS04250113
Feature: [Module]Kernel Memory Management
(cherry-pick from 697b7a1140f8c22315667c530b84a0470756e108)