cmdq: fix drmP.h file build break
Errors:
drivers/gpu/drm/mediatek/mediatek_v2/mtk_drm_ddp.c:12:10: fatal error: 'drm/drmP.h' file not found
drivers/gpu/drm/mediatek/mediatek_v2/mtk_drm_ddp_comp.c:13:10: fatal error: 'drm/drmP.h' file not found
drivers/gpu/drm/mediatek/mediatek_v2/mtk_disp_recovery.c:20:10: fatal error: 'drm/drmP.h' file not found

Change-Id: If249d021860934ef19b979f98be0ff6a42d45447
CR-Id: ALPS05506766
Feature: [Module]Kernel Maintenance
Signed-off-by: Kuan-Ying Lee <Kuan-Ying.Lee@mediatek.com>
(cherry picked from commit 5cb46c95b5948dac757f30259baef6d962bd28d8)