clkbuf: fix srclken_dev_pm_resume() build break
Error:
drivers/misc/mediatek/srclken_rc/src/mtk-srclken-rc.c:121:1: error: non-void function does not return a value [-Werror,-Wreturn-type]

Change-Id: Ia804c339565d746bbfb5c66bafabd67cdfdee824
CR-Id: ALPS05438846
Feature: [Module]Kernel Maintenance
Signed-off-by: Kuan-Ying Lee <Kuan-Ying.Lee@mediatek.com>
(cherry picked from commit 2a7dd066fad964841577361085184d368575e4cf)