vow: fix extra tokens build breaks
Errors:
drivers/misc/mediatek/vow/ver02/vow.h:68:18: error: extra tokens at end of #ifdef directive [-Werror,-Wextra-tokens]
drivers/misc/mediatek/vow/ver02/vow.h:68:18: error: extra tokens at end of #ifdef directive [-Werror,-Wextra-tokens]

(cherry-picked from commit 81f360e0e6b3338ca5146783031ac2153684eba9)
Change-Id: I82cdb2252480d4e696a4da281439899208fc5cae
CR-Id: ALPS05511922
Feature: [Module]Kernel Maintenance
Signed-off-by: Miles Chen <miles.chen@mediatek.com>
(cherry picked from commit fed8a9c4c5e8d5555d90ecbf8b1f0b2e90c97bb0)