usb: mtu3: workaround unused function build breaks
workaorund this because we're modifying mtu3_core.c but not
upstream the patch yet.

Errors:
drivers/usb/mtu3/mtu3_core.c:248:13: error: unused function 'mtu3_csr_init' [-Werror,-Wunused-function]

Change-Id: I73b80940dfb584f48c5530b116f75f08a5ccf71e
CR-Id: ALPS05511922
Feature: [Module]Kernel Maintenance
Signed-off-by: Miles Chen <miles.chen@mediatek.com>
(cherry picked from commit fc5ba222225a3af3fb213973a2d06546796bf617)