thermal: fix timeval build breaks
Error:
drivers/thermal/mediatek/thermal_trace.c:115:17: error: variable has incomplete type 'struct timeval'

Signed-off-by: Miles Chen <miles.chen@mediatek.com>
Change-Id: I7b97f26479d1491a463c8da81f7352ccc38da079
CR-Id: ALPS05298037
Feature: [Module]Kernel Maintenance
Signed-off-by: Miles Chen <miles.chen@mediatek.com>
Source_Git_Sha: 48f4f0e1dfeedca2253f8463c37997de3d5460c7