scp: fix tautological-overlap-compare build breaks
Errors:
drivers/misc/mediatek/scp/rv33/scp_dvfs.c:837:5: error: overlapping comparisons always evaluate to false [-Werror,-Wtautological-overlap-compare]

Change-Id: I8a5a051a78521269aa80cc27aa9b308533b9203e
CR-Id: ALPS05511922
Feature: [Module]Kernel Maintenance
Signed-off-by: Miles Chen <miles.chen@mediatek.com>