scp: fix int-in-bool-context build breaks
Errors:
drivers/misc/mediatek/scp/rv55/scp_wrapper_ipi.c:307:24: error: converting the result of '<<' to a boolean; did you mean '(1 << scp_mbox_pin_recv[i].pin_index) != 0'? [-Werror,-Wint-in-bool-context]

(cherry-picked from commit c9d4059386aea879d7305718a35b55cf2dc02ed6)
Change-Id: I7f788fcb48620c9ba82bd008b7b32382e1b5f958
CR-Id: ALPS05511922
Feature: [Module]Kernel Maintenance
Signed-off-by: Miles Chen <miles.chen@mediatek.com>