mmc: Mediatek: fix file_operations build breaks
Errors:
drivers/mmc/host/mtk-dbg.c:990:10: error: incompatible pointer types passing 'const struct file_operations *' to parameter of type 'const struct proc_ops *' [-Werror,-Wincompatible-pointer-types]

Change-Id: I4f7feb9ca60e91892adac4609affad2255155eb8
CR-Id: ALPS05708600
Feature: [Module]Kernel Maintenance
Signed-off-by: Miles Chen <miles.chen@mediatek.com>