[ALPS04783226] l3cc: fix build breaks when CONFIG_KASAN=y
Fix build breaks when CONFIG_KASAN=y with CC=gcc

drivers/misc/mediatek/cache-auditor/./trace_cache_auditor.h:39:12:
error: format ‘%lx’ expects argument of type ‘long unsigned int’,
but argument 4 has type ‘u64 {aka long long unsigned int}’
[-Werror=format=]
drivers/misc/mediatek/cache-auditor/./trace_cache_auditor.h:39:12:
error: format ‘%lu’ expects argument of type ‘long unsigned int’,
but argument 5 has type ‘u64 {aka long long unsigned int}’
[-Werror=format=]
drivers/misc/mediatek/cache-auditor/./trace_cache_auditor.h:131:12:
error: format ‘%d’ expects argument of type ‘int’, but argument 4
has type ‘long unsigned int’ [-Werror=format=]

MTK-Commit-Id: 8636893a149daa3ec68bf2be51129acef641f68f

Change-Id: Ia28bd38f6100c418a905c61dce46812c3bf53b2d
CR-Id: ALPS04783226
Signed-off-by: Miles Chen <miles.chen@mediatek.com>
Feature: System Performance