apusys: fix min_freq/max_freq not found build breaks
Error:
drivers/misc/mediatek/apusys/power/2.0/mt6873/apu_power_table.c:347:36: error: no member named 'min_freq' in 'struct devfreq'
drivers/misc/mediatek/apusys/power/2.0/mt6873/apu_power_table.c:357:36: error: no member named 'max_freq' in 'struct devfreq'

Signed-off-by: Miles Chen <miles.chen@mediatek.com>
Change-Id: I946c2a2a24fb34e07ab20fd4b475a6b9244f2916
CR-Id: ALPS05298037
Feature: [Module]Kernel Maintenance
Signed-off-by: Miles Chen <miles.chen@mediatek.com>
Source_Git_Sha: 5a123dd4a2fbb4919e5a24599436740f6b1d4119