apusys: fix no member named get_static_power build breaks
Errors:
/mfs/mtkslt0480/mtk04267/CAS_REAL/alps-dev-r0.bsp-common-kernel-5.4--2021_01_19_14_00-6873/merged/kernel-mainline/drivers/misc/mediatek/apusys/power/2.0/mar/apu_power_table.c:333:41: error: no member named 'get_static_power' in 'struct devfreq_cooling_power'; did you mean 'get_real_power'?
/mfs/mtkslt0480/mtk04267/CAS_REAL/alps-dev-r0.bsp-common-kernel-5.4--2021_01_19_14_00-6873/merged/kernel-mainline/drivers/misc/mediatek/apusys/power/2.0/mar/apu_power_table.c:333:58: error: incompatible pointer types assigning to 'int (*)(struct devfreq *, u32 *, unsigned long, unsigned long)' (aka 'int (*)(struct devfreq *, unsigned int *, unsigned long, unsigned long)') from 'unsigned long (struct devfreq *, unsigned long)' [-Werror,-Wincompatible-pointer-types]
/mfs/mtkslt0480/mtk04267/CAS_REAL/alps-dev-r0.bsp-common-kernel-5.4--2021_01_19_14_00-6873/merged/kernel-mainline/drivers/misc/mediatek/apusys/power/2.0/mar/apu_power_table.c:335:41: error: no member named 'get_dynamic_power' in 'struct devfreq_cooling_power'

Change-Id: I42696c2e3c4196f7093e3ce002285338b259fbf1
Signed-off-by: Miles Chen <miles.chen@mediatek.com>
CR-Id: ALPS05568046
Feature: [Module]Kernel Maintenance