trusted_mem: fix proc_create build breaks
Errors:
drivers/misc/mediatek/trusted_mem/proc.c:237:35: error: incompatible pointer types passing 'const struct file_operations *' to parameter of type 'const struct proc_ops *' [-Werror,-Wincompatible-pointer-types]

Change-Id: I3038a42d78b5df71a8e369ea3709c06185ea65c8
Signed-off-by: Miles Chen <miles.chen@mediatek.com>
CR-Id: ALPS05540930
Feature: [Module]Kernel Maintenance