Revert "lkdtm: Add kernel version to failure hints"
This reverts commit b8661450bc7f1f3dd746f8cac48534e0dfdc1cdf.

This is a preparation change for merging upstream [1] into msm-kalama
branch. The reverted change is causing consolidate variant build to
fail with below error. Once this is fixed the change should be
restored:

  drivers/misc/lkdtm/lkdtm.h:8:10: fatal error: 'generated/compile.h' file not found

[1] keystone/android-mainline-keystone-qcom-release@5f052f1

Change-Id: I1a413531a3201176c210fa05235ae85fa6891946