SCP: fix proc_create build breaks
Errors:
drivers/misc/mediatek/scp/rv55/scp_dvfs.c:1070:7: error: incompatible pointer types passing 'const struct file_operations *const' to parameter of type 'const struct proc_ops *' [-Werror,-Wincompatible-pointer-types]

Change-Id: Ie091edfdb1bb32958787d587f1219ce4512f6319
CR-Id: ALPS05489813
Feature: [Module]Kernel Maintenance
Signed-off-by: Miles Chen <miles.chen@mediatek.com>