spi: fix sometimes-uninitialized build breaks
Errors:
drivers/spi/spi-mt65xx.c:698:6: error: variable 'mdata' is used uninitialized whenever 'if' condition is true [-Werror,-Wsometimes-uninitialized]

Change-Id: If109f9d9d4c9db70a4c4c57de81e4dcaac021f12
CR-Id: ALPS05511922
Feature: [Module]Kernel Maintenance
Signed-off-by: Miles Chen <miles.chen@mediatek.com>
(cherry picked from commit dbe3d0cde4359c01400eafb9a2b3ae50dcea2626)