charger: fix timespec build breaks
Error:
drivers/power/supply/mtk_pe2.c:208:18: error: variable has incomplete type 'struct timespec'
drivers/power/supply/mtk_pe2.c:244:9: error: implicit declaration of function 'ktime_to_timespec' [-Werror,-Wimplicit-function-declaration]

Signed-off-by: Miles Chen <miles.chen@mediatek.com>
Feature: [Module]Kernel Maintenance
Change-Id: I3c582b82319fb80a3b9acee934f35915fd7335a1
CR-Id: ALPS05298037
Signed-off-by: Miles Chen <miles.chen@mediatek.com>