clk: mediatek: fix tautological-pointer-compare build breaks
Errors:
drivers/clk/mediatek/clkdbg.c:1795:17: error: comparison of array 'save_point_3.spm_pwr_status' not equal to a null pointer is always true [-Werror,-Wtautological-pointer-compare]
drivers/clk/mediatek/clkdbg.c:1798:17: error: comparison of array 'save_point_2.spm_pwr_status' not equal to a null pointer is always true [-Werror,-Wtautological-pointer-compare]
drivers/clk/mediatek/clkdbg.c:1801:17: error: comparison of array 'save_point_1.spm_pwr_status' not equal to a null pointer is always true [-Werror,-Wtautological-pointer-compare]

Change-Id: I34807c403b2b6a23a69dfb8b1d297dfb77d569bb
CR-Id: ALPS05511922
Feature: [Module]Kernel Maintenance
Signed-off-by: Miles Chen <miles.chen@mediatek.com>
(cherry picked from commit d8811d98ec4ab79d29d100e02a61f5814acb0661)