mtkcam: fix timeval build breaks
Error:

drivers/misc/mediatek/cameraisp/mfb/isp_6s/camera_mfb.c:2293:17: error: variable has incomplete type 'struct timeval'
drivers/misc/mediatek/cameraisp/mfb/isp_6s/camera_mfb.c:2500:17: error: variable has incomplete type 'struct timeval'

Signed-off-by: Miles Chen <miles.chen@mediatek.com>
Change-Id: Icde9c7f1a23676c985ec22b32641cc04fa008017
CR-Id: ALPS05298037
Feature: [Module]Kernel Maintenance
Signed-off-by: Miles Chen <miles.chen@mediatek.com>
Source_Git_Sha: 62aeda9cfa96d7af5fe8bd56b936d2935e71505d