power: smb1390: fix string format compiler warning
 drivers/power/supply/qcom/smb1390-charger-psy.c: In function 'smb1390_parse_dt':
 drivers/power/supply/qcom/smb1390-charger-psy.c:774:6: error:
   format '%ld'

Fixes: 279146a97ff0 ("power: smb1390: Add snapshot of driver")
Change-Id: Ic0dedbadeb8f7537fd633eef3f3db4b11bb8cb1d
Signed-off-by: Jordan Crouse <jcrouse@codeaurora.org>