[ALPS04328372] kbuild: fix build breaks caused by incorrect include path
This change fixes the following build breaks:

In file included from ../include/linux/dma-mapping.h:198:0,
from ../arch/arm/kernel/asm-offsets.c:16:
../arch/arm/include/asm/dma-mapping.h:17:25: fatal error:
mt-plat/aee.h: No such file or directory
 #include <mt-plat/aee.h>

../drivers/clk/mediatek/mt6739_clkmgr.c:33:32: fatal error:
mt-plat/sync_write.h: No such file or directory

MTK-Commit-Id: 6b15c22e758ba7ed226340f05c088ee9e198cd82

Change-Id: I3d7d6c50f8a5f04945ae49ec71c6b0b8a3a45528
Signed-off-by: Miles Chen <miles.chen@mediatek.com>
CR-Id: ALPS04328372
Feature: [Module]Kernel Maintenance