msdc: fix unused variable build breaks
Errors:
drivers/mmc/host/cqhci.c:570:6: error: unused variable 'reg' [-Werror,-Wunused-variable]

Change-Id: I561784c81df0fbfebf86aea503106c6cebb25cf5
CR-Id: ALPS05511922
Feature: [Module]Kernel Maintenance
Signed-off-by: Miles Chen <miles.chen@mediatek.com>