charger: fix get_fs build breaks
https://lwn.net/Articles/832121/

Errors:
drivers/power/supply/mtk_charger.c:84:7: error: implicit declaration of function 'get_fs' [-Werror,-Wimplicit-function-declaration]
drivers/power/supply/mtk_charger.c:84:5: error: assigning to 'mm_segment_t' from incompatible type 'int'
drivers/power/supply/mtk_charger.c:85:2: error: implicit declaration of function 'set_fs' [-Werror,-Wimplicit-function-declaration]
drivers/power/supply/mtk_charger.c:85:9: error: use of undeclared identifier 'KERNEL_DS'; did you mean 'KERNFS_NS'?

Change-Id: I26dd9d3c8c1e3220f652ac97fcb8df365da687b4
Signed-off-by: Miles Chen <miles.chen@mediatek.com>
CR-Id: ALPS05568046
Feature: [Module]Kernel Maintenance