soc: mediatek: devapc: fix iounmap build break
Error:
include/asm-generic/io.h:1015:2: error: implicit declaration of function 'iounmap' [-Werror,-Wimplicit-function-declaration]

Change-Id: I7ac0760263f715eb6d0e70c4482520a779e0d44c
CR-Id: ALPS05489813
Feature: [Module]Kernel Maintenance
Signed-off-by: Miles Chen <miles.chen@mediatek.com>
(cherry picked from commit 802b1b2fae212953a9d5dae097d5806b1dbf0d8c)