dma: mediatek: fix unused variable build breaks
Errors:
drivers/dma/mediatek/mtk-uart-apdma.c:270:16: error: unused variable 'flags' [-Werror,-Wunused-variable]

(cherry-picked from commit e8d515443311df364dd88525690699f0ad7a83f8)
Change-Id: I8077e63ffe5633514a06609d21cf2bea078398c2
CR-Id: ALPS05511922
Feature: [Module]Kernel Maintenance
Signed-off-by: Miles Chen <miles.chen@mediatek.com>