apusys: apu_tp: fix module_mutex build breaks
Errors:
drivers/misc/mediatek/apusys/debug/apu_tp.c:63:14: error: use of undeclared identifier 'module_mutex'; did you mean 'module_put'?
drivers/misc/mediatek/apusys/debug/apu_tp.c:65:16: error: use of undeclared identifier 'module_mutex'; did you mean 'module_put'?

Change-Id: Ic9c5da7e7b66993c862f7c861441ab10c56a5788
Signed-off-by: Miles Chen <miles.chen@mediatek.com>
Feature: [Module]Kernel Maintenance
CR-Id: ALPS05625693