[ALPS04783226] drcc: fix build break when CONFIG_KASAN=y
Fix build breaks when CONFIG_KASAN=y with CC=gcc

drivers/misc/mediatek/base/power/drcc_v1/mt6885/mtk_drcc.c:531:45:
error: format ‘%llx’ expects argument of type
‘long long unsigned int’,
but argument 3 has type ‘int’ [-Werror=format=]
rivers/misc/mediatek/base/power/drcc_v1/mt6885/mtk_drcc.c:1099:45:
error: format ‘%llx’ expects argument of type
‘long long unsigned int’,
but argument 3 has type ‘int’ [-Werror=format=]

MTK-Commit-Id: d7824ee030129e46dd0d9e2d4d1bf6140a949e0e

Change-Id: I80f0b87084e89ba7620777d739ac1d7f01ef9eb8
CR-Id: ALPS04783226
Signed-off-by: Miles Chen <miles.chen@mediatek.com>
Feature: PTP-OD (Performance Thermal Power-Over Drive)