mdp: fix timeval and proc_create build breaks
Error:
drivers/misc/mediatek/mdp/mdp_common.h:141:17: error: field has incomplete type 'struct timeval'
drivers/misc/mediatek/mdp/mdp_common.h:142:17: error: field has incomplete type 'struct timeval'
drivers/misc/mediatek/mdp/mdp_common.h:141:17: error: field has incomplete type 'struct timeval'
drivers/misc/mediatek/mdp/mdp_common.h:142:17: error: field has incomplete type 'struct timeval'
drivers/misc/mediatek/mdp/mdp_common.h:141:17: error: field has incomplete type 'struct timeval'
drivers/misc/mediatek/mdp/mdp_common.h:142:17: error: field has incomplete type 'struct timeval'
drivers/misc/mediatek/mdp/mdp_common.c:1829:3: error: implicit declaration of function 'pm_qos_remove_request' [-Werror,-Wimplicit-function-declaration]
drivers/misc/mediatek/mdp/mdp_common.h:141:17: error: field has incomplete type 'struct timeval'
drivers/misc/mediatek/mdp/mdp_common.h:142:17: error: field has incomplete type 'struct timeval'
drivers/misc/mediatek/mdp/mdp_common.h:141:17: error: field has incomplete type 'struct timeval'
drivers/misc/mediatek/mdp/mdp_common.h:142:17: error: field has incomplete type 'struct timeval'
drivers/misc/mediatek/mdp/mdp_common.h:141:17: error: field has incomplete type 'struct timeval'
drivers/misc/mediatek/mdp/mdp_common.h:142:17: error: field has incomplete type 'struct timeval'
drivers/misc/mediatek/mdp/mdp_driver.c:1145:4: error: incompatible pointer types passing 'const struct file_operations *' to parameter of type 'const struct proc_ops *' [-Werror,-Wincompatible-pointer-types]/mfs/mtkslt0480/mtk04267/CAS_REAL/alps-dev-r0_bsp-common-kernel-5_4--2020_08_09_16_00/merged/kernel-5.4/drivers/misc/mediatek/mdp/cmdq_reg.h
t struct proc_ops *' [-Werror,-Wincompatible-pointer-types]
drivers/misc/mediatek/mdp/mdp_common.h:141:17: error: field has incomplete type 'struct timeval'
drivers/misc/mediatek/mdp/mdp_common.h:142:17: error: field has incomplete type 'struct timeval'
drivers/misc/mediatek/mdp/mdp_common.h:141:17: error: field has incomplete type 'struct timeval'
drivers/misc/mediatek/mdp/mdp_common.h:142:17: error: field has incomplete type 'struct timeval'

Signed-off-by: Miles Chen <miles.chen@mediatek.com>
Change-Id: Id1108eaaa73856c4c1dc92494a3ad7fd9e79192d
CR-Id: ALPS05298037
Feature: [Module]Kernel Maintenance
Signed-off-by: Miles Chen <miles.chen@mediatek.com>
Source_Git_Sha: d03f2066111cd6efa3bdfa0ee3c5b957d0ca0cc1