lpm: fix timespec build breaks
Error:
drivers/misc/mediatek/lpm/modules/platform/mt6873/suspend/mt6873_suspend.c:167:18: error: variable has incomplete type 'struct timespec'
drivers/misc/mediatek/lpm/modules/platform/mt6873/suspend/mt6873_suspend.c:170:2: error: implicit declaration of function 'getnstimeofday' [-Werror,-Wimplicit-function-declaration]
drivers/misc/mediatek/lpm/modules/platform/mt6873/suspend/mt6873_suspend.c:171:2: error: implicit declaration of function 'rtc_time_to_tm' [-Werror,-Wimplicit-function-declaration]

Signed-off-by: Miles Chen <miles.chen@mediatek.com>
Change-Id: Ie0ccb49bab577956cd002e65849ed53f67631aa1
CR-Id: ALPS05298037
Feature: [Module]Kernel Maintenance
Signed-off-by: Miles Chen <miles.chen@mediatek.com>
Source_Git_Sha: 4f00a2e39d1b1c2200a2fafc2c2eff456d53e9a2