ISP P1: fix proc_create and timeval build breaks
Error:
drivers/misc/mediatek/cameraisp/src/isp_6s/camera_isp.c:3045:17: error: variable has incomplete type 'struct timeval'
drivers/misc/mediatek/cameraisp/src/isp_6s/camera_isp.c:3046:17: error: variable has incomplete type 'struct timeval'
drivers/misc/mediatek/cameraisp/src/isp_6s/camera_isp.c:7473:44: error: incompatible pointer types passing 'const struct file_operations *' to parameter of type 'const struct proc_ops *' [-Werror,-Wincompatible-pointer-types]
drivers/misc/mediatek/cameraisp/src/isp_6s/camera_isp.c:7474:46: error: incompatible pointer types passing 'const struct file_operations *' to parameter of type 'const struct proc_ops *' [-Werror,-Wincompatible-pointer-types]
drivers/misc/mediatek/cameraisp/src/isp_6s/camera_isp.c:9024:17: error: variable has incomplete type 'struct timeval'
drivers/misc/mediatek/cameraisp/src/isp_6s/cam_qos.c:894:3: error: implicit declaration of function 'pm_qos_remove_request' [-Werror,-Wimplicit-function-declaration]
drivers/misc/mediatek/cameraisp/src/isp_6s/camera_isp.c:10472:17: error: variable has incomplete type 'struct timeval'
drivers/misc/mediatek/cameraisp/src/isp_6s/cam_qos.c:898:3: error: implicit declaration of function 'pm_qos_update_request' [-Werror,-Wimplicit-function-declaration]

Signed-off-by: Miles Chen <miles.chen@mediatek.com>
Change-Id: Icd3361627060ae76d45ce67590020a5bb9f8709f
CR-Id: ALPS05298037
Feature: [Module]Kernel Maintenance
Signed-off-by: Miles Chen <miles.chen@mediatek.com>
Source_Git_Sha: e9fb7e66cbb8e4b3e3e2940d418595bd6edf400d