Lens: fix unused variable build breaks
Errors:
drivers/misc/mediatek/lens/vcm/proprietary/main/common/lc898212xdaf/LC898212XDAF.c:158:17: error: unused variable 'HallCheck' [-Werror,-Wunused-variable]

(cherry-picked from commit 0156275fbe2e589bba1ac7800fb6ed1209be6fb6)
Change-Id: I51ff52e7f63b1aac065120d4eb97dfaa8335e712
CR-Id: ALPS05511922
Feature: [Module]Kernel Maintenance
Signed-off-by: Miles Chen <miles.chen@mediatek.com>