ANDROID: fix kernelci issue: visibility of struct cgroup_subsys
Kernelci reported:
include/trace/hooks/cgroup.h:27:18: error: declaration of 'struct cgroup_subsys'
will not be visible outside of this function

Fixes: 2487db8d5960 ("ANDROID: freezer: Add vendor hook to freezer for GKI
purpose.")
Signed-off-by: Todd Kjos <tkjos@google.com>
Change-Id: I7678fc03df6593ca42f2043f33ec3c3fee8d362b