GPU: fix proc_create() build breaks
Error:
kernel-5.4/drivers/gpu/mediatek/gpu_bm/gpu_bm.c:77:44: error: incompatible pointer types passing 'const struct file_operations *' to parameter of type 'const struct proc_ops *' [-Werror,-Wincompatible-pointer-types]

Signed-off-by: Miles Chen <miles.chen@mediatek.com>
Feature: [Module]Kernel Maintenance
Change-Id: I0830cec524c436fe5df537770c63dae170f77fbd
CR-Id: ALPS05298037
Signed-off-by: Miles Chen <miles.chen@mediatek.com>
Source_Git_Sha: 7e1e2545b4d5e58912ca34c06ffbb71ecdfddaa9