typec: mux: fix typec_mux_set_fn_t build breaks
Error:
drivers/misc/mediatek/typec/mux/mux_switch.c:338:15: error: incompatible pointer types assigning to 'typec_mux_set_fn_t' (aka 'int (*)(struct typec_mux *, struct typec_mux_state *)') from 'int (struct typec_mux *, int)' [-Werror,-Wincompatible-pointer-types]

Change-Id: I945af6f841df5de01de18574a24cd5fc1e7bd6db
CR-Id: ALPS05420447
Feature: [Module]Kernel Maintenance
Signed-off-by: Miles Chen <miles.chen@mediatek.com>
(cherry picked from commit 9254b88a1c3db1e0f5f02d5ba7f55799e3b651b4)