GPU: fix proc_create() build breaks
Error:
drivers/gpu/mediatek/gpufreq_v1/mt6853/mtk_gpufreq_plat.c:2402:48: error: incompatible pointer types passing 'const struct file_operations *const' to parameter of type 'const struct proc_ops *' [-Werror,-Wincompatible-pointer-types]

Change-Id: I84a61df469f08293b3fa3ccb7ca9c33807823ca7
Feature: OpenGL|ES
CR-Id: ALPS05298037
Signed-off-by: Miles Chen <miles.chen@mediatek.com>
Source_Git_Sha: c84f779932f26ec7d853e20f90b3e0e6acd82e08