flashlight: fix kzfree build breaks
Errors:
drivers/misc/mediatek/flashlight/mtk-composite.c:257:2: error: implicit declaration of function 'kzfree' [-Werror,-Wimplicit-function-declaration]

Change-Id: I1a657693a5ae035737c54b44adc7cdcb64ceae64
CR-Id: ALPS05431666
Feature: [Module]Kernel Maintenance
Signed-off-by: Miles Chen <miles.chen@mediatek.com>