Charger: fix phy_put build breaks
Errors:
drivers/power/supply/mt6362-chg.c:566
:13: error: too few arguments to function call, expected 2, have 1

Change-Id: I63337e869f5f3fe46c0b8ff5f2d016c98fa254b9
CR-Id: ALPS05489813
Feature: [Module]Kernel Maintenance
Signed-off-by: Miles Chen <miles.chen@mediatek.com>