GPU: fix proc_create build breaks
Error:
drivers/gpu/mediatek/gpufreq_v1/mt6873/mtk_gpufreq_plat.c:2460:48: error: incompatible pointer types passing 'const struct file_operations *const' to parameter of type 'const struct proc_ops *' [-Werror,-Wincompatible-pointer-types]

Signed-off-by: Miles Chen <miles.chen@mediatek.com>
Change-Id: I99c25e3bcfaad9292b00b42000e83d9de5f53f76
CR-Id: ALPS05298037
Feature: [Module]Kernel Maintenance
Signed-off-by: Miles Chen <miles.chen@mediatek.com>