cpufreq: mediatek-hw: fix em_dev_register_perf_domain build breaks
Errors:
drivers/cpufreq/mediatek-cpufreq-hw.c:182:70: error: too few arguments to function call, expected 5, have 4

Change-Id: I8025ed0754ee009c0596b3e07cc59e9530616256
Signed-off-by: Miles Chen <miles.chen@mediatek.com>
CR-Id: ALPS05568046
Feature: [Module]Kernel Maintenance