[ALPS04783226] ccci: fix build breaks when CC=gcc
Fix build breaks when CC=gcc

../drivers/misc/mediatek/eccci/mt6885/md_sys1_platform.c:
In function ‘md_cd_lock_modem_clock_src’:
../include/linux/kern_levels.h:5:18: error: format ‘%u’
expects argument of type ‘unsigned int’, but argument 4 has
type ‘size_t {aka long unsigne
d int}’ [-Werror=format=]

MTK-Commit-Id: a3666c540e8ccd7764a61318e0769e211dcb7b4c

Change-Id: I25960a1e678c0619770e5d79f23e12a596b9026c
CR-Id: ALPS04783226
Signed-off-by: Miles Chen <miles.chen@mediatek.com>
Feature: Modem Interface Driver