lpm: fix unsequenced modification and access build breaks
Errors:
drivers/misc/mediatek/lpm/modules/debug/v1/lpm_dbg_cpuidle_state.c:207:24: error: unsequenced modification and access to 'i' [-Werror,-Wunsequenced]

(cherry-picked from commit 91afe67fdd751c6fe39d28784bcbd40148431c9d)
Change-Id: I2d760e2501b55b782249798eaed735a7ae564931
CR-Id: ALPS05511922
Feature: [Module]Kernel Maintenance
Signed-off-by: Miles Chen <miles.chen@mediatek.com>