performance: tchbst: fix proc_create() build breaks
Error:
drivers/misc/mediatek/performance/tchbst/utch.c:399:52: error: incompatible pointer types passing 'const struct file_operations *' to parameter of type 'const struct proc_ops *' [-Werror,-Wincompatible-pointer-types]
drivers/misc/mediatek/performance/tchbst/utch.c:404:56: error: incompatible pointer types passing 'const struct file_operations *' to parameter of type 'const struct proc_ops *' [-Werror,-Wincompatible-pointer-types]

Feature: [Module]Kernel Maintenance
Change-Id: I4830eb1fb24cd25138c0ac0ac143369fecf715de
CR-Id: ALPS05298037
Signed-off-by: Miles Chen <miles.chen@mediatek.com>
Source_Git_Sha: 1118423213a8544d92d093bb78b21d4b7dd5a682