lpm: fix timespec, pm_qos API changes build breaks
Error:
drivers/misc/mediatek/lpm/mtk_lpm_module.c:143:21: error: incompatible function pointer types assigning to 's2idle_enter' (aka 'void (*)(struct cpuidle_device *, struct cpuidle_driver *, int)') from 'int (*)(struct cpuidle_device *, struct cpuidle_driver *, int)' [-Werror,-Wincompatible-function-pointer-types]
drivers/misc/mediatek/lpm/mtk_lpm_module.c:144:34: error: incompatible function pointer types assigning to 'int (*)(struct cpuidle_device *, struct cpuidle_driver *, int)' from 's2idle_enter' (aka 'void (*)(struct cpuidle_device *, struct cpuidle_driver *, int)') [-Werror,-Wincompatible-function-pointer-types]
drivers/misc/mediatek/lpm/modules/platform/mt6873/mtk_lp_plat_apmcu.c:196:2: error: implicit declaration of function 'pm_qos_update_request' [-Werror,-Wimplicit-function-declaration]
drivers/misc/mediatek/lpm/modules/platform/mt6873/mtk_lp_plat_apmcu.c:205:2: error: implicit declaration of function 'pm_qos_update_request' [-Werror,-Wimplicit-function-declaration]
drivers/misc/mediatek/lpm/modules/platform/mt6873/mtk_lp_plat_apmcu.c:226:8: error: implicit declaration of function 'ktime_to_timespec' [-Werror,-Wimplicit-function-declaration]
drivers/misc/mediatek/lpm/modules/platform/mt6873/mtk_lp_plat_apmcu.c:226:6: error: incomplete type 'struct timespec' is not assignable
drivers/misc/mediatek/lpm/modules/platform/mt6873/mtk_lp_plat_apmcu.c:231:18: error: variable has incomplete type 'struct timespec'
drivers/misc/mediatek/lpm/modules/platform/mt6873/mtk_lp_plat_apmcu.c:253:2: error: implicit declaration of function 'pm_qos_update_request' [-Werror,-Wimplicit-function-declaration]
drivers/misc/mediatek/lpm/modules/platform/mt6873/mtk_lp_plat_apmcu.c:315:3: error: implicit declaration of function 'pm_qos_remove_request' [-Werror,-Wimplicit-function-declaration]
drivers/misc/mediatek/lpm/modules/platform/mt6873/mtk_lp_plat_apmcu.c:339:2: error: implicit declaration of function 'pm_qos_add_request' [-Werror,-Wimplicit-function-declaration]
drivers/misc/mediatek/lpm/modules/debug/mt6873/mtk_idle_procfs_cpc.c:106:25: error: incompatible pointer types passing 'const struct file_operations *const' to parameter of type 'const struct proc_ops *' [-Werror,-Wincompatible-pointer-types]
drivers/misc/mediatek/lpm/modules/platform/mt6873/mtk_lp_plat_apmcu.c:339:2: error: use of undeclared identifier 'PM_QOS_CPU_DMA_LATENCY'
drivers/misc/mediatek/lpm/modules/platform/mt6873/mtk_lp_plat_apmcu.c:348:2: error: implicit declaration of function 'pm_qos_update_request' [-Werror,-Wimplicit-function-declaration]
drivers/misc/mediatek/lpm/modules/debug/mt6873/mtk_idle_procfs_state.c:67:5: error: no member named 'disabled' in 'struct cpuidle_state'
drivers/misc/mediatek/lpm/modules/debug/mt6873/mtk_idle_procfs_state.c:70:3: error: no member named 'disabled' in 'struct cpuidle_state'
drivers/misc/mediatek/lpm/modules/debug/mt6873/mtk_idle_procfs_state.c:246:25: error: incompatible pointer types passing 'const struct file_operations *const' to parameter of type 'const struct proc_ops *' [-Werror,-Wincompatible-pointer-types]
drivers/misc/mediatek/lpm/modules/debug/mt6873/mtk_cpuidle_status.c:321:4: error: no member named 'disabled' in 'struct cpuidle_state'
drivers/misc/mediatek/lpm/modules/debug/mt6873/mtk_cpuidle_status.c:324:17: error: no member named 'disabled' in 'struct cpuidle_state'
drivers/misc/mediatek/lpm/modules/debug/mt6873/mtk_idle_procfs.c:127:25: error: incompatible pointer types passing 'const struct file_operations *const' to parameter of type 'const struct proc_ops *' [-Werror,-Wincompatible-pointer-types]
drivers/misc/mediatek/lpm/modules/debug/mt6873/mtk_cpupm_dbg.c:74:2: error: implicit declaration of function 'pm_qos_update_request' [-Werror,-Wimplicit-function-declaration]
drivers/misc/mediatek/lpm/modules/debug/mt6873/mtk_cpupm_dbg.c:79:2: error: implicit declaration of function 'pm_qos_update_request' [-Werror,-Wimplicit-function-declaration]
drivers/misc/mediatek/lpm/modules/debug/mt6873/mtk_cpupm_dbg.c:132:2: error: implicit declaration of function 'pm_qos_add_request' [-Werror,-Wimplicit-function-declaration]
drivers/misc/mediatek/lpm/modules/debug/mt6873/mtk_idle_procfs_profile.c:171:25: error: incompatible pointer types passing 'const struct file_operations *const' to parameter of type 'const struct proc_ops *' [-Werror,-Wincompatible-pointer-types]
drivers/misc/mediatek/lpm/modules/debug/mt6873/mtk_cpupm_dbg.c:133:3: error: use of undeclared identifier 'PM_QOS_CPU_DMA_LATENCY'
drivers/misc/mediatek/lpm/modules/debug/mt6873/mtk_cpupm_dbg.c:152:2: error: implicit declaration of function 'pm_qos_remove_request' [-Werror,-Wimplicit-function-declaration]
drivers/misc/mediatek/lpm/modules/debug/mt6873/mtk_idle_procfs_control.c:337:25: error: incompatible pointer types passing 'const struct file_operations *const' to parameter of type 'const struct proc_ops *' [-Werror,-Wincompatible-pointer-types]

Signed-off-by: Miles Chen <miles.chen@mediatek.com>
Change-Id: I0979843a4041945ceddc9a9830eeb73fc799613c
CR-Id: ALPS05298037
Feature: [Module]Kernel Maintenance
Signed-off-by: Miles Chen <miles.chen@mediatek.com>
Source_Git_Sha: 9bb5b69ea688c6d273105eb5c32e99b10b6b1fe6