suspend: lpm: common: fix ioremap_nocache build breaks
Errors:
drivers/misc/mediatek/lpm/modules/debug/v1/gs/v1/lpm_pwr_gs_dump_clk.c:55:6: error: implicit declaration of function 'ioremap_nocache' [-Werror,-Wimplicit-function-declaration]

Change-Id: Id6fb02cd0e2c6dfdc9ba9c5c21dda14a07502008
CR-Id: ALPS05476666
Feature: [Module]Kernel Maintenance
Signed-off-by: Miles Chen <miles.chen@mediatek.com>