thermal: fix unused variable build breaks
Errors:
drivers/thermal/mediatek/soc_temp_lvts.c:259:17: error: unused variable 'dev' [-Werror,-Wunused-variable]
drivers/thermal/mediatek/soc_temp_lvts.c:301:17: error: unused variable 'dev' [-Werror,-Wunused-variable]
drivers/thermal/mediatek/soc_temp_lvts.c:391:17: error: unused variable 'dev' [-Werror,-Wunused-variable]
drivers/thermal/mediatek/soc_temp_lvts.c:989:17: error: unused variable 'dev' [-Werror,-Wunused-variable]

(cherry-picked from commit a93c5971686d75cfc3d2da3c5fc7b542573e128a)
Change-Id: I9d27863de1bdfe4d28077249ffc393f54f55bce8
CR-Id: ALPS05511922
Feature: [Module]Kernel Maintenance
Signed-off-by: Miles Chen <miles.chen@mediatek.com>