dvfs: fix misleading indentation build breaks
Errors:
drivers/misc/mediatek/cpufreq_v1/cpufreq-dbg.c:192:4: error: misleading indentation; statement is not part of the previous 'else' [-Werror,-Wmisleading-indentation]

(cherry-picked from commit e33448109a6909ee1668b4f7fed6297673371d19)
Change-Id: Ia6472127935a151cff77f3c1493e01caa91ee114
CR-Id: ALPS05511922
Feature: [Module]Kernel Maintenance
Signed-off-by: Miles Chen <miles.chen@mediatek.com>
(cherry picked from commit de50997bb7501acc653a9a5c4962398f4a0def62)