vow: fix timesepc and for_each_rtdcom build breaks
Errors:
sound/soc/mediatek/mt6873/mt6873-mt6359p.c:356:2: error: implicit declaration of function 'for_each_rtdcom' [-Werror,-Wimplicit-function-declaration]
sound/soc/mediatek/mt6873/mt6873-mt6359p.c:356:30: error: expected ';' after expression
sound/soc/mediatek/mt6873/mt6873-mt6359p.c:357:21: error: incomplete definition of type 'struct snd_soc_rtdcom_list'
sound/soc/mediatek/mt6873/mt6873-mt6359p.c:376:2: error: implicit declaration of function 'for_each_rtdcom' [-Werror,-Wimplicit-function-declaration]
sound/soc/mediatek/mt6873/mt6873-mt6359p.c:376:30: error: expected ';' after expression
sound/soc/mediatek/mt6873/mt6873-mt6359p.c:377:21: error: incomplete definition of type 'struct snd_soc_rtdcom_list'
drivers/misc/mediatek/vow/ver02/vow.c:1443:18: error: variable has incomplete type 'struct timespec'
drivers/misc/mediatek/vow/ver02/vow.c:1457:22: error: invalid application of 'sizeof' to an incomplete type 'struct timespec'
drivers/misc/mediatek/vow/ver02/vow.c:1458:2: error: implicit declaration of function 'getnstimeofday' [-Werror,-Wimplicit-function-declaration]

Change-Id: If9d0f0f864687137a31501c1cc7292458134409c
CR-Id: ALPS05387457
Feature: [Module]Kernel Maintenance
Signed-off-by: Miles Chen <miles.chen@mediatek.com>