charger: fix timespec, proc_create build breaks
Error:
drivers/power/supply/mtk_charger.h:262:18: error: field has incomplete type 'struct timespec'
drivers/power/supply/mtk_charger.h:295:18: error: field has incomplete type 'struct timespec'
drivers/power/supply/mtk_charger.h:262:18: error: field has incomplete type 'struct timespec'
drivers/power/supply/mtk_charger.h:295:18: error: field has incomplete type 'struct timespec'
drivers/power/supply/mtk_pulse_charger.c:76:18: error: field has incomplete type 'struct timespec'
drivers/power/supply/mtk_pulse_charger.c:77:18: error: field has incomplete type 'struct timespec'
drivers/power/supply/mtk_pulse_charger.c:274:18: error: variable has incomplete type 'struct timespec'
drivers/power/supply/mtk_pulse_charger.c:274:28: error: variable has incomplete type 'struct timespec'
drivers/power/supply/mtk_pulse_charger.c:286:36: error: implicit declaration of function 'timespec_to_ktime' [-Werror,-Wimplicit-function-declaration]
drivers/power/supply/mtk_pulse_charger.c:287:18: error: implicit declaration of function 'ktime_to_timespec' [-Werror,-Wimplicit-function-declaration]
drivers/power/supply/mtk_pulse_charger.c:336:18: error: variable has incomplete type 'struct timespec'
drivers/power/supply/mtk_pulse_charger.c:336:28: error: variable has incomplete type 'struct timespec'
drivers/power/supply/mtk_pulse_charger.c:336:43: error: variable has incomplete type 'struct timespec'
drivers/power/supply/mtk_pulse_charger.c:345:36: error: implicit declaration of function 'timespec_to_ktime' [-Werror,-Wimplicit-function-declaration]
drivers/power/supply/mtk_pulse_charger.c:346:18: error: implicit declaration of function 'ktime_to_timespec' [-Werror,-Wimplicit-function-declaration]
drivers/power/supply/mtk_pulse_charger.c:405:36: error: implicit declaration of function 'ktime_to_timespec' [-Werror,-Wimplicit-function-declaration]
drivers/power/supply/mtk_pulse_charger.c:442:37: error: implicit declaration of function 'ktime_to_timespec' [-Werror,-Wimplicit-function-declaration]
drivers/power/supply/mtk_pulse_charger.c:540:36: error: implicit declaration of function 'ktime_to_timespec' [-Werror,-Wimplicit-function-declaration]
drivers/power/supply/mtk_charger.h:262:18: error: field has incomplete type 'struct timespec'
drivers/power/supply/mtk_charger.h:295:18: error: field has incomplete type 'struct timespec'
drivers/power/supply/mtk_charger.h:262:18: error: field has incomplete type 'struct timespec'
drivers/power/supply/mtk_charger.h:295:18: error: field has incomplete type 'struct timespec'
drivers/power/supply/mtk_charger.h:262:18: error: field has incomplete type 'struct timespec'
drivers/power/supply/mtk_charger.h:295:18: error: field has incomplete type 'struct timespec'
drivers/power/supply/mtk_charger.c:472:18: error: variable has incomplete type 'struct timespec'
drivers/power/supply/mtk_charger.c:472:28: error: variable has incomplete type 'struct timespec'
drivers/power/supply/mtk_charger.c:484:13: error: implicit declaration of function 'ktime_to_timespec' [-Werror,-Wimplicit-function-declaration]
drivers/power/supply/mtk_charger.c:1544:18: error: variable has incomplete type 'struct timespec'
drivers/power/supply/mtk_charger.c:1559:9: error: implicit declaration of function 'ktime_to_timespec' [-Werror,-Wimplicit-function-declaration]
drivers/power/supply/mtk_charger.c:1561:7: error: implicit declaration of function 'timespec_compare' [-Werror,-Wimplicit-function-declaration]
drivers/power/supply/mtk_charger.c:1649:4: error: incompatible pointer types passing 'const struct file_operations *' to parameter of type 'const struct proc_ops *' [-Werror,-Wincompatible-pointer-types]
drivers/power/supply/mtk_charger.c:1655:4: error: incompatible pointer types passing 'const struct file_operations *' to parameter of type 'const struct proc_ops *' [-Werror,-Wincompatible-pointer-types]
drivers/power/supply/mtk_charger.c:1661:4: error: incompatible pointer types passing 'const struct file_operations *' to parameter of type 'const struct proc_ops *' [-Werror,-Wincompatible-pointer-types]

Signed-off-by: Miles Chen <miles.chen@mediatek.com>
Change-Id: I4dadf8fb821a530190097df79203a4acd0ab8ed3
CR-Id: ALPS05298037
Feature: [Module]Kernel Maintenance
Signed-off-by: Miles Chen <miles.chen@mediatek.com>
Source_Git_Sha: 3a360e64b6d860f2c17973237d3e1fbcadb08c64