thermal: fix warn_unused_result build breaks
Errors:
drivers/thermal/mediatek/thermal_ipi.c:253:2: error: ignoring return value of function declared with 'warn_unused_result' attribute [-Werror,-Wunused-result]

Change-Id: If340774c5dc2244e62f8d2d95999cc99dcb4437e
CR-Id: ALPS05584628
Feature: [Module]Kernel Maintenance
Signed-off-by: Miles Chen <miles.chen@mediatek.com>