[ALPS05550128] Migration: Fix build breaks
    kernel-4.14/sound/soc/codecs/mt6358.c:6684:7: error: incomplete
    definition of type struct mt6359_priv
    priv->mux_select[MUX_MIC_TYPE] == MIC_TYPE_MUX_DMIC;
    ~~~~^

MTK-Commit-Id: 2f08c861f0299e6749a122b9c58adc102e67be5f

Change-Id: Ia7d7d93e5a0db08aa54ac636a9ab86b46de417ad
CR-Id: ALPS05550128
Feature: Build error
Signed-off-by: Bo Ye <bo.ye@mediatek.com>