ion: Make MSM pool auto refill built-in only
When built as a module, msm_ion_heaps.ko is missing the following
generic unexported symbols:

  ERROR: "__next_zones_zonelist" [drivers/staging/android/ion/heaps/msm_ion_heaps.ko] undefined!
  ERROR: "zone_watermark_ok_safe" [drivers/staging/android/ion/heaps/msm_ion_heaps.ko] undefined!

Make ION_POOL_AUTO_REFILL depend on ION_MSM_HEAPS=y which should make
sure that the symbols are only used when the driver is built in.

Change-Id: Ic0dedbadc048743b9f92070af97ef2656e78a0ab
Signed-off-by: Jordan Crouse <jcrouse@codeaurora.org>