lpm: fix tautological-pointer-compare build breaks
Errors:
drivers/misc/mediatek/lpm/modules/debug/v1/lpm_dbg_rc_fs.c:553:20: error: comparison of array 'rc_handle' equal to a null pointer is always false [-Werror,-Wtautological-pointer-compare]

Change-Id: Ie67ebbe96644745c2734d136e7395bbdc9459ea2
CR-Id: ALPS05511922
Feature: [Module]Kernel Maintenance
Signed-off-by: Miles Chen <miles.chen@mediatek.com>