GPU: fix implicit declaration of function ksys_close build breaks
Errors:
drivers/gpu/mediatek/gpu_mali/mali_valhall/mali-r25p0/drivers/gpu/arm/midgard/mali_kbase_sync.h:165:2: error: implicit declaration of function 'ksys_close' [-Werror,-Wimplicit-function-declaration]
drivers/gpu/mediatek/gpu_mali/mali_valhall/mali-r25p0/drivers/gpu/arm/midgard/mali_kbase_sync.h:165:2: error: implicit declaration of function 'ksys_close' [-Werror,-Wimplicit-function-declaration]
drivers/gpu/mediatek/gpu_mali/mali_valhall/mali-r25p0/drivers/gpu/arm/midgard/mali_kbase_sync.h:165:2: error: implicit declaration of function 'ksys_close' [-Werror,-Wimplicit-function-declaration]
drivers/gpu/mediatek/gpu_mali/mali_valhall/mali-r25p0/drivers/gpu/arm/midgard/mali_kbase_sync.h:165:2: error: implicit declaration of function 'ksys_close' [-Werror,-Wimplicit-function-declaration]
drivers/gpu/mediatek/gpu_mali/mali_valhall/mali-r25p0/drivers/gpu/arm/midgard/mali_kbase_sync.h:165:2: error: implicit declaration of function 'ksys_close' [-Werror,-Wimplicit-function-declaration]
drivers/gpu/mediatek/gpu_mali/mali_valhall/mali-r25p0/drivers/gpu/arm/midgard/ipa/mali_kbase_ipa.c:600:3: error: field designator 'get_static_power' does not refer to any field in type 'struct devfreq_cooling_power'; did you mean 'get_real_power'?
drivers/gpu/mediatek/gpu_mali/mali_valhall/mali-r25p0/drivers/gpu/arm/midgard/ipa/mali_kbase_ipa.c:600:22: error: incompatible function pointer types initializing 'int (*)(struct devfreq *, u32 *, unsigned long, unsigned long)' (aka 'int (*)(struct devfreq *, unsigned int *, unsigned long, unsigned long)') with an expression of type 'unsigned long (*)(struct devfreq *, unsigned long)' [-Werror,-Wincompatible-function-pointer-types]
drivers/gpu/mediatek/gpu_mali/mali_valhall/mali-r25p0/drivers/gpu/arm/midgard/ipa/mali_kbase_ipa.c:601:3: error: field designator 'get_dynamic_power' does not refer to any field in type 'struct devfreq_cooling_power'

Change-Id: I671c432f5888833515c6aaab1d25246261ed4e9a
Signed-off-by: Miles Chen <miles.chen@mediatek.com>
CR-Id: ALPS05568046
Feature: [Module]Kernel Maintenance