spi: mediatek: fix pm_qos build breaks
Error:
drivers/spi/spi-mt65xx.c:803:2: error: implicit declaration of function 'pm_qos_add_request' [-Werror,-Wimplicit-function-declaration]
drivers/spi/spi-mt65xx.c:803:46: error: use of undeclared identifier 'PM_QOS_CPU_DMA_LATENCY'
drivers/spi/spi-mt65xx.c:821:2: error: implicit declaration of function 'pm_qos_remove_request' [-Werror,-Wimplicit-function-declaration]
drivers/spi/spi-mt65xx.c:875:2: error: implicit declaration of function 'pm_qos_update_request' [-Werror,-Wimplicit-function-declaration]
drivers/spi/spi-mt65xx.c:891:2: error: implicit declaration of function 'pm_qos_update_request' [-Werror,-Wimplicit-function-declaration]

Change-Id: I6c88b12fb29ce7cd6869396bbc20fa26907236f4
CR-Id: ALPS05377375
Feature: [Module]Kernel Maintenance
Signed-off-by: Miles Chen <miles.chen@mediatek.com>