remoteproc: fix allmodconfig build breaks
fix remoteproc related allmodconfig build breaks

build command:
ARCH=arm64 make mrproper allmodconfig all

probe_kernel_address is replaced by get_kernel_nofault in
the commit: 25f12ae45fc1 ("maccess: rename probe_kernel_address
to get_kernel_nofault")

Errors:
drivers/remoteproc/mtk_ccd.c:265:22: error: implicit declaration of function 'compat_ptr' [-Werror,-Wimplicit-function-declaration]
drivers/remoteproc/mtk_ccd_mem.c:180:6: error: implicit declaration of function 'probe_kernel_address' [-Werror,-Wimplicit-function-declaration]
drivers/remoteproc/mtk_ccd_mem.c:181:52: error: variable 'siglock' is uninitialized when used here [-Werror,-Wuninitialized]
drivers/remoteproc/mtk_ccd_mem.c:180:43: error: variable 'sighand' is uninitialized when used here [-Werror,-Wuninitialized]

Change-Id: I76274afc2e2aa53824ca0926b240a4c20ae52ea2
Cc: Frederic Chen <frederic.chen@mediatek.com>
Signed-off-by: Miles Chen <miles.chen@mediatek.com>
Feature: Kernel SI Operation
CR-Id: ALPS05903624