task-turbo: fix braces around initialization build breaks
Errors:
drivers/misc/mediatek/task_turbo/features.h:10:1: error: suggest braces around initialization of subobject [-Werror,-Wmissing-braces]
drivers/misc/mediatek/task_turbo/features.h:15:1: error: suggest braces around initialization of subobject [-Werror,-Wmissing-braces]
drivers/misc/mediatek/task_turbo/features.h:10:1: error: suggest braces around initialization of subobject [-Werror,-Wmissing-braces]
drivers/misc/mediatek/task_turbo/features.h:21:1: error: suggest braces around initialization of subobject [-Werror,-Wmissing-braces]
drivers/misc/mediatek/task_turbo/features.h:27:1: error: suggest braces around initialization of subobject [-Werror,-Wmissing-braces]
drivers/misc/mediatek/task_turbo/features.h:21:1: error: suggest braces around initialization of subobject [-Werror,-Wmissing-braces]
drivers/misc/mediatek/task_turbo/features.h:32:1: error: suggest braces around initialization of subobject [-Werror,-Wmissing-braces]
drivers/misc/mediatek/task_turbo/features.h:36:1: error: suggest braces around initialization of subobject [-Werror,-Wmissing-braces]
drivers/misc/mediatek/task_turbo/features.h:32:1: error: suggest braces around initialization of subobject [-Werror,-Wmissing-braces]
drivers/misc/mediatek/task_turbo/features.h:37:1: error: suggest braces around initialization of subobject [-Werror,-Wmissing-braces]
drivers/misc/mediatek/task_turbo/features.h:38:1: error: suggest braces around initialization of subobject [-Werror,-Wmissing-braces]
drivers/misc/mediatek/task_turbo/features.h:37:1: error: suggest braces around initialization of subobject [-Werror,-Wmissing-braces]
drivers/misc/mediatek/task_turbo/features.h:42:1: error: suggest braces around initialization of subobject [-Werror,-Wmissing-braces]
drivers/misc/mediatek/task_turbo/features.h:47:1: error: suggest braces around initialization of subobject [-Werror,-Wmissing-braces]
drivers/misc/mediatek/task_turbo/features.h:42:1: error: suggest braces around initialization of subobject [-Werror,-Wmissing-braces]
drivers/misc/mediatek/task_turbo/features.h:51:1: error: suggest braces around initialization of subobject [-Werror,-Wmissing-braces]
drivers/misc/mediatek/task_turbo/features.h:52:1: error: suggest braces around initialization of subobject [-Werror,-Wmissing-braces]
drivers/misc/mediatek/task_turbo/features.h:51:1: error: suggest braces around initialization of subobject [-Werror,-Wmissing-braces]
drivers/misc/mediatek/task_turbo/features.h:58:1: error: suggest braces around initialization of subobject [-Werror,-Wmissing-braces]

(cherry-picked from commit 16d21b2777a4890ee7cb93ac24bbb68f29dbe201)
Change-Id: I0eca80874c58d27a51fd00da013adafd61b2305f
CR-Id: ALPS05511922
Feature: [Module]Kernel Maintenance
Signed-off-by: Miles Chen <miles.chen@mediatek.com>