lockdep: fix proc_create() build breaks
Errors:
drivers/misc/mediatek/locking/lockdep_test.c:367:42: error: incompatible pointer types passing 'const struct file_operations *' to parameter of type 'const struct proc_ops *' [-Werror,-Wincompatible-pointer-types]

Change-Id: Ia2bd7451593ca526080ca0198a405053fccac58b
CR-Id: ALPS05442624
Feature: [Module]Kernel Maintenance
Signed-off-by: Miles Chen <miles.chen@mediatek.com>
(cherry picked from commit e7319f2cb8aab551fce804392ce411a1a46a9459)