log_store: fix prco_create() build breaks
Errors:
drivers/misc/mediatek/log_store/log_store.c:478:43: error: incompatible pointer types passing 'const struct file_operations *' to parameter of type 'const struct proc_ops *' [-Werror,-Wincompatible-pointer-types]

Change-Id: Idc4b270c5ed22cbf1157e2042d456ff7735a69ec
CR-Id: ALPS05442624
Feature: [Module]Kernel Maintenance
Signed-off-by: Miles Chen <miles.chen@mediatek.com>
(cherry picked from commit b192322e71a511772206d67571167f831235f1f2)