[ALPS04783226] vpu: fix build breaks when CONFIG_KASAN=y
Fix the following build breaks when CONFIG_KASAN=y with CC=gcc

drivers/misc/mediatek/apusys/vpu/mt6885/vpu_mem.c:316:24: error:
format ‘%d’ expects argument of type ‘int’, but argument 4 has
type ‘const char *’ [-Werror=format=]
drivers/misc/mediatek/apusys/vpu/mt6885/vpu_mem.c:316:24: error:
format ‘%s’ expects a matching ‘char *’ argument [-Werror=format=]

MTK-Commit-Id: f8845c35d51ca5dfdc98545602ab985e6f1b113d

Change-Id: If95217f8ecf926721be6c59ffbf913fdd337ce49
CR-Id: ALPS04783226
Signed-off-by: Miles Chen <miles.chen@mediatek.com>
Feature: VPU Platform