drivers: thermal: qmi_sensor: Fix compiler warning
 drivers/thermal/qcom/qmi_sensors.c: In function 'qmi_register_sensor_device':
 ./include/linux/kern_levels.h:5:18: error:
   format '%ld' expects argument of type 'long int', but argument 5 has type 'int' [-Werror=format=]

Change-Id: Ic0dedbad7596d06630010f084d965a30d92490ab
Signed-off-by: Jordan Crouse <jcrouse@codeaurora.org>