sched: fix non-void function does not return a value build breaks
Errors:
drivers/misc/mediatek/sched/scheduler.c:259:1: error: non-void function does not return a value in all control paths [-Werror,-Wreturn-type]

Change-Id: I0a9936f4221a466072bbfc1386641b0c9ce6ca17
CR-Id: ALPS05431666
Feature: [Module]Kernel Maintenance
Signed-off-by: Miles Chen <miles.chen@mediatek.com>
(cherry picked from commit f9aa50ff57564ba3b026ba039fb63d7768d696cc)