blocktag: fix bi_disk build breaks
Errors:
/mfs/mtkslt0480/mtk04267/CAS_REAL/alps-dev-r0.bsp-common-kernel-5.4--2021_03_10_23_00-6873/merged/kernel-mainline/drivers/misc/mediatek/blocktag/blocktag-core.c:192:19: error: no member named 'bi_disk' in 'struct bio'

Change-Id: I8075efc75de74bd6a03563a01fb90056e02b6800
Signed-off-by: Miles Chen <miles.chen@mediatek.com>
Feature: [Module]Kernel Maintenance
CR-Id: ALPS05625693