typec: mux: fix incompatible conversion build breaks
Errors:
drivers/misc/mediatek/typec/mux/mux_switch.c:143:33: error: incompatible integer to pointer conversion passing 'u32' (aka 'unsigned int') to parameter of type 'struct typec_mux_state *' [-Werror,-Wint-conversion]

Change-Id: Ib7bc663006bddf35f6bf4c30fd39f9e803a5e217
CR-Id: ALPS05511922
Feature: [Module]Kernel Maintenance
Signed-off-by: Miles Chen <miles.chen@mediatek.com>
(cherry picked from commit f7ec7f9bfaf0f4eb78b6e5203f09b1b3ea7a16a7)