scsi: ufs-mediatek: fix proc_create() and lrb_in_use build breaks
Error :
drivers/scsi/ufs/ufs-mediatek-dbg.c:77:14: error: no member named 'lrb_in_use' in 'struct ufs_hba'
drivers/scsi/ufs/ufs-mediatek-dbg.c:77:14: error: no member named 'lrb_in_use' in 'struct ufs_hba'
drivers/scsi/ufs/ufs-mediatek-dbg.c:77:14: error: no member named 'lrb_in_use' in 'struct ufs_hba'
drivers/scsi/ufs/ufs-mediatek-dbg.c:667:10: error: incompatible pointer types passing 'const struct file_operations *' to parameter of type 'const struct proc_ops *' [-Werror,-Wincompatible-pointer-types]

Feature: [Module]Kernel Maintenance
Change-Id: I3b5e110695671c1b15e5450dee1ca45142bad25c
CR-Id: ALPS05363693
Signed-off-by: Miles Chen <miles.chen@mediatek.com>