sspm: fix allmodconfig build breaks
fix sspm related allmodconfig build breaks

build command:
ARCH=arm64 make mrproper allmodconfig all

Errors:
drivers/misc/mediatek/sspm/v2/sspm_reservedmem_define.h:7:10: error: 'sspm_reservedmem.h' file not found with <angled> include; use "quotes" instead
drivers/misc/mediatek/sspm/v2/sspm_reservedmem_define.h:7:10: error: 'sspm_reservedmem.h' file not found with <angled> include; use "quotes" instead
drivers/misc/mediatek/sspm/v2/sspm_reservedmem_define.h:7:10: error: 'sspm_reservedmem.h' file not found with <angled> include; use "quotes" instead

Change-Id: I4be8039d557467de1c6c0430b93834ec1a7baf33
Cc: Anmin Hsu <anmin.hsu@mediatek.com>
Signed-off-by: Miles Chen <miles.chen@mediatek.com>
Feature: Kernel SI Operation
CR-Id: ALPS05903624