cmdq: fix unused variable build breaks
Errors:
drivers/misc/mediatek/mdp/cmdq_helper_ext.c:4445:6: error: unused variable 'ret'

(cherry-picked from commit cca6499a7611234eed34e1e952679e690edf4497)
Change-Id: I8169750d6072032c345e682c2ad912d7f747add4
CR-Id: ALPS05511922
Feature: [Module]Kernel Maintenance
Signed-off-by: Miles Chen <miles.chen@mediatek.com>