soc: qcom: Fix build error
Fix below compilation error due to unused function

llcc-qcom.h:240:12: error: unused function
 '\''llcc_configure_staling_mode'\'' [-Werror,-Wunused-function].

Change-Id: I29e9db0bf15b94252fea8a71b3ffe6e279f0bf74
Signed-off-by: Srinivasarao Pathipati <quic_c_spathi@quicinc.com>