mddp: fix struct timespec build breaks
Errors:
drivers/misc/mediatek/mddp/ctrl/mddp_dev.c:706:30: error: variable has incomplete type 'struct timespec'
drivers/misc/mediatek/mddp/ctrl/mddp_dev.c:728:2: error: implicit declaration of function 'getnstimeofday' [-Werror,-Wimplicit-function-declaration]
drivers/misc/mediatek/mddp/ctrl/mddp_dev.c:729:2: error: implicit declaration of function 'rtc_time_to_tm' [-Werror,-Wimplicit-function-declaration]

Change-Id: I77af9dd8a4063076d2445c549b5424f4f7869e55
CR-Id: ALPS05408933
Feature: Others
Signed-off-by: Kuan-Ying Lee <Kuan-Ying.Lee@mediatek.com>