cmdq: fix build breaks caused by mismerge
Error:
drivers/mailbox/mtk-cmdq-mailbox.c:1604:7: error: implicit declaration of function
'cmdq_thread_is_in_wfe' [-Werror,-Wimplicit-function-declaration]
drivers/mailbox/mtk-cmdq-mailbox.c:1609:20: error: no member named 'async_cb' in 'struct cmdq_pkt'
drivers/mailbox/mtk-cmdq-mailbox.c:1611:9: error: no member named 'sta' in 'struct cmdq_cb_data'
drivers/mailbox/mtk-cmdq-mailbox.c:1611:15: error: use of undeclared identifier 'CMDQ_CB_ERROR'

Signed-off-by: Miles Chen <miles.chen@mediatek.com>
Change-Id: I578c5ea7a4a3742a0ce2214dafdd1ba1fa51eafd
CR-Id: ALPS05298037
Feature: [Module]Kernel Maintenance
Signed-off-by: Miles Chen <miles.chen@mediatek.com>
Source_Git_Sha: 69b7cec24692ddc5d17cf3d47527cc55585e6877