msm: adsprpc: Remove warning and fix logged kernel memory address
I came in to fix these warnings:

drivers/char/adsprpc.c: In function 'dma_alloc_memory':
drivers/char/adsprpc.c:632:36: warning: cast from pointer to integer of different size [-Wpointer-to-int-cast]

drivers/char/adsprpc.c: In function 'fastrpc_buf_alloc':
drivers/char/adsprpc.c:976:35: error: cast from pointer to integer of different size [-Werror=pointer-to-int-cast]

But then I discovered that this was leaking a kernel memory address by
accident so fix the warning by changing the printk format to %pK in two spots.

Fixes: d5c40c85d4b9 ("msm: adsprpc: add fastrpc driver files")
Change-Id: Ic0dedbad8ffbeaa28e56f1f2f968747cb82b518e
Signed-off-by: Jordan Crouse <jcrouse@codeaurora.org>