bvt: remove CONFIG_KASAN from bvt
This change removes CONFIG_KASAN from bvt test. The reason is
when CONFIG_KASAN=y and CC=clang, the frame size will be increased
and causes the following errors:

kernel-4.19/fs/quota/quota.c:837:5: error: stack frame size of
3456 bytes in function 'kernel_quotactl'

Change-Id: I3b732d3ef67325a2ee0c5b5f429a8aaee3aeb1ce
Signed-off-by: Walter <walter-zh.wu@mediatek.com>
CR-Id: ALPS04739066