apusys: fix ioremap_nocache build breaks
Error:
drivers/misc/mediatek/apusys/debug/1.0/common/debug_drv.c:180:12: error: implicit declaration of function 'ioremap_nocache' [-Werror,-Wimplicit-function-declaration]

Signed-off-by: Miles Chen <miles.chen@mediatek.com>
Change-Id: I54bef364d4db359df391331545f4c9d3ea965925
CR-Id: ALPS05298037
Feature:[Module] APUSYS
Signed-off-by: Miles Chen <miles.chen@mediatek.com>
Source_Git_Sha: 17449860e363023752f095e623585aaafd8323c5