eemgpu: fix unused variable build breaks
Errors:
drivers/misc/mediatek/eemgpu/mtk_eemgpu.c:124:22: error: unused variable 'j' [-Werror,-Wunused-variable]
drivers/misc/mediatek/eemgpu/mtk_eemgpu.c:272:10: error: enumeration values 'THERMAL_BANK5' and 'THERMAL_BANK_NUM' not handled in switch [-Werror,-Wswitch]
drivers/misc/mediatek/eemgpu/mtk_eemgpu.c:1420:3: error: add explicit braces to avoid dangling else [-Werror,-Wdangling-else]
drivers/misc/mediatek/eemgpu/mtk_eemgpu.c:1791:7: error: unused variable 'val' [-Werror,-Wunused-variable]
drivers/misc/mediatek/eemgpu/mtk_eemgpu.c:2397:55: error: unused variable 'ret_1' [-Werror,-Wunused-variable]
drivers/misc/mediatek/eemgpu/mtk_eemgpu.c:2397:6: error: unused variable 'temperature_1' [-Werror,-Wunused-variable]
drivers/misc/mediatek/eemgpu/mtk_eemgpu.c:2396:30: error: unused variable 'zone_0' [-Werror,-Wunused-variable]
drivers/misc/mediatek/eemgpu/mtk_eemgpu.c:2397:25: error: unused variable 'temperature_0' [-Werror,-Wunused-variable]
drivers/misc/mediatek/eemgpu/mtk_eemgpu.c:2396:39: error: unused variable 'zone_1' [-Werror,-Wunused-variable]
drivers/misc/mediatek/eemgpu/mtk_eemgpu.c:2397:44: error: unused variable 'ret_0' [-Werror,-Wunused-variable]

(cherry-picked from commit 44cb3dc2df58fa6522f15f15f450f9991e30725a)
Change-Id: I751ee5b6ad3caaf24bba85322bfd9ffd35fc6881
CR-Id: ALPS05511922
Feature: [Module]Kernel Maintenance
Signed-off-by: Miles Chen <miles.chen@mediatek.com>