apusys: reviser: fix debugfs and ioremap_nocache build breaks
Error:
/mfs/mtkslt0480/mtk04267/CAS_REAL/alps-dev-r0_bsp-common-kernel-5_4--2020_08_26_00_00/merged/kernel-5.4/drivers/misc/mediatek/apusys/reviser/1.5/common/reviser_dbg.c:592:28: error: assigning to 'struct dentry *' from incompatible type 'void'
/mfs/mtkslt0480/mtk04267/CAS_REAL/alps-dev-r0_bsp-common-kernel-5_4--2020_08_26_00_00/merged/kernel-5.4/drivers/misc/mediatek/apusys/reviser/1.5/common/reviser_dbg.c:622:27: error: assigning to 'struct dentry *' from incompatible type 'void'
/mfs/mtkslt0480/mtk04267/CAS_REAL/alps-dev-r0_bsp-common-kernel-5_4--2020_08_26_00_00/merged/kernel-5.4/drivers/misc/mediatek/apusys/reviser/1.5/common/reviser_dbg.c:641:28: error: assigning to 'struct dentry *' from incompatible type 'void'
/mfs/mtkslt0480/mtk04267/CAS_REAL/alps-dev-r0_bsp-common-kernel-5_4--2020_08_26_00_00/merged/kernel-5.4/drivers/misc/mediatek/apusys/reviser/1.5/common/reviser_dbg.c:651:27: error: assigning to 'struct dentry *' from incompatible type 'void'
/mfs/mtkslt0480/mtk04267/CAS_REAL/alps-dev-r0_bsp-common-kernel-5_4--2020_08_26_00_00/merged/kernel-5.4/drivers/misc/mediatek/apusys/reviser/1.5/common/reviser_dbg.c:672:18: error: assigning to 'struct dentry *' from incompatible type 'void'
/mfs/mtkslt0480/mtk04267/CAS_REAL/alps-dev-r0_bsp-common-kernel-5_4--2020_08_26_00_00/merged/kernel-5.4/drivers/misc/mediatek/apusys/reviser/1.5/common/reviser_drv.c:191:9: error: implicit declaration of function 'ioremap_nocache' [-Werror,-Wimplicit-function-declaration]

Signed-off-by: Miles Chen <miles.chen@mediatek.com>
Change-Id: I8df3936e61fea0aa4934692a865300a381e95068
CR-Id: ALPS05298037
Feature:[Module] APUSYS
Signed-off-by: Miles Chen <miles.chen@mediatek.com>
Source_Git_Sha: d8bb11e080f9ac4a60cc66edf2709ac01470edb5