sched: fix proc_create() and nr_cap_states build breaks
Error:
drivers/misc/mediatek/sched/scheduler.c:35:26: error: no member named 'nr_cap_states' in 'struct em_perf_domain'; did you mean 'nr_perf_states'?
drivers/misc/mediatek/sched/scheduler.c:145:17: error: no member named 'nr_cap_states' in 'struct em_perf_domain'; did you mean 'nr_perf_states'?
drivers/misc/mediatek/sched/scheduler.c:230:52: error: incompatible pointer types passing 'const struct file_operations *' to parameter of type 'const struct proc_ops *' [-Werror,-Wincompatible-pointer-types]

Change-Id: Ief36e1186a213b0654108e507e748de65a24dcc0
CR-Id: ALPS05394556
Feature: [Module]Kernel Maintenance
Signed-off-by: Miles Chen <miles.chen@mediatek.com>