aee: build error for kwdt_regist_irq_info
ERROR: "kwdt_regist_irq_info" [drivers/misc/mediatek/mtprof/
irq_monitor.ko] undefined!

fix: check if CONFIG_MTK_AEE_HANGDET is enabled before use this API.

(cherry-picked from commit 6d4b983451be6678f1894d5621d651727fff6741)
Signed-off-by: zhiyong.wang <zhiyong.wang@mediatek.com>
Change-Id: I538e0ceeea1267e6e9de0455ed057048fed28068
CR-Id: ALPS05636910
Feature: Android Exception Engine(AEE)
Signed-off-by: Miles Chen <miles.chen@mediatek.com>