msm: kgsl: Check the return value of regulator_enable
Fix the following compiler error:

 drivers/gpu/msm/kgsl_iommu.c:845:3: error: ignoring return value of
	‘regulator_enable’, declared with attribute warn_unused_result

Fixes: 1c6fcc54eca9 ("msm: kgsl: Enable the CX GSDC before accessing IOMMU registers")
Change-Id: Ic0dedbad7d68d3dfb2344525d79d9d563e28d6d6
Signed-off-by: Jordan Crouse <jcrouse@codeaurora.org>