ccci: fix timespec, proc, and many build breaks
Error:
drivers/misc/mediatek/ccci_util/ccci_private_log.c:789:56: error: incompatible pointer types passing 'const struct file_operations *' to parameter of type 'const struct proc_ops *' [-Werror,-Wincompatible-pointer-types]
drivers/misc/mediatek/ccci_util/ccci_private_log.c:1023:17: error: variable has incomplete type 'struct timeval'
drivers/misc/mediatek/ccci_util/ccci_private_log.c:1046:2: error: implicit declaration of function 'rtc_time_to_tm' [-Werror,-Wimplicit-function-declaration]
drivers/misc/mediatek/ccci_util/ccci_private_log.c:1144:54: error: incompatible pointer types passing 'const struct file_operations *' to parameter of type 'const struct proc_ops *' [-Werror,-Wincompatible-pointer-types]
drivers/misc/mediatek/ccci_util/ccci_util_broadcast.c:30:17: error: field has incomplete type 'struct timeval'
drivers/misc/mediatek/ccci_util/ccci_util_broadcast.c:38:24: error: field has incomplete type 'struct compat_timeval'
drivers/misc/mediatek/ccci_util/ccci_util_broadcast.c:64:17: error: field has incomplete type 'struct timeval'
drivers/misc/mediatek/ccci_util/ccci_util_broadcast.c:174:17: error: variable has incomplete type 'struct timeval'
drivers/misc/mediatek/ccci_util/ccci_util_lib_load_img.c:1058:11: error: implicit declaration of function 'ioremap_nocache' [-Werror,-Wimplicit-function-declaration]
drivers/misc/mediatek/ccci_util/ccci_util_lib_load_img.c:1080:11: error: implicit declaration of function 'ioremap_nocache' [-Werror,-Wimplicit-function-declaration]
drivers/misc/mediatek/ccci_util/ccci_util_lib_load_img.c:1095:11: error: implicit declaration of function 'ioremap_nocache' [-Werror,-Wimplicit-function-declaration]
drivers/misc/mediatek/ccci_util/ccci_util_sib.c:115:54: error: incompatible pointer types passing 'const struct file_operations *' to parameter of type 'const struct proc_ops *' [-Werror,-Wincompatible-pointer-types]
drivers/misc/mediatek/ccmni/ccmni.c:914:20: error: incompatible pointer types initializing 'void (*)(struct net_device *, unsigned int)' with an expression of type 'void (struct net_device *)' [-Werror,-Wincompatible-pointer-types]
drivers/misc/mediatek/eccci/hif/ccci_hif_cldma.h:423:10: error: expected expression
drivers/misc/mediatek/eccci/hif/ccci_hif_ccif.h:246:10: error: expected expression
drivers/misc/mediatek/eccci/hif/ccci_hif_cldma.h:423:10: error: expected expression
drivers/misc/mediatek/eccci/hif/ccci_hif_cldma.h:423:10: error: expected expression
drivers/misc/mediatek/eccci/port/port_proxy.c:1837:57: error: incompatible pointer types passing 'const struct file_operations *' to parameter of type 'const struct proc_ops *' [-Werror,-Wincompatible-pointer-types]
drivers/misc/mediatek/eccci/fsm/mdee_dumper_v1.c:128:17: error: variable has incomplete type 'struct timeval'
drivers/misc/mediatek/eccci/fsm/mdee_dumper_v1.c:129:17: error: variable has incomplete type 'struct timeval'
drivers/misc/mediatek/eccci/fsm/mdee_dumper_v1.c:139:2: error: implicit declaration of function 'rtc_time_to_tm' [-Werror,-Wimplicit-function-declaration]
drivers/misc/mediatek/eccci/fsm/mdee_dumper_v2.c:248:17: error: variable has incomplete type 'struct timeval'
drivers/misc/mediatek/eccci/fsm/mdee_dumper_v2.c:249:17: error: variable has incomplete type 'struct timeval'
drivers/misc/mediatek/eccci/fsm/mdee_dumper_v2.c:277:2: error: implicit declaration of function 'rtc_time_to_tm' [-Werror,-Wimplicit-function-declaration]
drivers/misc/mediatek/eccci/mt6873/ap_md_reg_dump.c:30:14: error: implicit declaration of function 'ioremap_nocache' [-Werror,-Wimplicit-function-declaration]
drivers/misc/mediatek/eccci/hif/ccci_hif_ccif.h:246:10: error: expected expression
drivers/misc/mediatek/eccci/hif/ccci_hif_ccif.c:1741:9: error: expected expression
drivers/misc/mediatek/eccci/mt6873/md_sys1_platform.c:193:4: error: implicit declaration of function 'ioremap_nocache' [-Werror,-Wimplicit-function-declaration]
drivers/misc/mediatek/eccci/hif/ccci_hif_ccif.c:1974:3: error: implicit declaration of function 'ioremap_nocache' [-Werror,-Wimplicit-function-declaration]
drivers/misc/mediatek/eccci/mt6873/md_sys1_platform.c:356:3: error: implicit declaration of function 'ioremap_nocache' [-Werror,-Wimplicit-function-declaration]
drivers/misc/mediatek/eccci/mt6873/md_sys1_platform.c:612:17: error: implicit declaration of function 'ioremap_nocache' [-Werror,-Wimplicit-function-declaration]
drivers/misc/mediatek/eccci/hif/ccci_hif_dpmaif.c:3738:9: error: expected expression

Signed-off-by: Miles Chen <miles.chen@mediatek.com>
Change-Id: Ic5c1a56d14f8817f08a10d98a0a8f328dc86d6ee
CR-Id: ALPS05298037
Feature: [Module]Kernel Maintenance
Signed-off-by: Miles Chen <miles.chen@mediatek.com>