memory: mediatek: Fix the error on casting void pointer to int
When using clang with options '-Werror,-Wvoid-pointer-to-int-cast',
there is the compile error.
	error: cast to smaller integer type 'int' from 'const void *'

Use the C99 uintptr_t to cast first.

(cherry-picked from commit f5311129753dbb52a2b9e8e975293a30217451c9)
Signed-off-by: cc.hwang <cc.hwang@mediatek.com>
Change-Id: I5a7d79018762eab92a5437c194031b6dd19a9be9
CR-Id: ALPS05539426
Feature: External Memory Interface(emi)
Signed-off-by: Kuan-Ying Lee <Kuan-Ying.Lee@mediatek.com>