apusys: fix min_freq build breaks
Errors:
drivers/misc/mediatek/apusys/power/2.5/governor/gov-apusys.c:222:7: error: use of undeclared identifier 'DEVFREQ_GOV_INTERVAL'
drivers/misc/mediatek/apusys/power/2.5/governor/gov-apusys.c:223:3: error: implicit declaration of function 'devfreq_interval_update' [-Werror,-Wimplicit-function-declaration]
drivers/misc/mediatek/apusys/power/2.5/common/apu-of.c:171:4: error: implicit declaration of function 'ioremap_nocache' [-Werror,-Wimplicit-function-declaration]
drivers/misc/mediatek/apusys/power/2.5/common/apu-plat.c:258:63: error: too few arguments to function call, expected 3, have 2
drivers/misc/mediatek/apusys/power/2.5/common/apu-dbg.c:371:17: error: no member named 'max_freq' in 'struct devfreq'
drivers/misc/mediatek/apusys/power/2.5/common/apu-dbg.c:372:17: error: no member named 'min_freq' in 'struct devfreq'
drivers/misc/mediatek/apusys/power/2.5/common/apu-dbg.c:396:16: error: no member named 'max_freq' in 'struct devfreq'
drivers/misc/mediatek/apusys/power/2.5/common/apu-dbg.c:397:16: error: no member named 'min_freq' in 'struct devfreq'

Change-Id: Ia7299a195cd871d08131d313feb18b49635312b3
CR-Id: ALPS05489813
Feature: [Module]Kernel Maintenance
Signed-off-by: Miles Chen <miles.chen@mediatek.com>