fpsgo: fix proc_create() build breaks
Error:
drivers/misc/mediatek/performance/perf_ioctl/perf_ioctl.c:385:47: error: incompatible pointer types passing 'const struct file_operations *' to parameter of type 'const struct proc_ops *' [-Werror,-Wincompatible-pointer-types]
drivers/misc/mediatek/performance/perf_ioctl/perf_ioctl.c:394:47: error: incompatible pointer types passing 'const struct file_operations *' to parameter of type 'const struct proc_ops *' [-Werror,-Wincompatible-pointer-types]

Feature: [Module]Kernel Maintenance
Change-Id: Ie7e1523a111fc95c7530f4b009130442ac7e8d42
CR-Id: ALPS05298037
Signed-off-by: Miles Chen <miles.chen@mediatek.com>
Source_Git_Sha: 10edd5cc6cd098f72ed34d27b10476eccadfff29