soc: mediatek: fix MT8192_POWER_DOMAIN_ADSP not defined build breaks
Errors:
drivers/soc/mediatek/mtk-scpsys.c:1941:3: error: use of undeclared identifier 'MT8192_POWER_DOMAIN_ADSP'

Change-Id: I7d40c33331f4d6fb14eba5c35259bf97b2abd06e
Signed-off-by: Miles Chen <miles.chen@mediatek.com>
CR-Id: ALPS05568046
Feature: [Module]Kernel Maintenance