slbc: fix proc_create() build breaks
Error:
/drivers/misc/mediatek/slbc/slbc.c:1169:11: error: incompatible pointer types passing 'const struct file_operations *const' to parameter of type 'const struct proc_ops *' [-Werror,-Wincompatible-pointer-types]

Feature: [Module]Kernel Maintenance
Change-Id: Ib8f7c616c44c73e0764d9da856a3eb3b0672d093
CR-Id: ALPS05298037
Signed-off-by: Miles Chen <miles.chen@mediatek.com>
Source_Git_Sha: 44d5750700a4cb6d10e2c4b01ce8688e5aeb1285