power: smb5: fix uninitalized variable warning
 drivers/power/supply/qcom/smb5-lib.c: In function 'smblib_set_prop_pr_swap_in_progress':
 drivers/power/supply/qcom/smb5-lib.c:4978:15: error:
  'stat' may be used uninitialized in this function [-Werror=maybe-uninitialized]

Fixes: caceca44a0db ("power: smb5: Add snapshot of SMB5 driver and its dependencies")
Change-Id: Ic0dedbadb6100f7e050cac16c8de1ccda778842a
Signed-off-by: Jordan Crouse <jcrouse@codeaurora.org>