slbc: fix allmodconfig build breaks
fix slbc related allmodconfig build errors

build command:
ARCH=arm64 make mrproper allmodconfig all

Errors:
drivers/misc/mediatek/slbc/slbc.c:20:10: error: 'slbc.h' file not found with <angled> include; use "quotes" instead
drivers/misc/mediatek/slbc/slbc.h:9:10: error: 'slbc_ops.h' file not found with <angled> include; use "quotes" instead
drivers/misc/mediatek/slbc/slbc.c:27:10: error: 'mmsram.h' file not found with <angled> include; use "quotes" instead

Change-Id: I92e78e153e6e20da5c4d1ec6f56efee7e5648225
Cc: Morven-CF Yeh <morven-cf.yeh@mediatek.com>
Signed-off-by: Miles Chen <miles.chen@mediatek.com>
Feature: Kernel SI Operation
CR-Id: ALPS05903624