apusys: fix max_freq/min_freq build breaks
Errors:
drivers/misc/mediatek/apusys/power/2.5/common/apu-dbg.c:136:10: error: no member named 'max_freq' in 'struct devfreq'
drivers/misc/mediatek/apusys/power/2.5/common/apu-dbg.c:137:10: error: no member named 'min_freq' in 'struct devfreq'
drivers/misc/mediatek/apusys/power/2.5/common/apu-dbg.c:146:10: error: no member named 'max_freq' in 'struct devfreq'
drivers/misc/mediatek/apusys/power/2.5/common/apu-dbg.c:147:10: error: no member named 'min_freq' in 'struct devfreq'

Change-Id: I33b669d87344da89cae77ab7284ea8bc73240ca9
CR-Id: ALPS05502217
Feature: [Module]Kernel Maintenance
Signed-off-by: Miles Chen <miles.chen@mediatek.com>