aee: fix save_stack_trace_tsk build breaks
Errors:
drivers/misc/mediatek/aee/mrdump/mrdump_control.c:93:41: error: expected expression
drivers/misc/mediatek/aee/aed/aed-main.c:1982:21: error: variable has incomplete type 'struct stack_trace'
drivers/misc/mediatek/aee/aed/aed-main.c:1992:2: error: implicit declaration of function 'save_stack_trace_tsk' [-Werror,-Wimplicit-function-declaration]
drivers/misc/mediatek/aee/mrdump/mrdump_helper.c:54:39: error: expected expression
drivers/misc/mediatek/aee/mrdump/mrdump_helper.c:100:31: error: expected expression
drivers/misc/mediatek/aee/mrdump/mrdump_mini.c:559:21: error: variable has incomplete type 'struct stack_trace'
drivers/misc/mediatek/aee/mrdump/mrdump_mini.c:625:2: error: implicit declaration of function 'save_stack_trace_tsk' [-Werror,-Wimplicit-function-declaration]

Change-Id: Ia90df1ef4951d92c9288912c238aed36e0d485f7
CR-Id: ALPS05431666
Feature: [Module]Kernel Maintenance
Signed-off-by: Miles Chen <miles.chen@mediatek.com>
(cherry picked from commit eac6216f20e921ac948cc33a343a2c608012449a)