disp: fix drm_panel_attach not found build breaks
Error:
drivers/gpu/drm/panel/panel-truly-td4330-vdo.c:827:6: error: assigning to 'int' from incompatible type 'void'
drivers/gpu/drm/mediatek/mediatek_v2/mtk_dsi.c:1916:9: error: implicit declaration of function 'drm_panel_attach' [-Werror,-Wimplicit-function-declaration]

Change-Id: I4d9df5e5cdf3340460e1d2d39b5c880443cdd90c
CR-Id: ALPS05431666
Feature: [Module]Kernel Maintenance
Signed-off-by: Miles Chen <miles.chen@mediatek.com>