disp: fix gem interface build breaks
Errors:
drivers/gpu/drm/mediatek/mediatek_v2/mtk_drm_drv.c:2419:3: error: field designator 'gem_free_object_unlocked' does not refer to any field in type 'struct drm_driver'
drivers/gpu/drm/mediatek/mediatek_v2/mtk_drm_drv.c:2420:3: error: field designator 'gem_vm_ops' does not refer to any field in type 'struct drm_driver'
drivers/gpu/drm/mediatek/mediatek_v2/mtk_drm_drv.c:2427:3: error: field designator 'gem_prime_export' does not refer to any field in type 'struct drm_driver'; did you mean 'gem_prime_import'?
drivers/gpu/drm/mediatek/mediatek_v2/mtk_drm_drv.c:2427:22: error: incompatible pointer types initializing 'struct drm_gem_object *(*)(struct drm_device *, struct dma_buf *)' with an expression of type 'struct dma_buf *(struct drm_gem_object *, int)' [-Werror,-Wincompatible-pointer-types]
drivers/gpu/drm/mediatek/mediatek_v2/mtk_drm_drv.c:2429:3: error: field designator 'gem_prime_get_sg_table' does not refer to any field in type 'struct drm_driver'; did you mean 'gem_prime_import_sg_table'?
drivers/gpu/drm/mediatek/mediatek_v2/mtk_drm_drv.c:2429:28: error: incompatible pointer types initializing 'struct drm_gem_object *(*)(struct drm_device *, struct dma_buf_attachment *, struct sg_table *)' with an expression of type 'struct sg_table *(struct drm_gem_object *)' [-Werror,-Wincompatible-pointer-types]
drivers/gpu/drm/mediatek/mediatek_v2/mtk_drm_crtc.c:4698:19: error: incompatible pointer types initializing 'void (*)(struct drm_crtc *, struct drm_atomic_state *)' with an expression of type 'void (struct drm_crtc *, struct drm_crtc_state *)' [-Werror,-Wincompatible-pointer-types]
drivers/gpu/drm/mediatek/mediatek_v2/mtk_drm_crtc.c:4700:18: error: incompatible pointer types initializing 'void (*)(struct drm_crtc *, struct drm_atomic_state *)' with an expression of type 'void (struct drm_crtc *, struct drm_crtc_state *)' [-Werror,-Wincompatible-pointer-types]
drivers/gpu/drm/mediatek/mediatek_v2/mtk_drm_crtc.c:4701:18: error: incompatible pointer types initializing 'void (*)(struct drm_crtc *, struct drm_atomic_state *)' with an expression of type 'void (struct drm_crtc *, struct drm_crtc_state *)' [-Werror,-Wincompatible-pointer-types]

Change-Id: I744e1bd483a7cc73fdeb84c99685a5da82bc6318
Signed-off-by: Miles Chen <miles.chen@mediatek.com>
CR-Id: ALPS05568046
Feature: [Module]Kernel Maintenance