camsys: fix unused variable build breaks
Errors:
drivers/media/platform/mtk-isp/isp_60s/cam/mtk_cam-raw.c:866:7: error: unused variable 'res' [-Werror,-Wunused-variable]
drivers/media/platform/mtk-isp/isp_60s/cam/mtk_cam-raw.c:977:5: error: 'MTK_CAM_DUMP_WORK_INT_CONTEXT' is not defined, evaluates to 0 [-Werror,-Wundef]
drivers/media/platform/mtk-isp/isp_60s/cam/mtk_cam-raw.c:1317:7: error: GCC does not allow variable declarations in for loop initializers before C99 [-Werror,-Wgcc-compat]
drivers/media/platform/mtk-isp/isp_60s/cam/mtk_cam-raw.c:1320:8: error: GCC does not allow variable declarations in for loop initializers before C99 [-Werror,-Wgcc-compat]
drivers/media/platform/mtk-isp/isp_60s/cam/mtk_cam-raw.c:1350:8: error: GCC does not allow variable declarations in for loop initializers before C99 [-Werror,-Wgcc-compat]
drivers/media/platform/mtk-isp/isp_60s/cam/mtk_cam-raw.c:1359:8: error: GCC does not allow variable declarations in for loop initializers before C99 [-Werror,-Wgcc-compat]
drivers/media/platform/mtk-isp/isp_60s/cam/mtk_cam-video.c:403:6: error: unused variable 'width' [-Werror,-Wunused-variable]
drivers/media/platform/mtk-isp/isp_60s/cam/mtk_cam-ctrl.c:422:6: error: unused variable 'time_after_sof' [-Werror,-Wunused-variable]
drivers/media/platform/mtk-isp/isp_60s/cam/mtk_cam-ctrl.c:420:25: error: unused variable 'cam' [-Werror,-Wunused-variable]

(cherry-picked from commit 1ceb6db6bae8d2c86c791583ba611610f08c768f)
Change-Id: I86f11509b67d19211836a6558acd1e921fe77b6f
CR-Id: ALPS05511922
Feature: [Module]Kernel Maintenance
Signed-off-by: Miles Chen <miles.chen@mediatek.com>