scsi: ufs-mediatek: fix compl_xfer_req build breaks
Fix build breaks after the revert of "FROMLIST: ufs: introduce
a callback to get info of command completion"

Errors:
drivers/scsi/ufs/ufs-mediatek.c:1104:3: error: field designator
'compl_xfer_req' does not refer to any field in type
'const struct ufs_hba_variant_ops'

Change-Id: Ia6d7812df372bc8a14c3e9af288cf10fbff45812
Signed-off-by: Miles Chen <miles.chen@mediatek.com>
Feature: [Module]Kernel Maintenance
CR-Id: ALPS05653242