apusys: fix compat_ptr, ioremap_nocache build breaks
Error:
drivers/misc/mediatek/apusys/mdla/platform/v2_0/mdla_v2_0.c:358:9: error: implicit declaration of function 'ioremap_nocache' [-Werror,-Wimplicit-function-declaration]
drivers/misc/mediatek/apusys/mdla/platform/v1_5/mdla_v1_5.c:323:9: error: implicit declaration of function 'ioremap_nocache' [-Werror,-Wimplicit-function-declaration]
drivers/misc/mediatek/apusys/mdla/platform/v1_7/mdla_v1_7.c:332:9: error: implicit declaration of function 'ioremap_nocache' [-Werror,-Wimplicit-function-declaration]
drivers/misc/mediatek/apusys/mdla/platform/v1_0/mdla_v1_0.c:316:9: error: implicit declaration of function 'ioremap_nocache' [-Werror,-Wimplicit-function-declaration]
drivers/misc/mediatek/apusys/mdla/common/mdla_ioctl.c:126:47: error: implicit declaration of function 'compat_ptr' [-Werror,-Wimplicit-function-declaration]

Signed-off-by: Miles Chen <miles.chen@mediatek.com>
Change-Id: I7a7450be571b4396caa5b17fcb2d77d1f46f319c
CR-Id: ALPS05298037
Feature: [Module]Kernel Maintenance
Signed-off-by: Miles Chen <miles.chen@mediatek.com>