touch: remove the use of irq_to_desc
irq_to_desc is restrict exported by commit 64a1b95bb9fe3ec76e1a2cd803eff06389341ae4
("genirq: Restrict export of irq_to_desc()").

Remove the use of irq_to_desc().

Error:
ERROR: modpost: "irq_to_desc" [drivers/input/touchscreen/GT9896S/gt9896s.ko] undefined!
ERROR: modpost: "irq_to_desc" [drivers/input/touchscreen/GT9886/gt9886.ko] undefined!

Change-Id: Ieea21a0b92ac0cda5d92f254489cba5cb3ed216c
Signed-off-by: Miles Chen <miles.chen@mediatek.com>
Feature: [Module]Kernel Maintenance
CR-Id: ALPS05672993