hang: fix save_stack_trace_tsk not found build breaks
Errors:
drivers/misc/mediatek/monitor_hang/monitor_hang.c:395:21: error: variable has incomplete type 'struct stack_trace'
drivers/misc/mediatek/monitor_hang/monitor_hang.c:404:2: error: implicit declaration of function 'save_stack_trace_tsk' [-Werror,-Wimplicit-function-declaration]

Change-Id: I6caca9f34f9ff7df5fbf99587be3727aa7e1775b
CR-Id: ALPS05431666
Feature: [Module]Kernel Maintenance
Signed-off-by: Miles Chen <miles.chen@mediatek.com>