iommu/mediatek: fix has_bclk build breaks
Errors:
drivers/iommu/mtk_iommu.c:952:24: error: no member named 'has_bclk' in 'struct mtk_iommu_plat_data'
drivers/iommu/mtk_iommu.c:990:24: error: no member named 'has_bclk' in 'struct mtk_iommu_plat_data'

Change-Id: I471103585f5552d976b83cd20641a7cd00a8e452
CR-Id: ALPS05377375
Feature: [Module]Kernel Maintenance
Signed-off-by: Miles Chen <miles.chen@mediatek.com>