[ALPS04781108] fscrypt: hie: fix build error
Fix build error:
multiple definition of fscrypt_crypt_info_act.

MTK-Commit-Id: 9679d159ee40829b179dd20370170e6b0a943682

Change-Id: I59331b753380d4436e32a45c81544918bb977c8d
Signed-off-by: Stanley Chu <stanley.chu@mediatek.com>
CR-Id: ALPS04781108
Feature: Multi-Storage
(cherry picked from commit f3c3270f39fc7a85848d866b322e2db51a004440)