power: qpnp-fg-gen4: Fix missing printk argument
Fix a missing printk argument:

 drivers/power/supply/qcom/qpnp-fg-gen4.c:1030:3: note: in expansion of macro 'pr_err'
 ./include/linux/kern_levels.h:5:18: error:
   format '%d' expects a matching 'int' argument [-Werror=format=]

Fixes: 53f2a2062b69 ("power: qpnp-fg-gen4: Add snapshot of driver and its dependencies")
Change-Id: Ic0dedbadb98e7e6daacfd78cb17e931dbc4281db
Signed-off-by: Jordan Crouse <jcrouse@codeaurora.org>