msdc: fix MMC_CAP_ERASE build breaks
Errors:
drivers/mmc/host/mtk-mmc.c:2094:15: error: use of undeclared identifier 'MMC_CAP_ERASE'

Change-Id: I41b174e84e814f990bb46f468b575bbfa63b4cca
CR-Id: ALPS05619749
Feature: [Module]Kernel Maintenance
Signed-off-by: Miles Chen <miles.chen@mediatek.com>