Charger: fix POWER_SUPPLY_TYPE_USB_FLOAT build breaks
Fix build breaks after the revert of:
"FROMLIST: power: supply: core: add quick charge type property"
"FROMLIST: power: supply: core: add wireless charger adapter type property"
"FROMLIST: power: supply: core: add wireless signal strength property"
"FROMLIST: power: supply: core: property to control reverse charge"
"FROMLIST: ufs: introduce a callback to get info of command completion"

Errors:
drivers/power/supply/mtk_charger.c:1569:7: error: use of undeclared
identifier 'POWER_SUPPLY_TYPE_USB_FLOAT'; did you mean 'POWER_SUPPLY_TYPE_USB_ACA'?
drivers/power/supply/mtk_charger_intf.c:279:19: error: use of undeclared
identifier 'POWER_SUPPLY_TYPE_USB_FLOAT'; did you mean 'POWER_SUPPLY_TYPE_USB_ACA'?
drivers/power/supply/mtk_basic_charger.c:190:31: error: use of undeclared
identifier 'POWER_SUPPLY_TYPE_USB_FLOAT'; did you mean 'POWER_SUPPLY_TYPE_USB_ACA'?

Change-Id: I399a388136ff73635826241673ce91e0dec3908f
Signed-off-by: Miles Chen <miles.chen@mediatek.com>
Feature: [Module]Kernel Maintenance
CR-Id: ALPS05653242