blocktag: fix proc_create() build breaks
Error:
drivers/misc/mediatek/blocktag/blocktag-core.c:1020:23: error: incompatible pointer types passing 'const struct file_operations *' to parameter of type 'const struct proc_ops *' [-Werror,-Wincompatible-pointer-types]
drivers/misc/mediatek/blocktag/blocktag-core.c:1027:23: error: incompatible pointer types passing 'const struct file_operations *' to parameter of type 'const struct proc_ops *' [-Werror,-Wincompatible-pointer-types]
drivers/misc/mediatek/blocktag/blocktag-core.c:1161:10: error: incompatible pointer types passing 'const struct file_operations *' to parameter of type 'const struct proc_ops *' [-Werror,-Wincompatible-pointer-types]

Change-Id: I70a77df1b8a41d3c17bdce2236e8ce7db5eacb1f
CR-Id: ALPS05387457
Feature: [Module]Kernel Maintenance
Signed-off-by: Miles Chen <miles.chen@mediatek.com>