soc: mediatek: devapc: fix iounmap build break
Error:
include/asm-generic/io.h:1015:2: error: implicit declaration of function 'iounmap' [-Werror,-Wimplicit-function-declaration]

Change-Id: I8779de6387ef7c7a9c2c70d936beb2d8a050cb26
CR-Id: ALPS05431666
Feature: [Module]Kernel Maintenance
Signed-off-by: Miles Chen <miles.chen@mediatek.com>
(cherry picked from commit 2b63468cf1ad4806c42f0a06b3821ed6e8fca31e)