ccci: fix PTR_RET build breaks
Error:
drivers/misc/mediatek/msg-center/ccci_msg_
center.c:659:10: error: implicit declaration of function 'PTR_RET' [-Werror,-Wimplicit-function-declaration]

Feature: [Module]Kernel Maintenance
Change-Id: Ib83180cbc28f0377720bbbd1cc6b817211484d13
CR-Id: ALPS05298037
Signed-off-by: Miles Chen <miles.chen@mediatek.com>
Source_Git_Sha: 12490a73087cff123ccc4bd68c319f09111ea01d