mtkcam: fix y2038 build breaks
Error:
drivers/misc/mediatek/cameraisp/rsc/isp_6s/camera_rsc.c:1716:17: error: variable has incomplete type 'struct timeval'

Signed-off-by: Miles Chen <miles.chen@mediatek.com>
Change-Id: I2e7086385a91faf82c53779b55e41eb371469a73
CR-Id: ALPS05298037
Feature: [Module]Kernel Maintenance
Signed-off-by: Miles Chen <miles.chen@mediatek.com>