[ALPS04758189] GPU: fix build breaks when CONFIG_KASAN=y
Fix build break: error format

drivers/misc/mediatek/base/power/gpufreq_v1/mt6885/mtk_gpufreq_plat.c:2129
error: format ˉ%lxˇ expects argument of type ˉlong unsigned intˇ,
 but argument 6 has type ˉunsigned intˇ [-Werror=format=]

MTK-Commit-Id: ac5cf112389cebf27598093d41b30767abb47067

Change-Id: I9a03a2eddbf5ade1c32c3779efd35b8299f1c8dd
Signed-off-by: max.yu <max.yu@mediatek.com>
CR-Id: ALPS04758189
Feature: OpenGL|ES