lpm: remove the use of irq_to_desc
irq_to_desc is restrict exported by commit 64a1b95bb9fe3ec76e1a2cd803eff06389341ae4
("genirq: Restrict export of irq_to_desc()").

Replace irq_to_desc() with irq_get_irq_data().

Error:
ERROR: modpost: "irq_to_desc" [drivers/misc/mediatek/lpm/modules/platform/mtk-lpm-plat-mt6873.ko] undefined!
ERROR: modpost: "irq_to_desc" [drivers/misc/mediatek/lpm/mtk-lpm.ko] undefined!

Change-Id: Ie54a91b69e9c1834f00eb2f14cf732c59059b806
Signed-off-by: Miles Chen <miles.chen@mediatek.com>
Feature: [Module]Kernel Maintenance
CR-Id: ALPS05672993