scsi: ufs: fix unused label build breaks
Errors:
drivers/scsi/ufs/ufshcd.c:8431:1: error: unused label 'out' [-Werror,-Wunused-label]

Change-Id: Ida2b3cf2171bdec609cd6d7e9e7e83da26b574f5
CR-Id: ALPS05511922
Feature: [Module]Kernel Maintenance
Signed-off-by: Miles Chen <miles.chen@mediatek.com>
(cherry picked from commit a11970e53c42509deb4d1846bb63d65c61a4f888)