atf_logger: fix proc_create() build breaks
Error
drivers/misc/mediatek/atf/atf_logger.c:525:21: error: incompatible pointer types passing 'const struct file_operations *' to parameter of type 'const struct proc_ops *' [-Werror,-Wincompatible-pointer-types]
drivers/misc/mediatek/atf/atf_logger.c:533:21: error: incompatible pointer types passing 'const struct file_operations *' to parameter of type 'const struct proc_ops *' [-Werror,-Wincompatible-pointer-types]

Signed-off-by: Miles Chen <miles.chen@mediatek.com>
Change-Id: I4d01386dee9a8d9fbabb1ba7f09e9bb21ae387dd
CR-Id: ALPS05298037
Feature: [Module]Kernel Maintenance
Signed-off-by: Miles Chen <miles.chen@mediatek.com>