mmstat: fix implicit conversion from enumeration build breaks
Errors:
drivers/misc/mediatek/mmstat/trace_mmstat.c:163:55: error: implicit conversion from enumeration type 'enum node_stat_item' to different enumeration type 'enum zone_stat_item' [-Werror,-Wenum-conversion]

Change-Id: I56fa3e85835b587fe48f39ccf1aa09aa6a0a79ed
Signed-off-by: Miles Chen <miles.chen@mediatek.com>
CR-Id: ALPS05568046
Feature: [Module]Kernel Maintenance