ASoc: mediatek: fix struct snd_soc_pcm_runtime build breaks
Errors:
sound/soc/mediatek/common/mtk-afe-fe-dai.c:354:12: error: no member named 'cpu_dai' in 'struct snd_soc_pcm_runtime'
sound/soc/mediatek/audio_dsp/mtk-dsp-platform-driver.c:714:16: error: no member named 'cpu_dai' in 'struct snd_soc_pcm_runtime'
sound/soc/mediatek/audio_dsp/mtk-dsp-platform-driver.c:780:12: error: no member named 'cpu_dai' in 'struct snd_soc_pcm_runtime'
sound/soc/mediatek/audio_dsp/mtk-dsp-platform-driver.c:1144:16: error: no member named 'cpu_dai' in 'struct snd_soc_pcm_runtime'
sound/soc/mediatek/audio_dsp/mtk-dsp-platform-driver.c:1176:16: error: no member named 'cpu_dai' in 'struct snd_soc_pcm_runtime'
sound/soc/mediatek/audio_dsp/mtk-dsp-platform-driver.c:1203:16: error: no member named 'cpu_dai' in 'struct snd_soc_pcm_runtime'
sound/soc/mediatek/audio_dsp/mtk-dsp-platform-driver.c:1302:16: error: no member named 'cpu_dai' in 'struct snd_soc_pcm_runtime'
sound/soc/mediatek/audio_dsp/mtk-dsp-platform-driver.c:1338:16: error: no member named 'cpu_dai' in 'struct snd_soc_pcm_runtime'
sound/soc/mediatek/audio_dsp/mtk-dsp-platform-driver.c:1379:16: error: no member named 'cpu_dai' in 'struct snd_soc_pcm_runtime'
sound/soc/mediatek/audio_dsp/mtk-dsp-platform-driver.c:1390:16: error: no member named 'cpu_dai' in 'struct snd_soc_pcm_runtime'
sound/soc/mediatek/audio_dsp/mtk-dsp-platform-driver.c:1407:24: error: no member named 'cpu_dai' in 'struct snd_soc_pcm_runtime'
sound/soc/mediatek/audio_dsp/mtk-dsp-platform-driver.c:1429:16: error: no member named 'cpu_dai' in 'struct snd_soc_pcm_runtime'
sound/soc/mediatek/audio_dsp/mtk-dsp-platform-driver.c:1499:16: error: no member named 'cpu_dai' in 'struct snd_soc_pcm_runtime'
sound/soc/mediatek/audio_dsp/mtk-dsp-platform-driver.c:1553:16: error: no member named 'cpu_dai' in 'struct snd_soc_pcm_runtime'
sound/soc/mediatek/audio_dsp/mtk-dsp-platform-driver.c:1753:3: error: field designator 'ops' does not refer to any field in type 'const struct snd_soc_component_driver'
sound/soc/mediatek/audio_dsp/mtk-dsp-platform-driver.c:1754:3: error: field designator 'pcm_new' does not refer to any field in type 'const struct snd_soc_component_driver'
sound/soc/mediatek/mt6873/mt6873-afe-pcm.c:302:16: error: no member named 'cpu_dai' in 'struct snd_soc_pcm_runtime'

Change-Id: Ic8afc82759bf239c68508dbbb4eb12ef396ed8e6
CR-Id: ALPS05442624
Feature: [Module]Kernel Maintenance
Signed-off-by: Miles Chen <miles.chen@mediatek.com>
(cherry picked from commit e0486361b3d3850339323cc704d72e13f8d17a73)