Lens: fix v4l2_async_notifier_add_subdev build breaks
Errors:
/mfs/mtkslt0480/mtk04267/CAS_REAL/alps-dev-r0.bsp-common-kernel-5.4--2021_03_10_23_00-6873/merged/kernel-mainline/drivers/misc/mediatek/lens/vcm/v4l2/media/mtk-composite.c:146:19: error: expected expression

Change-Id: I098fdc0c243ef16d873e57a678e1103766e29ffd
Signed-off-by: Miles Chen <miles.chen@mediatek.com>
Feature: [Module]Kernel Maintenance
CR-Id: ALPS05625693