isp p1: fix proc_create() build breaks
Error:
drivers/misc/mediatek/cameraisp/src/isp_6s/camera_isp.c:7303:54: error: incompatible pointer types passing 'const struct file_operations *' to parameter of type 'const struct proc_ops *' [-Werror,-Wincompatible-pointer-types]

Feature: [Module]Kernel Maintenance
Change-Id: I54703c7eefc4ccd36904dffde7cb2aab4c22e064
CR-Id: ALPS05298037
Signed-off-by: Miles Chen <miles.chen@mediatek.com>