WPE driver: fix timeval build breaks
Errors:
drivers/misc/mediatek/cameraisp/wpe/isp_6s/camera_wpe.c:3155:17: error: variable has incomplete type 'struct timeval'

Change-Id: Ie02bc8a27e01b9f0ce721e716c48491aa8f7118d
CR-Id: ALPS05381961
Feature: [Module]Kernel Maintenance
Signed-off-by: Miles Chen <miles.chen@mediatek.com>