arm64: fix undeclared identifier 'regs' build breaks
Error:
arch/arm64/kernel/smp.c:906:29: error: use of undeclared identifier 'regs'

Change-Id: I6bb582d53e957eedc8d1a9d6bc58039ae3b22bb8
Signed-off-by: Miles Chen <miles.chen@mediatek.com>
CR-Id: ALPS05387262
Feature: [Module]Kernel Maintenance