regulator: mt6315: fix regulator_linear_range build breaks
Error:
drivers/regulator/mt6315-regulator.c:75:58: error: array has incomplete element type 'const struct regulator_linear_range'

Signed-off-by: Miles Chen <miles.chen@mediatek.com>
Feature: [Module]Kernel Maintenance
Change-Id: I2a565472043c35e4a7422cd3553d92458a50ad1c
CR-Id: ALPS05298037
Signed-off-by: Miles Chen <miles.chen@mediatek.com>