soc: mediatek: fix num_domains build breaks
Use ARRAY_SIZE to count num_domains.

Errors:
drivers/soc/mediatek/mtk-scpsys.c:1941:3: error: use of undeclared identifier 'MT8192_POWER_DOMAIN_ADSP'

Change-Id: I1e0b7929cead24d8444b15c8543d5c7f4981ffc4
Signed-off-by: Miles Chen <miles.chen@mediatek.com>
CR-Id: ALPS05568046
Feature: [Module]Kernel Maintenance