lpm: fix allmodconfig build breaks
fix lpm related allmodconfig build errors

build command:
ARCH=arm64 make mrproper allmodconfig all

Errors:
drivers/misc/mediatek/lpm/lpm_module.c:23:10: error: 'lpm_internal.h' file not found with <angled> include; use "quotes" instead
drivers/misc/mediatek/lpm/platform/lpm_irqremain.c:18:10: fatal error: 'lpm_internal.h' file not found
drivers/misc/mediatek/lpm/platform/lpm_resource_ctrl.c:12:10: fatal error: 'lpm_internal.h' file not found
drivers/misc/mediatek/lpm/platform/lpm_rc.c:12:10: fatal error: 'lpm_internal.h' file not found
drivers/misc/mediatek/lpm/platform/lpm_trace.c:13:10: fatal error: 'lpm_internal.h' file not found

Change-Id: I5c75af6bcfc853d609bb6717b0d4ff13577a44b8
Cc: rogercl.yang <rogercl.yang@mediatek.com>
Signed-off-by: Miles Chen <miles.chen@mediatek.com>
Feature: Kernel SI Operation
CR-Id: ALPS05903624