cpufreq: mediatek-hw: fix em_register_perf_domain build breaks
Error:
drivers/cpufreq/mediatek-cpufreq-hw.c:113:34: error: incompatible function pointer types initializing 'int (*)(unsigned long *, unsigned long *, struct device *)' with an expression of type 'int (*)(unsigned long *, unsigned long *, int)' [-Werror,-Wincompatible-function-pointer-types]
drivers/cpufreq/mediatek-cpufreq-hw.c:141:2: error: implicit declaration of function 'em_register_perf_domain' [-Werror,-Wimplicit-function-declaration]

Signed-off-by: Miles Chen <miles.chen@mediatek.com>
Feature: [Module]Kernel Maintenance
Change-Id: I2aae776e79c5a52e0248552b19f403f2f57c4ae5
CR-Id: ALPS05298037
Signed-off-by: Miles Chen <miles.chen@mediatek.com>
Source_Git_Sha: 9e91d839666f3252331835a70cc59eaafe17e390