[ALPS04057194] kernel: disable native clang kernel build warnings
Wrap clang compile options since gcc does not understand them.
This is for the following build warnings:

arch/arm64/crypto/crct10dif-ce-glue.c:96:1: error: variable
cpu_feature_match_PMULL is not needed and will not be emitted
[-Werror,-Wunneeded-internal-declaration]

arch/arm64/crypto/crc32-ce-glue.c:235:33: error: variable
crc32_cpu_feature is not needed and will not be emitted
[-Werror,-Wunneeded-internal-declaration]

drivers/clocksource/mtk_timer.c:238:44: error: implicit
declaration of function sched_clock
[-Werror,-Wimplicit-function-declaration]

drivers/clocksource/mtk_timer.c:238:44: error: this function
declaration is not a prototype [-Werror,-Wstrict-prototypes]

drivers/cpufreq/cppc_cpufreq.c:281:36: error: variable
cppc_acpi_ids is not needed and will not be emitted
[-Werror,-Wunneeded-internal-declaration]

drivers/crypto/bcm/cipher.c:822:34: error: implicit conversion
from enumeration type enum spu_cipher_type
to different enumeration type enum hash_type [-Werror,-Wenum nversion]

drivers/crypto/bcm/cipher.c:1413:26: error: implicit conversion
from enumeration type enum spu_cipher_type to different enumeration
type enum hash_type [-Werror,-Wenu onversion]

drivers/pinctrl/pinctrl-max77620.c:56:12: error: implicit conversion
from enumeration type enum max77620_pinconf_param to different
enumeration type enum pin_config_pa  [-Werror,-Wenum-conversion]

drivers/soc/rockchip/pm_domains.c:726:21: error: shift count is
negative [-Werror,-Wshift-count-negative]

MTK-Commit-Id: 84eb4416edaa384fa657540be1b6dd9b134d52a9

Change-Id: I08424499caeef8bc086d3ec7f920741caeed85c6
Signed-off-by: Miles Chen <miles.chen@mediatek.com>
CR-Id: ALPS04057194
Feature: [Module]Kernel Maintenance