mnoc: fix qos_req not defined build breaks
Error:
drivers/misc/mediatek/apusys/mnoc/1.5/mnoc_qos.c:284:49: error: no member named 'qos_req' in 'struct engine_pm_qos_counter'

Signed-off-by: Miles Chen <miles.chen@mediatek.com>
Change-Id: I1105ea053638ca019b6eca59a1f8e3f6079f8482
CR-Id: ALPS05298037
Feature: [Module]Kernel Maintenance
Signed-off-by: Miles Chen <miles.chen@mediatek.com>
Source_Git_Sha: 7d79e66cea0875db71b68a14839c280b8df4bd99