[ALPS05647642] aee: build error due to init fail
Error: mrdump_ka_init fail

Fix: skip mrdump kernel init as a workaround.

MTK-Commit-Id: 702c1bd4d0d013fe735639ac276752f8a3c41583

Change-Id: I6240c525be01eaad89a8692811bc717deb18d738
Signed-off-by: zhiyong.wang <zhiyong.wang@mediatek.com>
CR-Id: ALPS05647642
Feature: Android Exception Engine(AEE)