battery: fix timespec build breaks
Fix timespace with timespec64

Error:
drivers/power/supply/mtk_battery.h:831:18: error: field has incomplete type 'struct timespec'
drivers/power/supply/mtk_battery.h:831:18: error: field has incomplete type 'struct timespec'
drivers/power/supply/mtk_battery_algo.c:24:18: error: variable has incomplete type 'struct timespec'
drivers/power/supply/mtk_battery_algo.c:24:32: error: variable has incomplete type 'struct timespec'
drivers/power/supply/mtk_battery_algo.c:28:17: error: implicit declaration of function 'ktime_to_timespec' [-Werror,-Wimplicit-function-declaration]
drivers/power/supply/mtk_battery.h:831:18: error: field has incomplete type 'struct timespec'
drivers/power/supply/mtk_battery.h:831:18: error: field has incomplete type 'struct timespec'
drivers/power/supply/mtk_battery.c:373:18: error: variable has incomplete type 'struct timespec'
drivers/power/supply/mtk_battery.c:447:15: error: implicit declaration of function 'ktime_to_timespec' [-Werror,-Wimplicit-function-declaration]
drivers/power/supply/mtk_battery.c:1784:18: error: variable has incomplete type 'struct timespec'
drivers/power/supply/mtk_battery.c:1814:14: error: implicit declaration of function 'ktime_to_timespec' [-Werror,-Wimplicit-function-declaration]
drivers/power/supply/mtk_battery.c:2045:18: error: variable has incomplete type 'struct timespec'
drivers/power/supply/mtk_battery.c:2045:29: error: variable has incomplete type 'struct timespec'
drivers/power/supply/mtk_battery.c:2045:43: error: variable has incomplete type 'struct timespec'
drivers/power/supply/mtk_battery.c:2063:15: error: implicit declaration of function 'ktime_to_timespec' [-Werror,-Wimplicit-function-declaration]
drivers/power/supply/mtk_battery.c:2075:17: error: implicit declaration of function 'ktime_to_timespec' [-Werror,-Wimplicit-function-declaration]
drivers/power/supply/mtk_battery.c:2458:18: error: variable has incomplete type 'struct timespec'
drivers/power/supply/mtk_battery.c:2486:20: error: implicit declaration of function 'ktime_to_timespec' [-Werror,-Wimplicit-function-declaration]
drivers/power/supply/mtk_battery.c:2510:20: error: implicit declaration of function 'ktime_to_timespec' [-Werror,-Wimplicit-function-declaration]
drivers/power/supply/mtk_battery.c:2530:19: error: implicit declaration of function 'ktime_to_timespec' [-Werror,-Wimplicit-function-declaration]
drivers/power/supply/mtk_battery.c:2600:22: error: implicit declaration of function 'ktime_to_timespec' [-Werror,-Wimplicit-function-declaration]
drivers/power/supply/mtk_battery.c:2658:18: error: variable has incomplete type 'struct timespec'
drivers/power/supply/mtk_battery.c:2658:28: error: variable has incomplete type 'struct timespec'
drivers/power/supply/mtk_battery.c:2665:19: error: implicit declaration of function 'ktime_to_timespec' [-Werror,-Wimplicit-function-declaration]

Signed-off-by: Miles Chen <miles.chen@mediatek.com>
Change-Id: I672e1eee36d92867003d8655e44c62c9ef2389dd
CR-Id: ALPS05298037
Feature: [Module]Kernel Maintenance
Signed-off-by: Miles Chen <miles.chen@mediatek.com>
Source_Git_Sha: d23f24e3f3c7b2020a0a1e192ff73de92d684d7d