extcon: fix struct device_connection build breaks
Error:
drivers/misc/mediatek/extcon/extcon-mtk-usb.h:16:27: error: field has incomplete type 'struct device_connection'
drivers/misc/mediatek/extcon/extcon-mtk-usb.c:342:2: error: implicit declaration of function 'device_connection_add' [-Werror,-Wimplicit-function-declaration]
drivers/misc/mediatek/extcon/extcon-mtk-usb.c:399:3: error: implicit declaration of function 'device_connection_remove' [-Werror,-Wimplicit-function-declaration]

Change-Id: I9bb7132d7a5ed93c11ad47220b73051259b54468
CR-Id: ALPS05431666
Feature: [Module]Kernel Maintenance
Signed-off-by: Miles Chen <miles.chen@mediatek.com>