battery: fix timespec build breaks
Error:
drivers/power/supply/mtk_battery_daemon.c:64:18: error: variable has incomplete type 'struct timespec'
drivers/power/supply/mtk_battery_daemon.c:67:13: error: implicit declaration of function 'ktime_to_timespec' [-Werror,-Wimplicit-function-declaration]
drivers/power/supply/mtk_battery_daemon.c:2422:19: error: variable has incomplete type 'struct timespec'
drivers/power/supply/mtk_battery_daemon.c:2422:29: error: variable has incomplete type 'struct timespec'
drivers/power/supply/mtk_battery_daemon.c:2428:15: error: implicit declaration of function 'ktime_to_timespec' [-Werror,-Wimplicit-function-declaration]
drivers/power/supply/mtk_battery_daemon.c:3017:19: error: variable has incomplete type 'struct timespec'
drivers/power/supply/mtk_battery_daemon.c:3017:29: error: variable has incomplete type 'struct timespec'
drivers/power/supply/mtk_battery_daemon.c:3041:16: error: implicit declaration of function 'ktime_to_timespec' [-Werror,-Wimplicit-function-declaration]
drivers/power/supply/mtk_battery_daemon.c:4130:18: error: variable has incomplete type 'struct timespec'
drivers/power/supply/mtk_battery_daemon.c:4133:13: error: implicit declaration of function 'timespec_to_ktime' [-Werror,-Wimplicit-function-declaration]
drivers/power/supply/mtk_battery_daemon.c:4135:13: error: implicit declaration of function 'ktime_to_timespec' [-Werror,-Wimplicit-function-declaration]
drivers/power/supply/mtk_battery_daemon.c:4138:29: error: assigning to 'struct timespec64' from incompatible type 'int'
drivers/power/supply/mtk_battery_daemon.c:4174:18: error: variable has incomplete type 'struct timespec'
drivers/power/supply/mtk_battery_daemon.c:4178:9: error: implicit declaration of function 'ktime_to_timespec' [-Werror,-Wimplicit-function-declaration]

Feature: [Module]Kernel Maintenance
Change-Id: I682915f5add58d15535bf311c4169b9ef27e8fef
CR-Id: ALPS05357698
Signed-off-by: Miles Chen <miles.chen@mediatek.com>