usb: typec: tcpc: fix mt6360 pd build error
CC [M]  drivers/misc/mediatek/typec/tcpc/pd_dpm_core.o
kernel-5.4/drivers/misc/mediatek/typec/tcpc/pd_dpm_core.c:1541:15:
error: implicit declaration of function 'dpm_is_valid_pdo_pair'
[-Werror,-Wimplicit-function-declaration]
                        find_cap = dpm_is_valid_pdo_pair(&sink, &source,
                                   ^

(cherry-picked from commit 4f4862b7e7bab75512d7a0daea6f3b527bb9d9e5)
Signed-off-by: Vend.Gene.Chen <vend_gene_chen001@mediatek.com>
Change-Id: I425af92e84337482e1536fb88b6a310fd9f74a28
CR-Id: ALPS05298037
Feature: Charger
Signed-off-by: Miles Chen <miles.chen@mediatek.com>