[ALPS04776236] sched_mon: update kernel configuration
add new configuration:
CONFIG_MTK_IRQ_COUNT_TRACER
CONFIG_MTK_IRQ_OFF_TRACER
CONFIG_MTK_PREEMPT_TRACER

remove unused configuration:
CONFIG_MTK_RCU_MONITOR
CONFIG_MTK_SCHED_MON_DEFAULT_ENABLE
CONFIG_PREEMPT_MONITOR

remove auto selected configuration:
CONFIG_ENABLE_DEFAULT_TRACERS

update Kconfig of schedule monitor
update configurations to projects
update correct_config.csv

fix drivers/misc/mediatek/include/mt-plat/mtk_sched_mon.h:161:13:
error: inlining failed in call to always_inline trace_hardirqs_off_time
: function body not available
    inline void trace_hardirqs_off_time(void);

MTK-Commit-Id: abb9d013ebc69df7f534cde4ea5f2fd6999a3134

Change-Id: I80bc9176213a4cdfa03c51bb5315b6cb65a19462
CR-Id: ALPS04776236
Feature: [Module]Schedule Monitor
Signed-off-by: Kobe Wu <kobe-cp.wu@mediatek.com>