apusys power: fix unused function build breaks
Errors:
drivers/misc/mediatek/apusys/power/2.5/common/apu-regulator.c:40:12: error: unused function '_apu_avs_static' [-Werror,-Wunused-function]

(cherry-picked from commit 9b025f08f74479a768a0f79b1aee3ab2ec34dfe2)
Change-Id: If656bcbc70cbae61c90226a297a3cac2b38fc0ea
CR-Id: ALPS05511922
Feature: [Module]Kernel Maintenance
Signed-off-by: Miles Chen <miles.chen@mediatek.com>
(cherry picked from commit a534c883e67e671a5263fb7587d01dc4c3c9a4c5)