dma: mediatek: fix unused variable build breaks
Errors:
drivers/dma/mediatek/mtk-uart-apdma.c:512:19: error: unused variable 'res' [-Werror,-Wunused-variable]

Change-Id: I058b6f3bf081654d012ffae0556ae02d77e42d1f
CR-Id: ALPS05511922
Feature: [Module]Kernel Maintenance
Signed-off-by: Miles Chen <miles.chen@mediatek.com>