mnoc: fix pm_qos and init_timer build breaks
Error:
drivers/misc/mediatek/apusys/mnoc/1.5/mnoc_qos.c:162:2: error: implicit declaration of function 'pm_qos_add_request' [-Werror,-Wimplicit-function-declaration]
drivers/misc/mediatek/apusys/mnoc/1.5/mnoc_qos.c:162:26: error: use of undeclared identifier 'PM_QOS_APU_MEMORY_BANDWIDTH'
drivers/misc/mediatek/apusys/mnoc/1.5/mnoc_qos.c:170:2: error: implicit declaration of function 'pm_qos_update_request' [-Werror,-Wimplicit-function-declaration]
drivers/misc/mediatek/apusys/mnoc/1.5/mnoc_qos.c:175:2: error: implicit declaration of function 'pm_qos_update_request' [-Werror,-Wimplicit-function-declaration]
drivers/misc/mediatek/apusys/mnoc/1.5/mnoc_qos.c:175:29: error: use of undeclared identifier 'PM_QOS_APU_MEMORY_BANDWIDTH_DEFAULT_VALUE'
drivers/misc/mediatek/apusys/mnoc/1.5/mnoc_qos.c:176:2: error: implicit declaration of function 'pm_qos_remove_request' [-Werror,-Wimplicit-function-declaration]
drivers/misc/mediatek/apusys/mnoc/1.5/mnoc_qos.c:220:2: error: implicit declaration of function 'init_timer' [-Werror,-Wimplicit-function-declaration]
drivers/misc/mediatek/apusys/mnoc/1.5/mnoc_qos.c:221:30: error: incompatible function pointer types assigning to 'void (*)(struct timer_list *)' from 'void (*)(unsigned long)' [-Werror,-Wincompatible-function-pointer-types]
drivers/misc/mediatek/apusys/mnoc/1.5/mnoc_qos.c:222:21: error: no member named 'data' in 'struct timer_list'
drivers/misc/mediatek/apusys/mnoc/1.5/mnoc_qos.c:253:6: error: redefinition of 'apu_qos_on'
drivers/misc/mediatek/apusys/mnoc/1.5/mnoc_qos.c:273:6: error: redefinition of 'apu_qos_off'
drivers/misc/mediatek/apusys/mnoc/1.5/mnoc_qos.c:289:4: error: use of undeclared identifier 'PM_QOS_APU_MEMORY_BANDWIDTH_DEFAULT_VALUE'
drivers/misc/mediatek/apusys/mnoc/1.5/mnoc_qos.c:591:6: error: redefinition of 'apu_qos_suspend'
drivers/misc/mediatek/apusys/mnoc/1.5/mnoc_qos.c:630:6: error: redefinition of 'apu_qos_resume'
drivers/misc/mediatek/apusys/mnoc/1.5/mnoc_qos.c:978:6: error: redefinition of 'apu_qos_boost_start'
drivers/misc/mediatek/apusys/mnoc/1.5/mnoc_qos.c:985:3: error: use of undeclared identifier 'PM_QOS_DDR_OPP_DEFAULT_VALUE'
drivers/misc/mediatek/apusys/mnoc/1.5/mnoc_qos.c:987:3: error: implicit declaration of function 'pm_qos_update_request' [-Werror,-Wimplicit-function-declaration]
drivers/misc/mediatek/apusys/mnoc/1.5/mnoc_qos.c:998:6: error: redefinition of 'apu_qos_boost_end'
drivers/misc/mediatek/apusys/mnoc/1.5/mnoc_qos.c:1008:4: error: use of undeclared identifier 'PM_QOS_DDR_OPP_DEFAULT_VALUE'
fatal error: too many errors emitted, stopping now [-ferror-limit=]

Signed-off-by: Miles Chen <miles.chen@mediatek.com>
Change-Id: I69c210a64a7f6a713bed55a9e540fcfe72a07de2
CR-Id: ALPS05298037
Feature: [Module]Kernel Maintenance
Signed-off-by: Miles Chen <miles.chen@mediatek.com>
Source_Git_Sha: 6f0d2464732832eef4a4663c196786ceef0c4e73