[ALPS04999122] arm64: configs: mt6853v1_64: disable CONFIG_MTK_EARA_AI
[Detail]
error: undefined symbol: fpsgo_debugfs_dir
debugfs is deprecated in Android R that we need to
disable first to prevent build break.

MTK-Commit-Id: 3dc5319884cd60221cb0d9854376d5df0cd2a17e

Change-Id: I3b9a898c970509556c3e3707c4914f7195d79822
Signed-off-by: Juju Sung <juju.sung@mediatek.com>
CR-Id: ALPS04999122
Feature: [Module]Kernel Maintenance