touch: fix ununsed variable build breaks
Errors:
drivers/input/touchscreen/GTP1151/tpd_control.c:45:6: error: unused variable 'convert_err' [-Werror,-Wunused-variable]

(cherry-picked from commit 0bdf9726f09e2813ce7b5069cbcc59a8cf704e53)
Change-Id: Ie27cde62d30d8f96c9f50868f2080faaca61717f
CR-Id: ALPS05511922
Feature: [Module]Kernel Maintenance
Signed-off-by: Miles Chen <miles.chen@mediatek.com>