dvfsrc: mediatek: fix no return value build breaks
Errors:
rivers/misc/mediatek/dvfsrc/dvfsrc-helper.c:715:1: error: non-void function does not return a value in all control paths [-Werror,-Wreturn-type]

Change-Id: I94a105ccd0740395340d8597a892de34e013a58b
CR-Id: ALPS05442624
Feature: [Module]Kernel Maintenance
Signed-off-by: Miles Chen <miles.chen@mediatek.com>
(cherry picked from commit feb7c8f18c5792d31a4118e4026d793d74aceb0b)