extcon: fix unused variable build breaks
Errors:
drivers/misc/mediatek/extcon/extcon-mtk-usb.c:301:26: error: unused variable 'conn_pdev' [-Werror,-Wunused-variable]
drivers/misc/mediatek/extcon/extcon-mtk-usb.c:302:22: error: unused variable 'conn_np' [-Werror,-Wunused-variable]

(cherry-picked from commit 1ff35c8177e7eaa7ea8111dcd6701300d51fc20e)
Change-Id: I5fd0185271594bfbf8e0b62aa69249b06c1c86e3
CR-Id: ALPS05511922
Feature: [Module]Kernel Maintenance
Signed-off-by: Miles Chen <miles.chen@mediatek.com>