apusys: fix variable length arrays build breaks
Errors:
drivers/misc/mediatek/apusys/midware/1.5/mdw_dbg.c:301:20: error: variable length arrays are a C99 feature [-Werror,-Wvla-extension]
drivers/misc/mediatek/apusys/power/2.0/apusys_power_debug.c:477:20: error: variable length arrays are a C99 feature [-Werror,-Wvla-extension]
drivers/misc/mediatek/apusys/power/2.5/common/apu-dbg.c:653:20: error: variable length arrays are a C99 feature [-Werror,-Wvla-extension]

Change-Id: I37b263f774774ab9185ef8755832869a670a2c16
Signed-off-by: Miles Chen <miles.chen@mediatek.com>
Feature: [Module]Kernel Maintenance
CR-Id: ALPS05595303