ASoC: fix mtk_memif_set_enable build breaks
Fix build breaks after disable adsp kernel configs

Errors:
sound/soc/mediatek/mt6873/../common/mtk-afe-fe-dai.h:38:5: note: 'mtk_memif_set_enable' declared here
int mtk_memif_set_enable(struct mtk_base_afe *afe, int id);
sound/soc/mediatek/mt6873/mt6873-afe-pcm.c:236:4: error: implicit declaration of function 'mtk_dsp_irq_set_disable' [-Werror,-Wimplicit-function-declaration]
mtk_dsp_irq_set_disable(afe, irq_data);
sound/soc/mediatek/mt6873/mt6873-afe-pcm.c:236:4: note: did you mean 'mtk_dsp_irq_set_enable'?
sound/soc/mediatek/mt6873/mt6873-afe-pcm.c:192:4: note: 'mtk_dsp_irq_set_enable' declared here

Change-Id: I6fbcca699cd8cde880afde60dd0d0537f2e39733
Signed-off-by: Miles Chen <miles.chen@mediatek.com>
CR-Id: ALPS05568046
Feature: [Module]Kernel Maintenance