AEE: fix proc_ops(), mmap_sem, y2038 build breaks
Error:
drivers/misc/mediatek/aee/aed/reboot-reason.c:46:4: error: incompatible pointer types passing 'const struct file_operations *' to parameter of type 'const struct proc_ops *' [-Werror,-Wincompatible-pointer-types]
drivers/misc/mediatek/aee/aed/aed-debug.c:707:2: error: incompatible pointer types passing 'const struct file_operations *' to parameter of type 'const struct proc_ops *' [-Werror,-Wincompatible-pointer-types]
drivers/misc/mediatek/aee/aed/aed-debug.c:709:2: error: incompatible pointer types passing 'const struct file_operations *' to parameter of type 'const struct proc_ops *' [-Werror,-Wincompatible-pointer-types]
drivers/misc/mediatek/aee/aed/aed-debug.c:711:2: error: incompatible pointer types passing 'const struct file_operations *' to parameter of type 'const struct proc_ops *' [-Werror,-Wincompatible-pointer-types]
drivers/misc/mediatek/aee/aed/aed-debug.c:712:2: error: incompatible pointer types passing 'const struct file_operations *' to parameter of type 'const struct proc_ops *' [-Werror,-Wincompatible-pointer-types]
drivers/misc/mediatek/aee/aed/aed-debug.c:714:2: error: incompatible pointer types passing 'const struct file_operations *' to parameter of type 'const struct proc_ops *' [-Werror,-Wincompatible-pointer-types]
drivers/misc/mediatek/aee/aed/aed-debug.c:715:2: error: incompatible pointer types passing 'const struct file_operations *' to parameter of type 'const struct proc_ops *' [-Werror,-Wincompatible-pointer-types]
drivers/misc/mediatek/aee/aed/aed-debug.c:716:2: error: incompatible pointer types passing 'const struct file_operations *' to parameter of type 'const struct proc_ops *' [-Werror,-Wincompatible-pointer-types]
drivers/misc/mediatek/aee/aed/aed-debug.c:717:2: error: incompatible pointer types passing 'const struct file_operations *' to parameter of type 'const struct proc_ops *' [-Werror,-Wincompatible-pointer-types]
drivers/misc/mediatek/aee/aed/aed-main.c:632:61: error: too many arguments provided to function-like macro invocation
drivers/misc/mediatek/aee/aed/aed-main.c:641:20: error: use of undeclared identifier 'aee_kapi_tasklet'
drivers/misc/mediatek/aee/aed/aed-main.c:1351:42: error: too many arguments to function call, expected 7, have 8
drivers/misc/mediatek/aee/aed/aed-main.c:1722:24: error: no member named 'mmap_sem' in 'struct mm_struct'
drivers/misc/mediatek/aee/aed/aed-main.c:1734:22: error: no member named 'mmap_sem' in 'struct mm_struct'
drivers/misc/mediatek/aee/aed/aed-main.c:1835:25: error: no member named 'mmap_sem' in 'struct mm_struct'
drivers/misc/mediatek/aee/aed/aed-main.c:1873:23: error: no member named 'mmap_sem' in 'struct mm_struct'
drivers/misc/mediatek/aee/aed/aed-main.c:2119:31: error: no member named 'mmap_sem' in 'struct mm_struct'
drivers/misc/mediatek/aee/aed/aed-main.c:2163:29: error: no member named 'mmap_sem' in 'struct mm_struct'
drivers/misc/mediatek/aee/aed/aed-main.c:2267:3: error: implicit declaration of function 'rtc_time_to_tm' [-Werror,-Wimplicit-function-declaration]
drivers/misc/mediatek/aee/aed/aed-main.c:2361:2: error: implicit declaration of function 'rtc_time_to_tm' [-Werror,-Wimplicit-function-declaration]
drivers/misc/mediatek/aee/aed/aed-main.c:2456:2: error: incompatible pointer types passing 'const struct file_operations *' to parameter of type 'const struct proc_ops *' [-Werror,-Wincompatible-pointer-types]
drivers/misc/mediatek/aee/aed/aed-main.c:2637:2: error: implicit declaration of function 'rtc_time_to_tm' [-Werror,-Wimplicit-function-declaration]
drivers/misc/mediatek/aee/mrdump/mrdump_mini.c:134:6: error: implicit declaration of function 'probe_kernel_address' [-Werror,-Wimplicit-function-declaration]
drivers/misc/mediatek/aee/mrdump/mrdump_mini.c:136:19: error: incompatible pointer types passing 'pgd_t *' to parameter of type 'p4d_t *' [-Werror,-Wincompatible-pointer-types]
drivers/misc/mediatek/aee/mrdump/mrdump_mini.c:134:6: error: initializing 'const typeof (pgd) *' (aka 'pgd_t *const *') with an expression of incompatible type 'pgd_t'
drivers/misc/mediatek/aee/mrdump/mrdump_mini.c:134:40: error: invalid operands to binary expression ('void' and 'int')
drivers/misc/mediatek/aee/mrdump/mrdump_mini.c:136:19: error: incompatible pointer types passing 'pgd_t *' to parameter of type 'p4d_t *' [-Werror,-Wincompatible-pointer-types]
drivers/misc/mediatek/aee/mrdump/mrdump_mini.c:137:6: error: initializing 'const typeof (pud) *' (aka 'pud_t *const *') with an expression of incompatible type 'pud_t'
drivers/misc/mediatek/aee/mrdump/mrdump_mini.c:137:40: error: invalid operands to binary expression ('void' and 'int')
drivers/misc/mediatek/aee/mrdump/mrdump_mini.c:143:7: error: initializing 'const typeof (pmd) *' (aka 'pmd_t *const *') with an expression of incompatible type 'pmd_t'
drivers/misc/mediatek/aee/mrdump/mrdump_mini.c:143:41: error: invalid operands to binary expression ('void' and 'int')
drivers/misc/mediatek/aee/mrdump/mrdump_mini.c:150:8: error: initializing 'const typeof (ptep) *' (aka 'pte_t *const *') with an expression of incompatible type 'pte_t'
drivers/misc/mediatek/aee/mrdump/mrdump_mini.c:151:5: error: invalid operands to binary expression ('void' and 'int')

Signed-off-by: Miles Chen <miles.chen@mediatek.com>
Change-Id: I9ed067ba84092316a420ec22cea4b041ca0a70a2
CR-Id: ALPS05298037
Feature: [Module]Kernel Maintenance
Signed-off-by: Miles Chen <miles.chen@mediatek.com>
Source_Git_Sha: b02a80fdb8c099e32802a3af7854c2eb104302cd