soc: mediatek: fix allmodconfig build breaks
fix devmpu related allmodconfig build breaks

build command:
ARCH=arm64 make mrproper allmodconfig all

Errors:
drivers/soc/mediatek/devmpu/devmpu.c:17:10: error: 'devmpu.h' file not found with <angled> include; use "quotes" instead

Change-Id: I2cca8a1e4933e7e04b3c585c09302656f1bfd6eb
Cc: calvin.liao <calvin.liao@mediatek.com>
Signed-off-by: Miles Chen <miles.chen@mediatek.com>
Feature: Kernel SI Operation
CR-Id: ALPS05903624