Mtkcam: fix dma_buf_vmap build breaks
Errors:
drivers/misc/mediatek/cameraisp/dpe/isp_60/videobuf2-dma-contig.c:79:51: error: too few arguments to function call, expected 2, have 1
drivers/misc/mediatek/cameraisp/dpe/isp_60/videobuf2-dma-contig.c:357:10: error: incompatible pointer types initializing 'int (*)(struct dma_buf *, struct dma_buf_map *)' with an expression of type 'void *(struct dma_buf *)' [-Werror,-Wincompatible-pointer-types]

Change-Id: I4214af10dd1107091948df295747f5e66e0b5a73
Signed-off-by: Miles Chen <miles.chen@mediatek.com>
CR-Id: ALPS05568046
Feature: [Module]Kernel Maintenance