imgsensor: fix unused variable build breaks
Errors:
drivers/misc/mediatek/imgsensor/src/mt6853/seninf/seninf_clk.c:350:9: error: unused variable 'j' [-Werror,-Wunused-variable]

(cherry-picked from commit e7d509593ada472d97e50bd2bc5ee231746dd1f1)
Change-Id: I156d88e3077b51d26f4860929a65e1af95c8ce09
CR-Id: ALPS05511922
Feature: [Module]Kernel Maintenance
Signed-off-by: Miles Chen <miles.chen@mediatek.com>
(cherry picked from commit 7ceae447fbbac04a4fc31b6748400cf5cba28b55)