lpm: fix __nocfi build breaks
Error:
drivers/cpuidle/cpuidle.c:211:12: error: expected ';' after top level declarator

Change-Id: I351811fd60b1a6259dde5fc952b9c00e13dbba91
CR-Id: ALPS05372238
Feature: [Module]Kernel Maintenance
Signed-off-by: Miles Chen <miles.chen@mediatek.com>
(cherry picked from commit e0e9a3d3f359215653cc7445a5164cba6becd45e)