subpmic: fix mt6360_pmu_info build breaks
Error:
drivers/misc/mediatek/subpmic/mt6360-dbg.c:222:6: error: invalid argument type 'void' to unary expression
drivers/misc/mediatek/subpmic/mt6360-dbg.c:224:6: error: invalid argument type 'void' to unary expression
drivers/misc/mediatek/subpmic/mt6360-dbg.c:309:10: error: incomplete definition of type 'struct mt6360_pmu_info'

Signed-off-by: Miles Chen <miles.chen@mediatek.com>
Feature: [Module]Kernel Maintenance
Change-Id: I78d0112a47c695116428a5c902903e9ec5cfce84
CR-Id: ALPS05298037
Signed-off-by: Miles Chen <miles.chen@mediatek.com>
Source_Git_Sha: 51b9449fc39eaabd352a4f27567fb46871c4147e