scsi: ufs: ufs-mediatek: Fix build warnings with make W=1
Fix build warnings with make W=1 as below,

1.
>> drivers/scsi/ufs/ufs-mediatek.c:116:22: warning: format '%d' expects
>> argument of type 'int', but argument 4 has type 'long int'

2.
  CC [M]  drivers/scsi/ufs/ufs-mediatek.o
../drivers/scsi/ufs/ufs-mediatek.c:749: error: Cannot parse struct or union!

/** is used specifically with kernel-doc tool.
As a quick fix by removing dubious /** in the comment block of
struct ufs_hba_variant_ops ufs_hba_mtk_vops.

(cherry-picked from commit 47628740b302158672cdecb6a1b08c125a2e28ce)
Link: https://lore.kernel.org/r/20200910013756.11385-1-stanley.chu@mediatek.com
Signed-off-by: Stanley Chu <stanley.chu@mediatek.com>
Signed-off-by: Martin K. Petersen <martin.petersen@oracle.com>
Change-Id: Iabe0209bf535b6a289b5206f9cc88b85902ccfbd
CR-Id: ALPS05420447
Feature: UFS(Universal Flash Storage)
Signed-off-by: Miles Chen <miles.chen@mediatek.com>
(cherry picked from commit 711ba861679ea9e0ccc9e59ca98996b5c8da3c5c)