eemgpu: fix proc_create_data build breaks
Errors:
drivers/misc/mediatek/eemgpu/mtk_eemgpu.c:3128:16: error: incompatible pointer types passing 'const struct file_operations *' to parameter of type 'const struct proc_ops *' [-Werror,-Wincompatible-pointer-types]
drivers/misc/mediatek/eemgpu/mtk_eemgpu.c:3154:6: error: incompatible pointer types passing 'const struct file_operations *' to parameter of type 'const struct proc_ops *' [-Werror,-Wincompatible-pointer-types]

Change-Id: I5aba9b459ddf58aad8796ae1b50b0ba2f5e57ffe
CR-Id: ALPS05438846
Feature: [Module]Kernel Maintenance
Signed-off-by: Kuan-Ying Lee <Kuan-Ying.Lee@mediatek.com>