flashlight: fix allmodconfig build breaks
fix flashlight related allmodconfig build breaks

build command:
ARCH=arm64 make mrproper allmodconfig all

Errors:
drivers/misc/mediatek/flashlight/flashlights-mt6336.c:21:10: fatal error: 'mt6336/mt6336.h' file not found

Change-Id: Iecfa294ab1c3dcd8532f74c2bfcf67b0e67f8d0c
Cc: roger-hy.wang <roger-hy.wang@mediatek.com>
Signed-off-by: Miles Chen <miles.chen@mediatek.com>
Feature: Kernel SI Operation
CR-Id: ALPS05903624