FPSGO: fix unused variable build breaks
Errors:
drivers/misc/mediatek/performance/fpsgo_v3/fbt/src/fbt_cpu.c:2556:24: error: unused variable 'opp' [-Werror,-Wunused-variable]
drivers/misc/mediatek/performance/fpsgo_v3/fbt/src/fbt_cpu.c:2556:6: error: unused variable 'cpu' [-Werror,-Wunused-variable]
drivers/misc/mediatek/performance/fpsgo_v3/fbt/src/fbt_cpu.c:2558:25: error: unused variable 'policy' [-Werror,-Wunused-variable]

(cherry-picked from commit 91e6aefbf5a05f6146e8108719bfba87b6fd3642)
Change-Id: Ifaa489d9049555365077b2c7caa16a0777026567
CR-Id: ALPS05511922
Feature: [Module]Kernel Maintenance
Signed-off-by: Miles Chen <miles.chen@mediatek.com>
(cherry picked from commit e9b5c2b81ac043e0538fd7f5105c61bdd585ef7f)