wmt: fix timesepc and proc_create build breaks
Error:
drivers/misc/mediatek/btif/common/inc/mtk_btif.h:156:17: error: field has incomplete type 'struct timeval'
drivers/misc/mediatek/btif/common/inc/mtk_btif.h:157:18: error: field has incomplete type 'struct timespec'
_00/merged/kernel-5.4/drivers/misc/mediatek/btif/common/mtk_btif.c:201:42: error: array has incomplete element type 'struct timeval'
include/linux/sched/debug.h:33:13: error: conflicting types for 'show_stack'
drivers/misc/mediatek/btif/common/mtk_btif.c:1731:17: error: variable has incomplete type 'struct timeval'
drivers/misc/mediatek/btif/common/mtk_btif.c:1732:17: error: variable has incomplete type 'struct timeval'
drivers/misc/mediatek/btif/common/mtk_btif.c:2178:17: error: variable has incomplete type 'struct timeval'
drivers/misc/mediatek/btif/common/inc/mtk_btif.h:156:17: error: field has incomplete type 'struct timeval'
drivers/misc/mediatek/btif/common/inc/mtk_btif.h:157:18: error: field has incomplete type 'struct timespec'
drivers/misc/mediatek/btif/common/mtk_btif.c:2970:10: error: implicit declaration of function 'ktime_to_timespec' [-Werror,-Wimplicit-function-declaration]
drivers/misc/mediatek/btif/common/mtk_btif.c:2990:22: error: incomplete definition of type 'struct timeval'
drivers/misc/mediatek/btif/common/mtk_btif.c:2990:44: error: incomplete definition of type 'struct timeval'
drivers/misc/mediatek/btif/common/mtk_btif.c:2991:20: error: incomplete definition of type 'struct timespec'
drivers/misc/mediatek/btif/common/mtk_btif.c:2991:34: error: incomplete definition of type 'struct timespec'
drivers/misc/mediatek/btif/common/mtk_btif.c:3033:16: error: incomplete definition of type 'struct timeval'
drivers/misc/mediatek/btif/common/mtk_btif.c:3034:16: error: incomplete definition of type 'struct timeval'
drivers/misc/mediatek/btif/common/mtk_btif.c:3035:19: error: incomplete definition of type 'struct timespec'
drivers/misc/mediatek/btif/common/mtk_btif.c:3036:8: error: incomplete definition of type 'struct timespec'
drivers/misc/mediatek/btif/common/mtk_btif.c:3577:4: error: incomplete definition of type 'struct timeval'
drivers/misc/mediatek/btif/common/mtk_btif.c:3578:4: error: incomplete definition of type 'struct timeval'
drivers/misc/mediatek/conn_md/conn_md_dbg.c:132:17: error: incompatible pointer types passing 'const struct file_operations *' to parameter of type 'const struct proc_ops *' [-Werror,-Wincompatible-pointer-types]
drivers/misc/mediatek/btif/common/inc/mtk_btif.h:156:17: error: field has incomplete type 'struct timeval'
drivers/misc/mediatek/btif/common/inc/mtk_btif.h:157:18: error: field has incomplete type 'struct timespec'
drivers/misc/mediatek/btif/common/btif_dma_plat.c:746:24: error: variable has incomplete type 'struct timeval'
drivers/misc/mediatek/btif/common/btif_dma_plat.c:747:24: error: variable has incomplete type 'struct timeval'
drivers/misc/mediatek/btif/common/inc/mtk_btif.h:156:17: error: field has incomplete type 'struct timeval'
157:18: error: field has incomplete type 'struct timespec'

Signed-off-by: Miles Chen <miles.chen@mediatek.com>
Change-Id: Ia22e0bb9c1cba998d3a0ffa0081c4fc9dc8a6565
CR-Id: ALPS05298037
Feature: [Module]Kernel Maintenance
Signed-off-by: Miles Chen <miles.chen@mediatek.com>
Source_Git_Sha: 60ed63816dc09fa55b8677195f5fb4cde59a827a