leakage_table: fix unused variable build breaks
Errors:
drivers/misc/mediatek/leakage_table/mtk_static_power.c:125:5: error: 'SPOWERTABLE' is not defined, evaluates to 0 [-Werror,-Wundef]
drivers/misc/mediatek/leakage_table/mtk_static_power.c:517:5: error: 'SPOWERTABLE' is not defined, evaluates to 0 [-Werror,-Wundef]
drivers/misc/mediatek/leakage_table/mtk_static_power.c:524:5: error: 'SPOWERTABLE' is not defined, evaluates to 0 [-Werror,-Wundef]
drivers/misc/mediatek/leakage_table/mtk_static_power.c:529:5: error: 'SPOWERTABLE' is not defined, evaluates to 0 [-Werror,-Wundef]
drivers/misc/mediatek/leakage_table/mtk_static_power.c:552:5: error: 'SPOWERTABLE' is not defined, evaluates to 0 [-Werror,-Wundef]
drivers/misc/mediatek/leakage_table/mtk_static_power.c:577:5: error: 'SPOWERTABLE' is not defined, evaluates to 0 [-Werror,-Wundef]
drivers/misc/mediatek/leakage_table/mtk_static_power.c:586:5: error: 'SPOWERTABLE' is not defined, evaluates to 0 [-Werror,-Wundef]
drivers/misc/mediatek/leakage_table/mtk_static_power.c:617:5: error: 'SPOWERTABLE' is not defined, evaluates to 0 [-Werror,-Wundef]
drivers/misc/mediatek/leakage_table/mtk_static_power.c:501:22: error: unused variable 'tab' [-Werror,-Wunused-variable]
drivers/misc/mediatek/leakage_table/mtk_static_power.c:504:24: error: unused variable 'spower_value_1' [-Werror,-Wunused-variable]
drivers/misc/mediatek/leakage_table/mtk_static_power.c:504:7: error: unused variable 'spower_value_0' [-Werror,-Wunused-variable]
drivers/misc/mediatek/leakage_table/mtk_static_power.c:502:23: error: unused variable 'spower' [-Werror,-Wunused-variable]
drivers/misc/mediatek/leakage_table/mtk_static_power.c:506:7: error: unused variable 'cell_name' [-Werror,-Wunused-variable]
drivers/misc/mediatek/leakage_table/mtk_static_power.c:504:41: error: unused variable 'spower_value_2' [-Werror,-Wunused-variable]

(cherry-picked from commit d7513320798ef5e5e14b195f9c515ecb4042ae53)
Change-Id: I7d672fcec7286ce1c56c85e811ffb2a5c207d47a
CR-Id: ALPS05511922
Feature: [Module]Kernel Maintenance
Signed-off-by: Miles Chen <miles.chen@mediatek.com>