drm/panel: nt36672a/nt35695b: fix drm build breaks
Errors:
drivers/gpu/drm/panel/panel-nt36672a-rt4801-vdo.c:7:10: fatal error: 'drm/drmP.h' file not found
drivers/gpu/drm/panel/panel-nt36672a-rt4801-vdo.c:211:2: error: implicit declaration of function 'udelay' [-Werror,-Wimplicit-function-declaration]
drivers/gpu/drm/panel/panel-nt36672a-rt4801-vdo.c:469:2: error: implicit declaration of function 'msleep' [-Werror,-Wimplicit-function-declaration]
drivers/gpu/drm/panel/panel-nt36672a-rt4801-vdo.c:499:2: error: implicit declaration of function 'msleep' [-Werror,-Wimplicit-function-declaration]
drivers/gpu/drm/panel/panel-nt36672a-rt4801-vdo.c:529:2: error: implicit declaration of function 'udelay' [-Werror,-Wimplicit-function-declaration]
drivers/gpu/drm/panel/panel-nt36672a-rt4801-vdo.c:567:2: error: implicit declaration of function 'udelay' [-Werror,-Wimplicit-function-declaration]
drivers/gpu/drm/panel/panel-nt36672a-rt4801-vdo.c:623:38: error: variable has incomplete type 'const struct drm_display_mode'
drivers/gpu/drm/panel/panel-nt36672a-rt4801-vdo.c:739:9: error: implicit declaration of function 'drm_mode_duplicate' [-Werror,-Wimplicit-function-declaration]
drivers/gpu/drm/panel/panel-nt36672a-rt4801-vdo.c:739:35: error: no member named 'drm' in 'struct drm_panel'
drivers/gpu/drm/panel/panel-nt36672a-rt4801-vdo.c:741:19: error: no member named 'drm' in 'struct drm_panel'
drivers/gpu/drm/panel/panel-nt36672a-rt4801-vdo.c:747:2: error: implicit declaration of function 'drm_mode_set_name' [-Werror,-Wimplicit-function-declaration]
drivers/gpu/drm/panel/panel-nt36672a-rt4801-vdo.c:748:6: error: incomplete definition of type 'struct drm_display_mode'
drivers/gpu/drm/panel/panel-nt36672a-rt4801-vdo.c:748:15: error: use of undeclared identifier 'DRM_MODE_TYPE_DRIVER'
drivers/gpu/drm/panel/panel-nt36672a-rt4801-vdo.c:748:38: error: use of undeclared identifier 'DRM_MODE_TYPE_PREFERRED'
drivers/gpu/drm/panel/panel-nt36672a-rt4801-vdo.c:749:2: error: implicit declaration of function 'drm_mode_probed_add' [-Werror,-Wimplicit-function-declaration]
drivers/gpu/drm/panel/panel-nt36672a-rt4801-vdo.c:749:29: error: no member named 'connector' in 'struct drm_panel'
drivers/gpu/drm/panel/panel-nt36672a-rt4801-vdo.c:751:9: error: no member named 'connector' in 'struct drm_panel'

drivers/gpu/drm/panel/panel-nt36672a-rt4801-vdo.c:762:15: error: incompatible pointer types initializing 'int (*)(struct drm_panel *, struct drm_connector *)' with an expression of type 'int (struct drm_panel *)' [-Werror,-Wincompatible-pointer-types]
drivers/gpu/drm/panel/panel-nt36672a-rt4801-vdo.c:839:28: error: too few arguments to function call, expected 4, have 1

Change-Id: I6e3fbe3a554da99a8f696b7ffe98a5fccbbfbafb
CR-Id: ALPS05489813
Feature: [Module]Kernel Maintenance
Signed-off-by: Miles Chen <miles.chen@mediatek.com>