genirq: tmp export irq_to_desc to fix build breaks
Errors:
ERROR: modpost: "irq_to_desc" [drivers/power/supply/mt6359p_battery.ko] undefined!
ERROR: modpost: "irq_to_desc" [drivers/input/touchscreen/GT9896S/gt9896s.ko] undefined!
ERROR: modpost: "irq_to_desc" [drivers/input/touchscreen/GT9886/gt9886.ko] undefined!
ERROR: modpost: "irq_to_desc" [drivers/misc/mediatek/lpm/modules/platform/mtk-lpm-plat-mt6873.ko] undefined!
ERROR: modpost: "irq_to_desc" [drivers/misc/mediatek/lpm/mtk-lpm.ko] undefined!
ERROR: modpost: "irq_to_desc" [drivers/misc/mediatek/mtprof/irq_monitor.ko] undefined!

Change-Id: I1eb30918ae09569c5db11ecd5f5b07fb347ec11d
Signed-off-by: Miles Chen <miles.chen@mediatek.com>
CR-Id: ALPS05568046
Feature: [Module]Kernel Maintenance