scsi: ufs-mediatek-dbg: fix struct ufs_err_reg_hist build breaks
Errors:
drivers/scsi/ufs/ufs-mediatek-dbg.c:41:14: error: declaration of 'struct ufs_err_reg_hist' will not be visible outside of this function [-Werror,-Wvisibility]
drivers/scsi/ufs/ufs-mediatek-dbg.c:47:18: error: use of undeclared identifier 'UFS_ERR_REG_HIST_LENGTH'
drivers/scsi/ufs/ufs-mediatek-dbg.c:48:24: error: incomplete definition of type 'struct ufs_err_reg_hist'
drivers/scsi/ufs/ufs-mediatek-dbg.c:48:33: error: use of undeclared identifier 'UFS_ERR_REG_HIST_LENGTH'
drivers/scsi/ufs/ufs-mediatek-dbg.c:50:15: error: incomplete definition of type 'struct ufs_err_reg_hist'
drivers/scsi/ufs/ufs-mediatek-dbg.c:54:18: error: incomplete definition of type 'struct ufs_err_reg_hist'
drivers/scsi/ufs/ufs-mediatek-dbg.c:55:30: error: incomplete definition of type 'struct ufs_err_reg_hist'
drivers/scsi/ufs/ufs-mediatek-dbg.c:54:18: error: incomplete definition of type 'struct ufs_err_reg_hist'
drivers/scsi/ufs/ufs-mediatek-dbg.c:55:30: error: incomplete definition of type 'struct ufs_err_reg_hist'
drivers/scsi/ufs/ufs-mediatek-dbg.c:54:18: error: incomplete definition of type 'struct ufs_err_reg_hist'
drivers/scsi/ufs/ufs-mediatek-dbg.c:55:30: error: incomplete definition of type 'struct ufs_err_reg_hist'
drivers/scsi/ufs/ufs-mediatek-dbg.c:144:26: error: no member named 'pa_err' in 'struct ufs_stats'
drivers/scsi/ufs/ufs-mediatek-dbg.c:146:26: error: no member named 'dl_err' in 'struct ufs_stats'
drivers/scsi/ufs/ufs-mediatek-dbg.c:148:26: error: no member named 'nl_err' in 'struct ufs_stats'
drivers/scsi/ufs/ufs-mediatek-dbg.c:150:26: error: no member named 'tl_err' in 'struct ufs_stats'
drivers/scsi/ufs/ufs-mediatek-dbg.c:152:26: error: no member named 'dme_err' in 'struct ufs_stats'
drivers/scsi/ufs/ufs-mediatek-dbg.c:154:26: error: no member named 'auto_hibern8_err' in 'struct ufs_stats'
drivers/scsi/ufs/ufs-mediatek-dbg.c:157:26: error: no member named 'fatal_err' in 'struct ufs_stats'
drivers/scsi/ufs/ufs-mediatek-dbg.c:159:26: error: no member named 'link_startup_err' in 'struct ufs_stats'

Change-Id: I0817cf501e334edaf8cef603a314f7043a27430e
Signed-off-by: Miles Chen <miles.chen@mediatek.com>
CR-Id: ALPS05568046
Feature: [Module]Kernel Maintenance