apusys: fix dma_buf_k(un)map build breaks
dma_buf_k(un)map are not available not, replace
them with proper dma_buf_v(un)map.

Errors:
drivers/misc/mediatek/apusys/midware/1.5/mdw_mem_aosp.c:114:11: error: implicit declaration of function 'dma_buf_kmap' [-Werror,-Wimplicit-function-declaration]
drivers/misc/mediatek/apusys/midware/1.5/mdw_mem_aosp.c:235:2: error: implicit declaration of function 'dma_buf_kunmap' [-Werror,-Wimplicit-function-declaration]

Signed-off-by: Miles Chen <miles.chen@mediatek.com>
Change-Id: I5213a341732b4452306b424d50b10d0445170253
CR-Id: ALPS05298037
Feature: [Module]Kernel Maintenance
Signed-off-by: Miles Chen <miles.chen@mediatek.com>