ASoC: fix allmodconfig build breaks
fix ASoC related allmodconfig build errors

build command:
ARCH=arm64 make mrproper allmodconfig all

Errors:
sound/soc/mediatek/audio_dsp/mtk-dsp-common.c:18:10: error: 'mtk-dsp-mem-control.h' file not found with <angled> include; use "quotes" instead
sound/soc/mediatek/audio_dsp/mtk-dsp-common.c:19:10: error: 'mtk-base-dsp.h' file not found with <angled> include; use "quotes" instead
sound/soc/mediatek/audio_dsp/mtk-dsp-common.c:20:10: error: 'mtk-dsp-common.h' file not found with <angled> include; use "quotes" instead

Change-Id: I535e1ddb9d49f242deb419cd1ebd202dfabc298d
Cc: chipeng chang <chipeng.chang@mediatek.com>
Cc: Shane.Chien <shane.chien@mediatek.com>
Signed-off-by: Miles Chen <miles.chen@mediatek.com>
Feature: Kernel SI Operation
CR-Id: ALPS05903624