drm/panel: nt35695b: fix drm build breaks
Errors:
drivers/gpu/drm/panel/panel-nt35695b-auo-vdo.c:7:10: fatal error: 'drm/drmP.h' file not found
drivers/gpu/drm/panel/panel-nt35695b-auo-vdo.c:211:2: error: implicit declaration of function 'udelay' [-Werror,-Wimplicit-function-declaration]
drivers/gpu/drm/panel/panel-nt35695b-auo-vdo.c:743:2: error: implicit declaration of function 'msleep' [-Werror,-Wimplicit-function-declaration]
drivers/gpu/drm/panel/panel-nt35695b-auo-vdo.c:775:2: error: implicit declaration of function 'msleep' [-Werror,-Wimplicit-function-declaration]
drivers/gpu/drm/panel/panel-nt35695b-auo-vdo.c:805:2: error: implicit declaration of function 'udelay' [-Werror,-Wimplicit-function-declaration]
drivers/gpu/drm/panel/panel-nt35695b-auo-vdo.c:843:2: error: implicit declaration of function 'udelay' [-Werror,-Wimplicit-function-declaration]
drivers/gpu/drm/panel/panel-nt35695b-auo-vdo.c:903:32: error: variable has incomplete type 'struct drm_display_mode'
drivers/gpu/drm/panel/panel-nt35695b-auo-vdo.c:1037:7: error: incomplete definition of type 'struct drm_display_mode'
drivers/gpu/drm/panel/panel-nt35695b-auo-vdo.c:1038:7: error: incomplete definition of type 'struct drm_display_mode'
drivers/gpu/drm/panel/panel-nt35695b-auo-vdo.c:1039:7: error: incomplete definition of type 'struct drm_display_mode'
drivers/gpu/drm/panel/panel-nt35695b-auo-vdo.c:1040:7: error: incomplete definition of type 'struct drm_display_mode'
drivers/gpu/drm/panel/panel-nt35695b-auo-vdo.c:1043:7: error: incomplete definition of type 'struct drm_display_mode'
drivers/gpu/drm/panel/panel-nt35695b-auo-vdo.c:1044:7: error: incomplete definition of type 'struct drm_display_mode'
drivers/gpu/drm/panel/panel-nt35695b-auo-vdo.c:1045:7: error: incomplete definition of type 'struct drm_display_mode'
drivers/gpu/drm/panel/panel-nt35695b-auo-vdo.c:1046:7: error: incomplete definition of type 'struct drm_display_mode'
drivers/gpu/drm/panel/panel-nt35695b-auo-vdo.c:1056:9: error: implicit declaration of function 'drm_mode_duplicate' [-Werror,-Wimplicit-function-declaration]
drivers/gpu/drm/panel/panel-nt35695b-auo-vdo.c:1056:35: error: no member named 'drm' in 'struct drm_panel'
drivers/gpu/drm/panel/panel-nt35695b-auo-vdo.c:1058:19: error: no member named 'drm' in 'struct drm_panel'
drivers/gpu/drm/panel/panel-nt35695b-auo-vdo.c:1064:2: error: implicit declaration of function 'drm_mode_set_name' [-Werror,-Wimplicit-function-declaration]
drivers/gpu/drm/panel/panel-nt35695b-auo-vdo.c:1065:6: error: incomplete definition of type 'struct drm_display_mode'
fatal error: too many errors emitted, stopping now [-ferror-limit=]

Change-Id: I15f07e43c3108f485c199c1660275c5b16a8b400
Signed-off-by: Miles Chen <miles.chen@mediatek.com>
CR-Id: ALPS05495269
Feature: [Module]Kernel Maintenance
(cherry picked from commit 2c05a63fff40aecb2e82199d500bffefadbd7734)