sensor: fix proc_create_data build break
Error:
drivers/misc/mediatek/sensor/2.0/core/hf_manager.c:1397:4: error: incompatible pointer types passing 'const struct file_operations *' to parameter of type 'const struct proc_ops *' [-Werror,-Wincompatible-pointer-types]

Change-Id: Iaff0b6a23b2d4711fd01e371bb207d0cddd2c0b1
CR-Id: ALPS05438846
Feature: [Module]Kernel Maintenance
Signed-off-by: Kuan-Ying Lee <Kuan-Ying.Lee@mediatek.com>
(cherry picked from commit 7da6ff4082aa076b1468fe9c3fc32d8e84763cf5)