platform: mtk-aie: fix sometimes-uninitialized variable build breaks
Errors:
drivers/media/platform/mtk-aie/mtk_aie_drv.c:1091:13: error: variable 'yuv2rgb_cfg' is used uninitialized whenever 'if' condition is false [-Werror,-Wsometimes-uninitialized]
drivers/media/platform/mtk-aie/mtk_aie_drv.c:1091:13: error: variable 'src_crop_w' is used uninitialized whenever 'if' condition is false [-Werror,-Wsometimes-uninitialized]
drivers/media/platform/mtk-aie/mtk_aie_drv.c:1091:13: error: variable 'pym0_out_w' is used uninitialized whenever 'if' condition is false [-Werror,-Wsometimes-uninitialized]
drivers/media/platform/mtk-aie/mtk_aie_drv.c:1091:13: error: variable 'src_crop_h' is used uninitialized whenever 'if' condition is false [-Werror,-Wsometimes-uninitialized]
drivers/media/platform/mtk-aie/mtk_aie_drv.c:1083:6: error: variable 'srcbuf_UV' is used uninitialized whenever 'if' condition is false [-Werror,-Wsometimes-uninitialized]
drivers/media/platform/mtk-aie/mtk_aie_drv.c:1100:6: error: variable 'xmag_0' is used uninitialized whenever 'if' condition is false [-Werror,-Wsometimes-uninitialized]
drivers/media/platform/mtk-aie/mtk_aie_drv.c:1100:6: error: variable 'ymag_0' is used uninitialized whenever 'if' condition is false [-Werror,-Wsometimes-uninitialized]
drivers/media/platform/mtk-aie/mtk_aie_drv.c:1258:13: error: variable 'src_crop_h' is used uninitialized whenever 'if' condition is false [-Werror,-Wsometimes-uninitialized]
drivers/media/platform/mtk-aie/mtk_aie_drv.c:1258:13: error: variable 'src_crop_w' is used uninitialized whenever 'if' condition is false [-Werror,-Wsometimes-uninitialized]
drivers/media/platform/mtk-aie/mtk_aie_drv.c:1350:13: error: variable 'src_crop_w' is used uninitialized whenever 'if' condition is false [-Werror,-Wsometimes-uninitialized]
drivers/media/platform/mtk-aie/mtk_aie_drv.c:1350:13: error: variable 'src_crop_h' is used uninitialized whenever 'if' condition is false [-Werror,-Wsometimes-uninitialized]

(cherry-picked from commit e14e5223b0bea11fead9bdb4275d107b9f4ae146)
Change-Id: I94c9d56d539af7a70373def26b6ee2925544904c
CR-Id: ALPS05511922
Feature: [Module]Kernel Maintenance
Signed-off-by: Miles Chen <miles.chen@mediatek.com>
(cherry picked from commit afed109c90ecb7a08ce9ca32c1f39b466ed8562b)