[ALPS05111942] Audio: ADSP usage refactor for mt6873
[Error]
ld.lld: error: undefined symbol: adsp_enable_dsp_clk
>>> referenced by mtk_sys_timer.c:300
ld.lld: error: undefined symbol: adsp_A_register_notify
>>> referenced by mtk-usip.c:322
error: undefined symbol: adsp_A_register_notify
>>> referenced by mtk-usip.c

[Detail]
The common use for ADSP is refactored from mt6785 base to
mt6873 base. With some application side(timer,usip) we
replaced or deprecated legacy usage.

MTK-Commit-Id: a5a12223dbc5ac472185b6f6ecf8437c464dedae

Change-Id: I334ce9bda9e29cb35b24ea1a99a8bd11eca1d647
Signed-off-by: Juju Sung <juju.sung@mediatek.com>
CR-Id: ALPS05111942
Feature: [Module]Kernel Maintenance