sda: Fix the error on casting void pointer to int
When using clang with options '-Werror,-Wvoid-pointer-to-int-cast',
there is the compile error.
        error: cast to smaller integer type 'int' from 'const void *'

Use the C99 uintptr_t to cast first.

(cherry-picked from commit 8e91756430236875c284caba15227e6f523fa278)
Signed-off-by: cc.hwang <cc.hwang@mediatek.com>
Change-Id: I4ebb45f91933098850a206352d1c1b8b9f6fd173
CR-Id: ALPS05539426
Feature: External Memory Interface(emi)
Signed-off-by: Kuan-Ying Lee <Kuan-Ying.Lee@mediatek.com>