[ALPS04380679] perfmgr: eas_ctrl: add trace log size
To prevent the log from overflow as folowings
eas_ctrl.c: In function update_eas_uclamp_min:
eas_ctrl.c:377:2: error: specified bound 128 equals
the size of the destination
[-Werror=stringop-overflow=]
|   strncat(msg, msg1, LOG_BUF_SIZE);
|   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

MTK-Commit-Id: f94d230c70df108d56464843a5e8a4fd453f984e

Change-Id: Ia31133966962e39e8754b71b98b11732628c7648
CR-Id: ALPS04380679
Feature: [Module]PowerHAL
Signed-off-by: Andrew-CT Chen <andrew-ct.chen@mediatek.com>
(cherry picked from commit 512dfd7cbfd39c08296d49b326d31e99e8fc2de4)
(cherry picked from commit eda2249dd81be8645d43adc549c84ffe2fa0ef31)