touchscreen: fix unused function build breaks
Errors:
drivers/input/touchscreen/GT9886/goodix_ts_i2c.c:1918:22: error: variable length array used [-Werror,-Wvla]
drivers/input/touchscreen/GT9896S/goodix_cfg_bin.h:118:12: error: unused function 'gt9896s_parse_cfg_bin' [-Werror,-Wunused-function]
drivers/input/touchscreen/GT9896S/goodix_cfg_bin.h:120:12: error: unused function 'gt9896s_get_reg_and_cfg' [-Werror,-Wunused-function]
drivers/input/touchscreen/GT9896S/goodix_cfg_bin.h:123:12: error: unused function 'gt9896s_read_cfg_bin' [-Werror,-Wunused-function]
drivers/input/touchscreen/GT9896S/goodix_cfg_bin.h:126:13: error: unused function 'gt9896s_cfg_pkg_leToCpu' [-Werror,-Wunused-function]
drivers/input/touchscreen/GT9896S/goodix_gtx8_update.c:1621:13: error: unused function 'gt9896s_fwu_module_exit' [-Werror,-Wunused-function]
drivers/input/touchscreen/GT9886/goodix_gtx8_update.c:1513:13: error: unused function 'goodix_fwu_module_exit' [-Werror,-Wunused-function]
drivers/input/touchscreen/GT9896S/goodix_ts_core.c:1738:13: error: unused function 'gt9896s_ts_release_connects' [-Werror,-Wunused-function]

(cherry-picked from commit 61674b28d8c6e2f8bcaa06d9ba1173448bc0efc3)
Change-Id: I48187072478f49b93a7e52edf146dfc8da1142dd
CR-Id: ALPS05511922
Feature: [Module]Kernel Maintenance
Signed-off-by: Miles Chen <miles.chen@mediatek.com>