apusys: fix unused variable gov_data build breaks
Errors:
/mfs/mtkslt0480/mtk04267/CAS_REAL/alps-dev-r0.bsp-common-kernel-5.4--2020_12_31_02_00-6853-cleanup/merged/kernel-5.4/drivers/misc/mediatek/apusys/power/2.5/common/apu-regulator.c:102:23: error: unused variable 'pgov_data' [-Werror,-Wunused-variable]
/mfs/mtkslt0480/mtk04267/CAS_REAL/alps-dev-r0.bsp-common-kernel-5.4--2020_12_31_02_00-6853-cleanup/merged/kernel-5.4/drivers/misc/mediatek/apusys/power/2.5/common/apu-dbg.c:134:23: error: unused variable 'gov_data' [-Werror,-Wunused-variable]
/mfs/mtkslt0480/mtk04267/CAS_REAL/alps-dev-r0.bsp-common-kernel-5.4--2020_12_31_02_00-6853-cleanup/merged/kernel-5.4/drivers/misc/mediatek/apusys/power/2.5/common/apu-dbg.c:146:23: error: unused variable 'gov_data' [-Werror,-Wunused-variable]

(cherry-picked from commit 582219c0583182ea824b33f7c175c43cbf91ed98)
Change-Id: I0f51d36ba65cc93da260cca4cb124d7d32e0c159
CR-Id: ALPS05511922
Feature: [Module]Kernel Maintenance
Signed-off-by: Miles Chen <miles.chen@mediatek.com>
(cherry picked from commit d8b2157ac4ace29a1b44e0587f42376a38ccac1d)