apusys: fix DEVFREQ_GOV_INTERVAL build breaks
Errors:
drivers/misc/mediatek/apusys/power/2.5/governor/gov-apusys-pe.c:196:7: error: use of undeclared identifier 'DEVFREQ_GOV_INTERVAL'
drivers/misc/mediatek/apusys/power/2.5/governor/gov-apusys-pe.c:197:3: error: implicit declaration of function 'devfreq_interval_update' [-Werror,-Wimplicit-function-declaration]

Change-Id: I7881c629c8836b42e764b269465427a0084d7a34
Signed-off-by: Miles Chen <miles.chen@mediatek.com>
CR-Id: ALPS05694233
Feature: [Module]Kernel Maintenance