Lens: fix kzfree not found build break
Errors:
drivers/misc/mediatek/lens/v4l2/media/mtk-composite.c:257:2: error: implicit declaration of function 'kzfree' [-Werror,-Wimplicit-function-declaration]

Change-Id: I3fe1255548b1c250e338de9399f4963241729bc0
CR-Id: ALPS05431666
Feature: [Module]Kernel Maintenance
Signed-off-by: Miles Chen <miles.chen@mediatek.com>
(cherry picked from commit 57391c8a4022dae593508fee6056faf54b125994)