typec: tcpc: fix struct device_connection build breaks
Error:
drivers/misc/mediatek/typec/tcpc/inc/tcpci_core.h:410:27: error: field has incomplete type 'struct device_connection'
drivers/misc/mediatek/typec/tcpc/inc/tcpci_core.h:410:27: error: field has incomplete type 'struct device_connection'
drivers/misc/mediatek/typec/tcpc/inc/tcpci_core.h:410:27: error: field has incomplete type 'struct device_connection'
drivers/misc/mediatek/typec/tcpc/inc/tcpci_core.h:410:27: error: field has incomplete type 'struct device_connection'
drivers/misc/mediatek/typec/tcpc/inc/tcpci_core.h:410:27: error: field has incomplete type 'struct device_connection'
drivers/misc/mediatek/typec/tcpc/inc/tcpci_core.h:410:27: error: field has incomplete type 'struct device_connection'
drivers/misc/mediatek/typec/tcpc/inc/tcpci_core.h:410:27: error: field has incomplete type 'struct device_connection'
drivers/misc/mediatek/typec/tcpc/inc/tcpci_core.h:410:27: error: field has incomplete type 'struct device_connection'
drivers/misc/mediatek/typec/tcpc/inc/tcpci_core.h:410:27: error: field has incomplete type 'struct device_connection'
drivers/misc/mediatek/typec/tcpc/tcpci_dual_role.c:207:3: error: implicit declaration of function 'device_connection_add' [-Werror,-Wimplicit-function-declaration]
drivers/misc/mediatek/typec/tcpc/inc/tcpci_core.h:410:27: error: field has incomplete type 'struct device_connection'
drivers/misc/mediatek/typec/tcpc/inc/tcpci_core.h:410:27: error: field has incomplete type 'struct device_connection'
drivers/misc/mediatek/typec/tcpc/inc/tcpci_core.h:410:27: error: field has incomplete type 'struct device_connection'
drivers/misc/mediatek/typec/tcpc/inc/tcpci_core.h:410:27: error: field has incomplete type 'struct device_connection'
drivers/misc/mediatek/typec/tcpc/inc/tcpci_core.h:410:27: error: field has incomplete type 'struct device_connection'
drivers/misc/mediatek/typec/tcpc/inc/tcpci_core.h:410:27: error: field has incomplete type 'struct device_connection'
drivers/misc/mediatek/typec/tcpc/inc/tcpci_core.h:410:27: error: field has incomplete type 'struct device_connection'
drivers/misc/mediatek/typec/tcpc/inc/tcpci_core.h:410:27: error: field has incomplete type 'struct device_connection'
drivers/misc/mediatek/typec/tcpc/inc/tcpci_core.h:410:27: error: field has incomplete type 'struct device_connection'
drivers/misc/mediatek/typec/tcpc/inc/tcpci_core.h:410:27: error: field has incomplete type 'struct device_connection'
drivers/misc/mediatek/typec/tcpc/inc/tcpci_core.h:410:27: error: field has incomplete type 'struct device_connection'
drivers/misc/mediatek/typec/tcpc/inc/tcpci_core.h:410:27: error: field has incomplete type 'struct device_connection'
drivers/misc/mediatek/typec/tcpc/inc/tcpci_core.h:410:27: error: field has incomplete type 'struct device_connection'
drivers/misc/mediatek/typec/tcpc/inc/tcpci_core.h:410:27: error: field has incomplete type 'struct device_connection'
drivers/misc/mediatek/typec/tcpc/inc/tcpci_core.h:410:27: error: field has incomplete type 'struct device_connection'
drivers/misc/mediatek/typec/tcpc/inc/tcpci_core.h:410:27: error: field has incomplete type 'struct device_connection'
drivers/misc/mediatek/typec/tcpc/inc/tcpci_core.h:410:27: error: field has incomplete type 'struct device_connection'
drivers/misc/mediatek/typec/tcpc/inc/tcpci_core.h:410:27: error: field has incomplete type 'struct device_connection'
drivers/misc/mediatek/typec/tcpc/inc/tcpci_core.h:410:27: error: field has incomplete type 'struct device_connection'
drivers/misc/mediatek/typec/tcpc/inc/tcpci_core.h:410:27: error: field has incomplete type 'struct device_connection'
drivers/misc/mediatek/typec/tcpc/inc/tcpci_core.h:410:27: error: field has incomplete type 'struct device_connection'
drivers/misc/mediatek/typec/tcpc/inc/tcpci_core.h:410:27: error: field has incomplete type 'struct device_connection'
drivers/misc/mediatek/typec/tcpc/inc/tcpci_core.h:410:27: error: field has incomplete type 'struct device_connection'
drivers/misc/mediatek/typec/tcpc/inc/tcpci_core.h:410:27: error: field has incomplete type 'struct device_connection'
drivers/misc/mediatek/typec/tcpc/inc/tcpci_core.h:410:27: error: field has incomplete type 'struct device_connection'
drivers/misc/mediatek/typec/tcpc/inc/tcpci_core.h:410:27: error: field has incomplete type 'struct device_connection'
drivers/misc/mediatek/typec/tcpc/inc/tcpci_core.h:410:27: error: field has incomplete type 'struct device_connection'
drivers/misc/mediatek/typec/tcpc/inc/tcpci_core.h:410:27: error: field has incomplete type 'struct device_connection'
drivers/misc/mediatek/typec/tcpc/inc/tcpci_core.h:410:27: error: field has incomplete type 'struct device_connection'

Change-Id: Ia51e4e9493bfeb8b914795e4a0ef3fa03510ee3a
CR-Id: ALPS05431666
Feature: [Module]Kernel Maintenance
Signed-off-by: Miles Chen <miles.chen@mediatek.com>