ASoC: mediatek: symmetric_rates build breaks
Errors:
sound/soc/mediatek/mt6873/mt6873-dai-hw-gain.c:198:4: error: field designator 'symmetric_rates' does not refer to any field in type 'struct snd_soc_dai_driver'; did you mean 'symmetric_rate'?
sound/soc/mediatek/mt6873/mt6873-dai-hw-gain.c:200:4: error: field designator 'symmetric_samplebits' does not refer to any field in type 'struct snd_soc_dai_driver'; did you mean 'symmetric_sample_bits'?
sound/soc/mediatek/mt6873/mt6873-dai-hw-gain.c:220:4: error: field designator 'symmetric_rates' does not refer to any field in type 'struct snd_soc_dai_driver'; did you mean 'symmetric_rate'?
sound/soc/mediatek/mt6873/mt6873-dai-hw-gain.c:222:4: error: field designator 'symmetric_samplebits' does not refer to any field in type 'struct snd_soc_dai_driver'; did you mean 'symmetric_sample_bits'?
sound/soc/mediatek/mt6873/mt6873-dai-hw-gain.c:239:25: error: invalid application of 'sizeof' to an incomplete type 'struct snd_soc_dai_driver []'
sound/soc/mediatek/mt6873/mt6873-dai-pcm.c:362:4: error: field designator 'symmetric_rates' does not refer to any field in type 'struct snd_soc_dai_driver'; did you mean 'symmetric_rate'?
sound/soc/mediatek/mt6873/mt6873-dai-pcm.c:363:4: error: field designator 'symmetric_samplebits' does not refer to any field in type 'struct snd_soc_dai_driver'; did you mean 'symmetric_sample_bits'?
sound/soc/mediatek/mt6873/mt6873-dai-pcm.c:383:4: error: field designator 'symmetric_rates' does not refer to any field in type 'struct snd_soc_dai_driver'; did you mean 'symmetric_rate'?
sound/soc/mediatek/mt6873/mt6873-dai-pcm.c:384:4: error: field designator 'symmetric_samplebits' does not refer to any field in type 'struct snd_soc_dai_driver'; did you mean 'symmetric_sample_bits'?
sound/soc/mediatek/mt6873/mt6873-dai-pcm.c:401:25: error: invalid application of 'sizeof' to an incomplete type 'struct snd_soc_dai_driver []'
sound/soc/mediatek/mt6853/mt6853-dai-hw-gain.c:200:4: error: field designator 'symmetric_samplebits' does not refer to any field in type 'struct snd_soc_dai_driver'; did you mean 'symmetric_sample_bits'?
sound/soc/mediatek/mt6853/mt6853-dai-hw-gain.c:220:4: error: field designator 'symmetric_rates' does not refer to any field in type 'struct snd_soc_dai_driver'; did you mean 'symmetric_rate'?
sound/soc/mediatek/mt6853/mt6853-dai-hw-gain.c:222:4: error: field designator 'symmetric_samplebits' does not refer to any field in type 'struct snd_soc_dai_driver'; did you mean 'symmetric_sample_bits'?
sound/soc/mediatek/mt6853/mt6853-dai-hw-gain.c:239:25: error: invalid application of 'sizeof' to an incomplete type 'struct snd_soc_dai_driver []'
sound/soc/mediatek/mt6853/mt6853-dai-pcm.c:362:4: error: field designator 'symmetric_rates' does not refer to any field in type 'struct snd_soc_dai_driver'; did you mean 'symmetric_rate'?
sound/soc/mediatek/mt6853/mt6853-dai-pcm.c:363:4: error: field designator 'symmetric_samplebits' does not refer to any field in type 'struct snd_soc_dai_driver'; did you mean 'symmetric_sample_bits'?
sound/soc/mediatek/mt6853/mt6853-dai-pcm.c:383:4: error: field designator 'symmetric_rates' does not refer to any field in type 'struct snd_soc_dai_driver'; did you mean 'symmetric_rate'?
sound/soc/mediatek/mt6853/mt6853-dai-pcm.c:384:4: error: field designator 'symmetric_samplebits' does not refer to any field in type 'struct snd_soc_dai_driver'; did you mean 'symmetric_sample_bits'?
sound/soc/mediatek/mt6853/mt6853-dai-pcm.c:401:25: error: invalid application of 'sizeof' to an incomplete type 'struct snd_soc_dai_driver []'

Change-Id: Iee2946f7f73c086c3c3e5eb68ef8b5806b9a232b
Signed-off-by: Miles Chen <miles.chen@mediatek.com>
Feature: [Module]Kernel Maintenance
CR-Id: ALPS05625693