battery: fix warn_unused_result build breaks
Errors:
drivers/power/supply/mtk_battery.c:3057:4: error: ignoring return value of function declared with 'warn_unused_result' attribute [-Werror,-Wunused-result]
drivers/power/supply/mtk_battery.c:3069:4: error: ignoring return value of function declared with 'warn_unused_result' attribute [-Werror,-Wunused-result]
drivers/power/supply/mtk_battery.c:3080:4: error: ignoring return value of function declared with 'warn_unused_result' attribute [-Werror,-Wunused-result]

Feature: [Module]Kernel Maintenance
Change-Id: I197501b4cb485fb31b16d42153e56bfd28b03ff9
CR-Id: ALPS05610656
Signed-off-by: Miles Chen <miles.chen@mediatek.com>