cam: v4l2-imgsensor: fix uninitialized variable build breaks
Errors:
drivers/misc/mediatek/imgsensor/src-v4l2/adaptor-drv.c:615:9: error: variable 'ret' is uninitialized when used here [-Werror,-Wuninitialized]

(cherry-picked from commit 64afeb7a208f78259d160437a02d071e680ebb87)
Change-Id: I6a1984b43ab753003d00a626f421f16455b27f09
CR-Id: ALPS05511922
Feature: [Module]Kernel Maintenance
Signed-off-by: Miles Chen <miles.chen@mediatek.com>