camera_mem: fix proc_create() build break
Error:
drivers/misc/mediatek/camera_mem/camera_mem.c:878:53: error: incompatible pointer types passing 'const struct file_operations *' to parameter of type 'const struct proc_ops *' [-Werror,-Wincompatible-pointer-types]

Change-Id: Icd3793e3ee60dcebdfe008fa2e624bf1293764e2
CR-Id: ALPS05398736
Feature: [Module]Kernel Maintenance
Signed-off-by: Kuan-Ying Lee <Kuan-Ying.Lee@mediatek.com>
(cherry picked from commit f8add2de7b025bbe987648de8c7751aa7867822c)