hang: fix mmap_sem build breaks
Error:
drivers/misc/mediatek/aee/aed/aed.h:294:13: error: conflicting types for 'show_stack'
drivers/misc/mediatek/monitor_hang/monitor_hang.c:512:31: error: no member named 'mmap_sem' in 'struct mm_struct'
drivers/misc/mediatek/monitor_hang/monitor_hang.c:579:29: error: no member named 'mmap_sem' in 'struct mm_struct'
drivers/misc/mediatek/monitor_hang/monitor_hang.c:743:32: error: no member named 'mmap_sem' in 'struct mm_struct'
drivers/misc/mediatek/monitor_hang/monitor_hang.c:755:30: error: no member named 'mmap_sem' in 'struct mm_struct'
drivers/misc/mediatek/monitor_hang/monitor_hang.c:808:32: error: no member named 'mmap_sem' in 'struct mm_struct'
drivers/misc/mediatek/monitor_hang/monitor_hang.c:820:30: error: no member named 'mmap_sem' in 'struct mm_struct'

Change-Id: Idbcec94204437b0716e59049203f13815d7a83f4
CR-Id: ALPS05368193
Feature: [Module]Kernel Maintenance
Signed-off-by: Miles Chen <miles.chen@mediatek.com>