charger: fix POWER_SUPPLY_TYPE_USB_FLOAT build breaks
Errors:
drivers/power/supply/mtk_charger.c:1558:7: error: use of undeclared identifier 'POWER_SUPPLY_TYPE_USB_FLOAT'; did you mean 'POWER_SUPPLY_TYPE_USB_ACA'?
drivers/power/supply/mt6360_pmu_chg.c:633:24: error: use of undeclared identifier 'POWER_SUPPLY_TYPE_USB_FLOAT'; did you mean 'POWER_SUPPLY_TYPE_USB_ACA'?

Change-Id: If918c83cd34aca5b64c942180688052a3df24c63
CR-Id: ALPS05408933
Feature: Others
Signed-off-by: Kuan-Ying Lee <Kuan-Ying.Lee@mediatek.com>
(cherry picked from commit 99eeb287022c9306051363b5c952b400a75c5630)