Trustonic TEE: fix some allmodconfig build breaks
fix tee related allmodconfig build errors

build command:
ARCH=arm64 make mrproper allmodconfig all

Errors:
drivers/tee/gud/500/MobiCoreDriver/mci/mcloadformat.h:20:10: fatal error: 'public/mc_user.h' file not found
drivers/tee/gud/500/MobiCoreDriver/mci/mcloadformat.h:20:10: fatal error: 'public/mc_user.h' file not found
drivers/tee/gud/500/MobiCoreDriver/mci/mcifc.h:18:10: fatal error: 'platform.h' file not found
drivers/tee/gud/500/TlcTui/tlcTui.c:22:10: fatal error: 'mobicore_driver_api.h' file not found
drivers/tee/gud/500/TlcTui/tlcTui.h:19:10: fatal error: 'tui_ioctl.h' file not found
drivers/tee/gud/500/TlcTui/trustedui.c:19:10: fatal error: 't-base-tui.h' file not found
drivers/tee/gud/500/MobiCoreDriver/mci/mcimcp.h:19:10: fatal error: 'mci/mcloadformat.h' file not found
drivers/tee/gud/500/TlcTui/tui-hal.c:22:10: fatal error: 't-base-tui.h' file not found
drivers/tee/gud/500/MobiCoreDriver/mci/mcimcp.h:19:10: fatal error: 'mci/mcloadformat.h' file not found
drivers/tee/gud/500/MobiCoreDriver/mci/mcloadformat.h:20:10: fatal error: 'public/mc_user.h' file not found
drivers/tee/gud/500/MobiCoreDriver/mci/mcifc.h:18:10: fatal error: 'platform.h' file not found
drivers/tee/gud/500/MobiCoreDriver/mci/mcloadformat.h:20:10: fatal error: 'public/mc_user.h' file not found
drivers/tee/gud/500/MobiCoreDriver/mci/mcimcp.h:19:10: fatal error: 'mci/mcloadformat.h' file not found
drivers/tee/gud/500/MobiCoreDriver/mci/mcloadformat.h:20:10: fatal error: 'public/mc_user.h' file not found
drivers/tee/gud/500/MobiCoreDriver/mci/mciiwp.h:19:10: fatal error: 'public/GP/tee_client_types.h' file not found
drivers/tee/gud/500/MobiCoreDriver/mci/mciiwp.h:19:10: fatal error: 'public/GP/tee_client_types.h' file not found
drivers/tee/gud/500/MobiCoreDriver/mci/mciiwp.h:19:10: fatal error: 'public/GP/tee_client_types.h' file not found

Cc: Jackson Chang <jackson-kt.chang@mediatek.com>
Change-Id: Ic921488708c36cd0bb2079a2b69d0965069e7e6c
Signed-off-by: Miles Chen <miles.chen@mediatek.com>
Feature: Kernel SI Operation
CR-Id: ALPS05903624