lpm: fix __nocfi build breaks
Errors:
drivers/misc/mediatek/lpm/modules/platform/mt6873/suspend/mt6873_suspend.c:72:13: error: variable has incomplete type 'void'
drivers/misc/mediatek/lpm/modules/platform/mt6873/suspend/mt6873_suspend.c:72:20: error: expected ';' after top level declarator
drivers/misc/mediatek/lpm/modules/platform/mt6873/suspend/mt6873_suspend.c:195:3: error: use of undeclared identifier 'mt6873_model_suspend'; did you mean 'mt6873_model_suspend_init'?
drivers/misc/mediatek/lpm/modules/platform/mt6873/suspend/mt6873_suspend.c:195:3: error: member reference base type 'int (void)' is not a structure or union
drivers/misc/mediatek/lpm/modules/platform/mt6873/suspend/mt6873_suspend.c:195:26: error: use of undeclared identifier 'mt6873_suspend_s2idle_prompt'; did you mean '__mt6873_suspend_prompt'?
drivers/misc/mediatek/lpm/modules/platform/mt6873/suspend/mt6873_suspend.c:195:3: error: use of undeclared identifier 'mt6873_model_suspend'; did you mean 'mt6873_model_suspend_init'?
drivers/misc/mediatek/lpm/modules/platform/mt6873/suspend/mt6873_suspend.c:195:3: error: member reference base type 'int (void)' is not a structure or union
drivers/misc/mediatek/lpm/modules/platform/mt6873/suspend/mt6873_suspend.c:195:3: error: use of undeclared identifier 'mt6873_model_suspend'; did you mean 'mt6873_model_suspend_init'?
drivers/misc/mediatek/lpm/modules/platform/mt6873/suspend/mt6873_suspend.c:195:3: error: member reference base type 'int (void)' is not a structure or union
drivers/misc/mediatek/lpm/modules/platform/mt6873/suspend/mt6873_suspend.c:195:3: error: use of undeclared identifier 'mt6873_model_suspend'; did you mean 'mt6873_model_suspend_init'?
drivers/misc/mediatek/lpm/modules/platform/mt6873/suspend/mt6873_suspend.c:195:3: error: member reference base type 'int (void)' is not a structure or union
drivers/misc/mediatek/lpm/modules/platform/mt6873/suspend/mt6873_suspend.c:198:6: error: use of undeclared identifier 'mt6873_suspend_s2idle_reflect'
drivers/misc/mediatek/lpm/modules/platform/mt6873/suspend/mt6873_suspend.c:199:39: error: use of undeclared identifier 'mt6873_model_suspend'; did you mean 'mt6873_model_suspend_init'?
drivers/misc/mediatek/lpm/modules/platform/mt6873/suspend/mt6873_suspend.c:201:3: error: use of undeclared identifier 'mt6873_model_suspend'; did you mean 'mt6873_model_suspend_init'?
drivers/misc/mediatek/lpm/modules/platform/mt6873/suspend/mt6873_suspend.c:201:3: error: member reference base type 'int (void)' is not a structure or union
drivers/misc/mediatek/lpm/modules/platform/mt6873/suspend/mt6873_suspend.c:201:26: error: use of undeclared identifier 'mt6873_suspend_system_prompt'; did you mean '__mt6873_suspend_prompt'?
drivers/misc/mediatek/lpm/modules/platform/mt6873/suspend/mt6873_suspend.c:201:3: error: use of undeclared identifier 'mt6873_model_suspend'; did you mean 'mt6873_model_suspend_init'?
drivers/misc/mediatek/lpm/modules/platform/mt6873/suspend/mt6873_suspend.c:201:3: error: member reference base type 'int (void)' is not a structure or union
drivers/misc/mediatek/lpm/modules/platform/mt6873/suspend/mt6873_suspend.c:201:3: error: use of undeclared identifier 'mt6873_model_suspend'; did you mean 'mt6873_model_suspend_init'?
fatal error: too many errors emitted, stopping now [-ferror-limit=]

Change-Id: Ib2bddebd169f7bf988b37d181eae9e13708e7830
CR-Id: ALPS05398736
Feature: [Module]Kernel Maintenance
Signed-off-by: Kuan-Ying Lee <Kuan-Ying.Lee@mediatek.com>
(cherry picked from commit 9a052194d6aa7e8e01ffbddbc55787173d6295ea)