regulator: mt6362: fix regulator_linear_range build breaks
Errors:
/mfs/mtkslt0480/mtk04267/CAS_REAL/alps-dev-r0_bsp-common-kernel-5_4--2020_12_13_23_00/merged/kernel-mainline/drivers/regulator/mt6362-regulator.c:192:56: error: array has incomplete element type 'const struct regulator_linear_range'
/mfs/mtkslt0480/mtk04267/CAS_REAL/alps-dev-r0_bsp-common-kernel-5_4--2020_12_13_23_00/merged/kernel-mainline/drivers/regulator/mt6362-regulator.c:227:56: error: array has incomplete element type 'const struct regulator_linear_range'

Change-Id: Icd8e01fd563ecce526feaa001f3de9814347b407
CR-Id: ALPS05489813
Feature: [Module]Kernel Maintenance
Signed-off-by: Miles Chen <miles.chen@mediatek.com>