[ALPS04983577] mm/huge_memory: fix buidl breaks caused by SPF
Fix the following build break caused by SPF, using ARCH=arm64
defconfig.

mm/huge_memory.c:2295:46: error: too few arguments to function call,
expected 3.

Note that we are not use mm/huge_memory.c now.

MTK-Commit-Id: 43cbff0e321c58e9030434bc73709d9543de0677

Change-Id: Id584a4927871ba5e9b07cb0cb199b99636420850
Feature: [Module]Kernel Memory Management
Signed-off-by: Miles Chen <miles.chen@mediatek.com>
CR-Id: ALPS04983577