apusys: fix no member named 'min_freq' build breaks
Error:
drivers/misc/mediatek/apusys/power/2.0/mar/apu_power_table.c:358:36: error: no member named 'min_freq' in 'struct devfreq'
drivers/misc/mediatek/apusys/power/2.0/mar/apu_power_table.c:368:36: error: no member named 'max_freq' in 'struct devfreq'

Feature: [Module]Kernel Maintenance
Change-Id: Id53a51a9c417cbd72e017f22b316f48201258a20
CR-Id: ALPS05363693
Signed-off-by: Miles Chen <miles.chen@mediatek.com>