drivers: pinctrl: Export msm_qup_write
Commit 9c0e5c705430 ("drivers: pinctrl: Add support for read/write of QUP
registers") added msm_qup_write but didn't export it resulting in the
following error:

  ERROR: "msm_qup_write" [drivers/i3c/master/i3c-master-msm-geni.ko] undefined!

Change-Id: Ic0dedbadc6822cc2a8afe69ff71a9cd95e7c8665
Signed-off-by: Jordan Crouse <jcrouse@codeaurora.org>