[ALPS04721345] aee: fix build errors
Fix build errors when "# CONFIG_MTK_RAM_CONSOLE is not set"
Details
kernel-4.14/drivers/misc/mediatek/aee/mrdump/mrdump_mini.c:45:10: fatal
error: mach/memory_layout.h file not found
kernel-4.14/drivers/misc/mediatek/aee/mrdump/mrdump_panic.c:34:
kernel-4.14/drivers/misc/mediatek/include/mt-plat/mtk_ram_console.h:272:20:
error: static declaration of aee_rr_rec_kaslr_offset follows
non-static declaration
kernel-4.14/drivers/misc/mediatek/aee/mrdump/mrdump_private.h:65:13:
note: previous declaration is here

MTK-Commit-Id: 8851783659208a76e1191bea53661a3d861136e2

Change-Id: Ib075c6ef3c85366d066bb7c1460e9a2a5f536c74
Signed-off-by: Xinghua Yang <xinghua.yang@mediatek.com>
CR-Id: ALPS04721345
Feature: Android Exception Engine(AEE)
(cherry picked from commit 58272f2a560d090ac5ad6d5cd0a609866055774c)