[ALPS04783226] edma: fix build breaks when CONFIG_KASAN=y
Fix the following build breaks by moving the definition
to edma_driver.c.

../drivers/misc/mediatek/apusys/edma/edma_driver.h:26:22:
error: ‘edma_class’ defined but not used [-Werror=unused-variable]

MTK-Commit-Id: f85bfe8da3ae6620c2bc876398f063fc7b3dd03f

Change-Id: I0313708ca00e88824a7c9191c6d4e4415c2b9b0c
CR-Id: ALPS04783226
Feature: [Module] APUSYS
Signed-off-by: Miles Chen <miles.chen@mediatek.com>