cpufreq_v1: fix proc_create_data() build breaks
Error:
drivers/misc/mediatek/cpufreq_v1/eem-dbg.c:840:15: error: incompatible pointer types passing 'const struct file_operations *' to parameter of type 'const struct proc_ops *' [-Werror,-Wincompatible-pointer-types]
drivers/misc/mediatek/cpufreq_v1/eem-dbg.c:858:5: error: incompatible pointer types passing 'const struct file_operations *' to parameter of type 'const struct proc_ops *' [-Werror,-Wincompatible-pointer-types]
drivers/misc/mediatek/cpufreq_v1/cpufreq-dbg.c:311:11: error: incompatible pointer types passing 'const struct file_operations *' to parameter of type 'const struct proc_ops *' [-Werror,-Wincompatible-pointer-types]
drivers/misc/mediatek/cpufreq_v1/cpufreq-dbg.c:315:11: error: incompatible pointer types passing 'const struct file_operations *' to parameter of type 'const struct proc_ops *' [-Werror,-Wincompatible-pointer-types]
drivers/misc/mediatek/cpufreq_v1/cpufreq-dbg.c:319:11: error: incompatible pointer types passing 'const struct file_operations *' to parameter of type 'const struct proc_ops *' [-Werror,-Wincompatible-pointer-types]
drivers/misc/mediatek/cpufreq_v1/cpufreq-dbg.c:323:11: error: incompatible pointer types passing 'const struct file_operations *' to parameter of type 'const struct proc_ops *' [-Werror,-Wincompatible-pointer-types]

Change-Id: Ib88bb1f36b49c47ca44a402074311ab486f4a0e8
CR-Id: ALPS05396263
Feature: [Module]Kernel Maintenance
Signed-off-by: Kuan-Ying Lee <Kuan-Ying.Lee@mediatek.com>