charger: fix mpi and phys_put() build breaks
Error:
drivers/power/supply/mt6360_pmu_chg.c:443:13: error: too few arguments to function call, expected 2, have 1
drivers/power/supply/mt6360_pmu_chg.c:885:17: error: incomplete definition of type 'struct mt6360_pmu_info'
drivers/power/supply/mt6360_pmu_chg.c:887:41: error: incomplete definition of type 'struct mt6360_pmu_info'
drivers/power/supply/mt6360_pmu_chg.c:895:41: error: incomplete definition of type 'struct mt6360_pmu_info'
drivers/power/supply/mt6360_pmu_chg.c:903:41: error: incomplete definition of type 'struct mt6360_pmu_info'
drivers/power/supply/mt6360_pmu_chg.c:908:19: error: incomplete definition of type 'struct mt6360_pmu_info'
drivers/power/supply/mt6360_pmu_chg.c:2287:14: error: incomplete definition of type 'struct mt6360_pmu_info'
drivers/power/supply/mt6360_pmu_chg.c:2370:17: error: incomplete definition of type 'struct mt6360_pmu_info'
drivers/power/supply/mt6360_pmu_chg.c:2372:41: error: incomplete definition of type 'struct mt6360_pmu_info'
drivers/power/supply/mt6360_pmu_chg.c:2383:41: error: incomplete definition of type 'struct mt6360_pmu_info'
drivers/power/supply/mt6360_pmu_chg.c:2391:42: error: incomplete definition of type 'struct mt6360_pmu_info'
drivers/power/supply/mt6360_pmu_chg.c:2399:42: error: incomplete definition of type 'struct mt6360_pmu_info'
drivers/power/supply/mt6360_pmu_chg.c:2404:19: error: incomplete definition of type 'struct mt6360_pmu_info'

Signed-off-by: Miles Chen <miles.chen@mediatek.com>
Change-Id: I92724f9a070c547237d465ed46659a606b4e6ddc
CR-Id: ALPS05298037
Feature: [Module]Kernel Maintenance
Signed-off-by: Miles Chen <miles.chen@mediatek.com>
Source_Git_Sha: a7c2992b32e87736906fb5badecd5c39a83a775d