Mtkcam: fix unused variable/function build breaks
Errors:
drivers/misc/mediatek/cameraisp/rsc/isp_6s/camera_rsc.c:1848:21: error: unused variable 'sec' [-Werror,-Wunused-variable]
drivers/misc/mediatek/cameraisp/rsc/isp_6s/camera_rsc.c:1849:16: error: unused variable 'usec' [-Werror,-Wunused-variable]
drivers/misc/mediatek/cameraisp/dpe/isp_60/camera_dpe.c:3245:21: error: unused variable 'sec' [-Werror,-Wunused-variable]
drivers/misc/mediatek/cameraisp/dpe/isp_60/camera_dpe.c:3246:16: error: unused variable 'usec' [-Werror,-Wunused-variable]
drivers/misc/mediatek/cameraisp/dpe/isp_60/videobuf2-dma-contig.c:337:14: error: unused function 'vb2_dc_dmabuf_ops_kmap' [-Werror,-Wunused-function]

Change-Id: I0f2280bf9986017b621cbebf89f4f8c46914aec5
CR-Id: ALPS05511922
Feature: [Module]Kernel Maintenance
Signed-off-by: Miles Chen <miles.chen@mediatek.com>
(cherry picked from commit c50eeda774c57653edceca4af151bca535d847f6)