v4l2: fix undeclared identifier V4L2_CTRL_CLASS_MPEG build breaks
Errors:
drivers/media/platform/mtk-videobuf/mtk_dma_contig.c:69:51: error: too few arguments to function call, expected 2, have 1
drivers/media/platform/mtk-vcodec/mtk_vcodec_dec.c:2507:7: error: use of undeclared identifier 'V4L2_CTRL_CLASS_MPEG'
drivers/media/platform/mtk-vcodec/mtk_vcodec_dec.c:2517:7: error: use of undeclared identifier 'V4L2_CTRL_CLASS_MPEG'
drivers/media/platform/mtk-vcodec/mtk_vcodec_dec.c:2525:7: error: use of undeclared identifier 'V4L2_CTRL_CLASS_MPEG'
drivers/media/platform/mtk-vcodec/mtk_vcodec_dec.c:2532:7: error: use of undeclared identifier 'V4L2_CTRL_CLASS_MPEG'
drivers/media/platform/mtk-vcodec/mtk_vcodec_dec.c:2540:7: error: use of undeclared identifier 'V4L2_CTRL_CLASS_MPEG'
drivers/media/platform/mtk-vcodec/mtk_vcodec_dec.c:2548:7: error: use of undeclared identifier 'V4L2_CTRL_CLASS_MPEG'
drivers/media/platform/mtk-vcodec/mtk_vcodec_dec.c:2555:7: error: use of undeclared identifier 'V4L2_CTRL_CLASS_MPEG'
drivers/media/platform/mtk-vcodec/mtk_vcodec_enc.c:245:7: error: use of undeclared identifier 'V4L2_CTRL_CLASS_MPEG'
drivers/media/platform/mtk-vcodec/mtk_vcodec_dec.c:2576:18: error: use of undeclared identifier 'V4L2_CTRL_CLASS_MPEG'
drivers/media/platform/mtk-vcodec/mtk_vcodec_enc.c:347:7: error: use of undeclared identifier 'V4L2_CTRL_CLASS_MPEG'
drivers/media/platform/mtk-vcodec/mtk_vcodec_dec.c:2588:7: error: use of undeclared identifier 'V4L2_CTRL_CLASS_MPEG'
drivers/media/platform/mtk-vcodec/mtk_vcodec_enc.c:354:7: error: use of undeclared identifier 'V4L2_CTRL_CLASS_MPEG'
drivers/media/platform/mtk-vcodec/mtk_vcodec_dec.c:2592:7: error: use of undeclared identifier 'V4L2_CTRL_CLASS_MPEG'
drivers/media/platform/mtk-vcodec/mtk_vcodec_enc.c:361:7: error: use of undeclared identifier 'V4L2_CTRL_CLASS_MPEG'
drivers/media/platform/mtk-vcodec/mtk_vcodec_enc.c:369:7: error: use of undeclared identifier 'V4L2_CTRL_CLASS_MPEG'
drivers/media/platform/mtk-vcodec/mtk_vcodec_dec.c:2600:7: error: use of undeclared identifier 'V4L2_CTRL_CLASS_MPEG'
drivers/media/platform/mtk-vcodec/mtk_vcodec_enc.c:376:7: error: use of undeclared identifier 'V4L2_CTRL_CLASS_MPEG'
drivers/media/platform/mtk-vcodec/mtk_vcodec_dec.c:2607:7: error: use of undeclared identifier 'V4L2_CTRL_CLASS_MPEG'
drivers/media/platform/mtk-vcodec/mtk_vcodec_enc.c:390:7: error: use of undeclared identifier 'V4L2_CTRL_CLASS_MPEG'
drivers/media/platform/mtk-vcodec/mtk_vcodec_dec.c:2614:7: error: use of undeclared identifier 'V4L2_CTRL_CLASS_MPEG'
drivers/media/platform/mtk-vcodec/mtk_vcodec_enc.c:404:7: error: use of undeclared identifier 'V4L2_CTRL_CLASS_MPEG'
drivers/media/platform/mtk-vcodec/mtk_vcodec_dec.c:2618:7: error: use of undeclared identifier 'V4L2_CTRL_CLASS_MPEG'
drivers/media/platform/mtk-vcodec/mtk_vcodec_enc.c:411:7: error: use of undeclared identifier 'V4L2_CTRL_CLASS_MPEG'
drivers/media/platform/mtk-vcodec/mtk_vcodec_dec.c:2622:7: error: use of undeclared identifier 'V4L2_CTRL_CLASS_MPEG'
drivers/media/platform/mtk-vcodec/mtk_vcodec_enc.c:418:7: error: use of undeclared identifier 'V4L2_CTRL_CLASS_MPEG'
drivers/media/platform/mtk-vcodec/mtk_vcodec_dec.c:2626:7: error: use of undeclared identifier 'V4L2_CTRL_CLASS_MPEG'
drivers/media/platform/mtk-vcodec/mtk_vcodec_enc.c:426:7: error: use of undeclared identifier 'V4L2_CTRL_CLASS_MPEG'
drivers/media/platform/mtk-vcodec/mtk_vcodec_dec.c:2630:7: error: use of undeclared identifier 'V4L2_CTRL_CLASS_MPEG'
drivers/media/platform/mtk-vcodec/mtk_vcodec_enc.c:432:7: error: use of undeclared identifier 'V4L2_CTRL_CLASS_MPEG'
drivers/media/platform/mtk-vcodec/mtk_vcodec_dec.c:2634:7: error: use of undeclared identifier 'V4L2_CTRL_CLASS_MPEG'
drivers/media/platform/mtk-vcodec/mtk_vcodec_enc.c:438:7: error: use of undeclared identifier 'V4L2_CTRL_CLASS_MPEG'
drivers/media/platform/mtk-vcodec/mtk_vcodec_dec.c:2683:11: error: use of undeclared identifier 'V4L2_CTRL_CLASS_MPEG'
drivers/media/platform/mtk-vcodec/mtk_vcodec_enc.c:444:7: error: use of undeclared identifier 'V4L2_CTRL_CLASS_MPEG'
drivers/media/platform/mtk-vcodec/mtk_vcodec_enc.c:450:7: error: use of undeclared identifier 'V4L2_CTRL_CLASS_MPEG'
drivers/media/platform/mtk-vcodec/mtk_vcodec_enc.c:456:7: error: use of undeclared identifier 'V4L2_CTRL_CLASS_MPEG'
drivers/media/platform/mtk-vcodec/mtk_vcodec_enc.c:478:7: error: use of undeclared identifier 'V4L2_CTRL_CLASS_MPEG'
drivers/media/platform/mtk-vcodec/mtk_vcodec_enc.c:484:7: error: use of undeclared identifier 'V4L2_CTRL_CLASS_MPEG'
drivers/media/platform/mtk-vcodec/mtk_vcodec_enc.c:2559:11: error: use of undeclared identifier 'V4L2_CTRL_CLASS_MPEG'
fatal error: too many errors emitted, stopping now [-ferror-limit=]

Change-Id: I4d776bbee2b14beef3385982293e6f64ba80ea23
Signed-off-by: Miles Chen <miles.chen@mediatek.com>
CR-Id: ALPS05568046
Feature: [Module]Kernel Maintenance