iommu/arm-smmu: Fix a few compiler warnings
The following error occurs when manually building the kernel.

 ./include/trace/define_trace.h:95:43: fatal error: ./arm-smmu-trace.h: No such
 file or directory
 #include TRACE_INCLUDE(TRACE_INCLUDE_FILE)

Fix the path so it can always be found.

Also, with gcc 7.4.1 the following warning occurs:

 drivers/iommu/arm-smmu.c:4382:17: warning: format '%d' expects argument of type
 'int', but argument 3 has type 'long int' [-Wformat=]
 dev_err(dev, "Unable to read interconnect path from devicetree rc: %d\n",

Because PTR_ERR is a cast from a pointer, it is always a unsigned long. Fix
the argument.

Change-Id: Ic0dedbad992eaa72d9a6127316c4ffbbb8816ef8
Signed-off-by: Jordan Crouse <jcrouse@codeaurora.org>