clk: mediatek: fix build breaks if CLKDBG_PM_DOMAIN is set
Errors:
drivers/clk/mediatek/clkdbg.c:1880:6: error: unused variable 'pg' [-Werror,-Wunused-variable]
drivers/clk/mediatek/clkdbg.c:1878:28: error: unused variable 'pd' [-Werror,-Wunused-variable]

(cherry-picked from commit 504747fb398c76aed13a25b083be872a122a72da)
Change-Id: I94e7765adcebe184e2248a49f52c27a615c67520
CR-Id: ALPS05511922
Feature: [Module]Kernel Maintenance
Signed-off-by: Miles Chen <miles.chen@mediatek.com>
(cherry picked from commit cafe25cc4ee7148eebc78d508f33bed2d4ba8719)